#+TITLE: June 25, 2023
#+INCLUDE: ~/org/blog/noumena/header.org


* Morning

Having vomited several times last night, I was not prepared to cook anything this morning. Although I felt better than I did last night, I was still really struggling. I had to make something quick and easy. She ate Oatmeal and puffs for breakfast.

I was so ill that I would just lay on the couch this morning while she would play. I turned the TV on, but she was quite disinterested for the most part. I just let her destroy the house--getting into the kitchen cabinets, throwing toys, ripping up baby wipes etc.


Even in my state, there were a few times I got her to lay down with me and cuddle. This helped a lot. At about 10am we took maybe a 45 minutes nap on the bed and it was wonderful. There were more brief naps while we were watching Sesame Street. Noumena really did make it very easy on me in the morning.

* Afternoon

Oksana arrives and I'm laying out the couch. Thank goodness. Right when she gets here, she starts taking care of us. She brought a bunch of medicine to help me with my stomach. And Noumena absolutely loves playing with her. She helps clean the house and is honestly a godsend. Oksana brought this squeezable mango-carrot packet with her for Noumena to eat and I think it's fine for Noumena to handle it herself. The first thing Noumena does is squirt the mango and carrot mixture all over the carpet! We had to show her better what to do, but thankfully Chalmers cleaned it all up.

Noumena naps shortly after she arrives giving Oksana time to make food for us. Oksana makes soup and rice and when Noumena wakes up she's starving... Or maybe she just really liked Oksana's soup. She eats so much food like I haven't been feeding her.

#+begin_export html
<div class="video-container">
<iframe width="1870" height="733" src="https://www.youtube.com/embed/MnfSKhRbLN8" title="Playing with Oksana" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export

#+begin_export html
<div class="video-container">
<iframe width="1870" height="733" src="https://www.youtube.com/embed/RB2yzMNusW0" title="Rolling balls with Oksana" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export


#+begin_export html
<div class="video-container">
<iframe width="435" height="774" src="https://www.youtube.com/embed/FkMIHYvdeOs" title="Talking on the phone" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export


#+begin_export html
<div class="video-container">
<iframe width="1870" height="733" src="https://www.youtube.com/embed/-qBNJFixbUY" title="Riding her train" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export


* Evening

Although I laid around all day, Oksana eventually prompts me to take Noumena to the park. That's good because Noumena's not used to not going outside all day. It's really rough for me, but it ends up being okay. Once we get to the park, Noumena goes down the slide several times all by herself and we take her on the swing.

We get back home at about 8pm and I think she's hungry, so we eat more of Oksana's soup. She eats a lot of it, I'm impressed. My baby must be growing.

We follow our usual bed time routine.

Good night, sweet baby. When Daddy feels better, he'll write better journal entries. 
