#+TITLE: Dialogue On Freewill
#+INCLUDE: ~/org/blog/philosophy/header.org

* Preface

A conversation I had with a friend about freewill I wanted to share with any personal details obscured

* Conversation

 * *V*:
Do people cling unto the notion of free will in order to take credit for good things they did and blame others for bad things they did?

 * *Me*:
I don't know what you mean by "cling to it." You can't help but believe in freewill.

 * *V*:
I mean not everyone believes in it

 * *Me*:
Whether you formally admit to it or not, you make choices.

 * *V*:
And when they are told it doesn't exist and they consider it

There's an emotional reaction

 * *Me*:
I think it's really stupid to discuss unless you're analyzing it.

 * *V*:
To be told you don't make choices implicates you in something

That's why it matters whether it's true or not

 * *Me*:
It's interesting philosophically to talk about the nature of freedom, but it's not at all interesting to discuss whether it exists. It's like denying you have hands.

 * *V*:
I disagree

I don't think it exists

And there are implications to it

 * *Me*:
Anyone who says they deny it is just equivocating from the standard notion they use when they talk about choices they make in every day life because they're conditioned by some philosophical brain parasite.

 * *V*:
They make choices like computers make choices

Or trees

 * *Me*:
That's not true, but if it is it's irrelevant.

 * *V*:
I think it is

 * *Me*:
That just means it makes sense to feel indignation towards computers and trees. But it doesn't, so they don't have freedom.

 * *V*:
No

I mean

I do feel anger towards inanimate objects

 * *Me*:
Does it make sense that you do that?

To you?

 * *V*:
Not any less than feeling that way towards people

 * *Me*:
Those things don't have beliefs. People do.

 * *V*:
Well

 * *Me*:
You're not saying a computer did something wrong when you get angry

 * *V*:
At best they can't tell you their beliefs and people can

But

The beliefs people have don't depend on them

 * *Me*:
It's not about telling or not telling. You don't believe they have beliefs

 * *V*:
They're assigned beliefs at any given moment

 * *Me*:
I don't know what that means and it's irrelevant either way

The nature of believing is sufficient

Whether assigned or not whatever it means doesn't matter

 * *V*:
Sure it matters

 * *Me*:
Not in the slightest

The belief contents might have some normative impact, but believing is sufficient for normative attitudes

That's all that's relevant towards freedom

 * *V*:
A comp can be assigned beliefs

 * *Me*:
I don't think that's true, but if it is it just implies that computers have freedom

I don't think computers think

 * *V*:
You'd never know

 * *Me*:
I don't know why I'd accept that, but it's irrelevant to the discussion

 * *V*:
It is

 * *Me*:
Everything I'm saying just applies to computers mutatus mutandis if they have beliefs, so it's irrelevant

And trees or whatever

 * *V*:
Thinking is not sufficient for the notion of freedom

 * *Me*:
That's just a confusion

To think it's to have desires. To act on desires is to be free

 * *V*:
You might as well not be free

It's the same

 * *Me*:
I don't know what that means.

 * *V*:
As not having desires and not having an ability to act on em

 * *Me*:
To not have desires is to not have a mind.

I don't know how it makes sense to say it makes no difference whether you have a mind

Just seems straightforwardly nonsensical. What could matter more?

 * *V*:
I'm saying the mind being aware of it's existence is inconsequential to the possessor of that mind

 * *Me*:
I don't know what it means to have a mind you're unaware of. That's just not having a mind.

 * *V*:
A computer is something capable of processing information but has no awareness of itself or what information it's processing

 * *Me*:
Then it doesn't have a mind. Therefore it isn't free

 * *V*:
It behaves just like a mind with the only distinction being that it doesn't have an internal experience of it

 * *Me*:
I don't know what that means

 * *V*:
Right im seeing I'm saying the distinction between having a mind and not doesn't grant freedom

 * *Me*:
Yeah but I don't know what that means. It just sounds like you're equivocating on freedom.

 * *V*:
You just get an experience of a lack of the same lack of freedom that a computer has

 * *Me*:
Which is what I said makes the conversation stupid.

 * *V*:
I don't think so

I'm saying it doesn't matter that we have minds

 * *Me*:
Because that equivocation just means you're changing the subject.

 * *V*:
It doesn't change our predicament

 * *Me*:
Freedom is a mental notion.

So you're changing the subject if the mind is irrelevant to your conception.

 * *V*:
To be aware of what you're doing isn't the same as authoring what you're doing

 * *Me*:
I don't know what "authoring what you're doing" is besides deliberating and making choices. You make choices by acting on your desires.

You think "should I or should I not do x" and act accordingly.

Thinking is the crucial part

You don't watch things happen to you. You act!

 * *V*:
Well I'm saying you do watch what happens to you

 * *Me*:
You don't just watch yourself do things. You engage the world.

No. If that were true, there should be no difference from your perspective watching me do something and doing it yourself.

Or watching anyone for that matter.

 * *V*:
The difference is I watch myself do what I want

 * *Me*:
You would view yourself as a mechanism.

 * *V*:
But not even always

 * *Me*:
You wouldn't intend anything.

You wouldn't try

Or attempt

Or whatever.

 * *V*:
Sometimes I do things I don't want just like watching someone else do em

 * *Me*:
Computers don't try. Neither do trees. They just react.

 * *V*:
I'm saying so do we

 * *Me*:
The premise of the conversation betrays the falsity of this claim.

 * *V*:
Only thing is watching you I get a 3rd person view with no internal experience

 * *Me*:
You're just changing the subject if you're saying you don't try to do anything.

 * *V*:
But with myself I get a 1st person view and an experience of compulsion

 * *Me*:
First person experience is what makes it freedom. It's constitutive of it

That's the point

You engage the world
 * *Me*:
The world doesn't just happen to you

 * *V*:
I'm saying it does

 * *Me*:
Not from your perspective

 * *V*:
The internal experience is the first thing that happens to you

 * *Me*:
If it did, you wouldn't intend

You do intend so it doesn't.

 * *V*:
Intention happens to me too

 * *Me*:
Whether that's true is irrelevant.

 * *V*:
The compulsion drives me to react to my intentions

 * *Me*:
You don't react to your intentions.

You intend.

 * *V*:
I'm saying intention happens to you too

It's helpless

 * *Me*:
There are 2 ways of interpreting that. One is nonsensical the other is irrelevant.

 * *V*:
They cannot be changed and they cannot be decided they precede all experience of deliberation aka thoughts

 * *Me*:
On the one hand, you're viewing intention 3rd personally which is nonsensical. On the other, you're saying you don't intend to have every intention which is irrelevant.

 * *V*:
Intent occurs to you

Like a virus

Or a disease

 * *Me*:
I don't know which interpretation you're using when you're saying that. The nonsensical one or the irrelevant one.

Intention is first personal, so it's nonsense to view it third personally.

It doesn't make a difference whether or not for each intention you can intend to have it.

Although that's also nonsense

But even if it's not nonsense, it doesn't matter.

Your philosophical assumptions are just trash which are leading you into confusion.

 * *V*:
I don't see the nonsense

 * *Me*:
Which is really bizarre considering that denying freedom is tantamount to denying you have a mind.

 * *V*:
A mind just means awareness of existence

 * *Me*:
A mind is having intentions.

 * *V*:
I think a mind is knowing you exist everything else is optional

 * *Me*:
Look. If I asked you to choose to reword what you're about to right, you can make that choice.

You know what that means.

 * *V*:
Yeh

 * *Me*:
You can form the intention to do so and act on it.

That's all the is to it.

Just like if I told you to raise your arm.

 * *V*:
I don't see how that's any different than giving the same command to a comp

 * *Me*:
You can deliberate, see if that's a good idea and do it if you want.

Computers don't have wants.

They don't have minds.

 * *V*:
They don't know they exist

 * *Me*:
They will or won't.

They won't succeed or fail.

 * *V*:
But you can program them to do everything exactly like you would do

 * *Me*:
You might fail in getting the computer to do what you want.

But the computer won't.

 * *V*:
If that doesn't say something about freedom then I dunno

 * *Me*:
Just sounds like you're some sort of eliminativist about mentality.

Freedom is normative.

 * *V*:
You can make a machine that will live out your life identically in any given identical scenario

 * *Me*:
I don't know what it means for it to be identical and not have a mind.

Just sounds contradictory.

Unless you're making a computer that makes choices.

 * *V*:
Like a program which will predict what you will do and say at any given moment in any given circumstance

 * *Me*:
In which case, I agree.

I don't see how prediction is relevant.

Accurately predicting every choice one makes isn't the same thing as not making choices the same way accurately predicting every whether event makes it not rain.

 * *V*:
Well when it rains it happens to rain

When you do something you happen to do it

 * *Me*:
You can do something without choosing it, but I don't see how that's relevant. If I strike your knee with a mallet and you move it, that doesn't mean you chose it just because you can choose it.

Likewise, just because you chose to move your knee doesn't mean I struck it with a mallet.

The difference is intention... Obviously.

In one case you intended in the other you didn't.

 * *V*:
But the intent to move your knee is just a different kind of mallet

 * *Me*:
Again that just sounds like you're denying mentality.

You don't view it like that.

You intend

 * *V*:
It's an internal compulsion

 * *Me*:
I don't know what that means.

If it means you don't intend, then it's just nonsense.

Either way it's actually nonsense.

 * *V*:
It's a force in your consciousness which compels you to react such that you move your knee

And you're merely aware of the force

 * *Me*:
When you say force, do you just mean intention?

I don't know what it means to "merely" be aware.

 * *V*:
Yes but I'm properly identifying what an intention is in any given mind

 * *Me*:
You're not "merely" aware. You can be aware of the mallet but that's not an intention.

It sounds like you're just denying it's an intention.

You don't view the intention as happening to you.

That's what I'm saying.

You intend

 * *V*:
I'm saying you do

 * *Me*:
It's not a metaphorical mallet

No. You don't.

 * *V*:
View the intention as happening to you

 * *Me*:
Look, if you did, you would be afraid in your own body. Nothing you did would make a difference to you.

You wouldn't feel in control of anything.

So you don't view it that way

 * *V*:
Well that's kind of the thing here

 * *Me*:
You think you're in control of what you type, where you're sitting.

Etc

 * *V*:
Right you think so

 * *Me*:
That's just what it means to be in control.

 * *V*:
But it isn't so

 * *Me*:
I don't know what that means

Again it just sounds like you're not intending.

It's like you don't understand what an intention is.

Which is bizarre

Because you do.

 * *V*:
I know what they feel like

 * *Me*:
I'm saying to have no intentions is for nothing to matter to you.

 * *V*:
I experience them

But that's it

 * *Me*:
That just means nothing matters to you.

Which doesn't make and sense

You don't "just" experience them. You intend.

That's what you're not getting.

You intend.

 * *V*:
Again

Involuntary

If anything matters

I can't make it not

 * *Me*:
Intentions are by their nature voluntary.

 * *V*:
And I don't know why

 * *Me*:
That's what constitutes them.

 * *V*:
If they do matter

 * *Me*:
The fact that they're voluntary is what makes them intentions.

 * *V*:
They aren't

They occur to you

 * *Me*:
Then it just seems like you don't have the concept.

 * *V*:
Involuntarily

 * *Me*:
But you do, that's why this conversation is dumb.

 * *V*:
And you are their victim

 * *Me*:
I don't know what that means. There's nothing to contrast with in your fantasy scenario.

To be a victim is contrastive.

It's coherent under my notion and incoherent under yours.

 * *V*:
Contrary to being the author

 * *Me*:
Again, it is either just nonsense or nonsense and irrelevant.

I hate it when people talk like this because it's just like denying you have hands.

Why would I want to argue with a lunatic who thinks they don't have hands?

 * *V*:
I have hands

 * *Me*:
Exactly!

 * *V*:
There's nothing to deny

 * *Me*:
Exactly!

 * *V*:
I'm not denying I have intentions

I'm denying being their author

 * *Me*:
Being "their author" is either irrelevant and nonsensical or just nonsensical.

 * *V*:
I don't see how

 * *Me*:
Because freedom is constituted by intention.

So it doesn't matter why you intend.

 * *V*:
It does to be free

Not just why but what

 * *Me*:
No. This is just the nonsense philosophical presuppositions that are stealing your attention from the blatantly obvious fact that all it is to be free is to intend.

It couldn't be anything else.

And I'm not particularly interested in any other notion.

I don't see why anyone would be.

 * *V*:
Its insufficient

To the concept of freedom

 * *Me*:
Yeah. That's just changing the subject to one I don't know why anyone would have any interest in.

It's practically irrelevant.

It's not the notion you use when assessing your behavior or the behavior of others.

 * *V*:
Freedom to me implies options and possibilities

You have no options or possibilities

When it comes to having intentions

 * *Me*:
You have to view options and possibilities from the same perspective you intend and therefore there are options and possibilities.

Take the example with raising your arms or getting a cup of tea.

To you, you could get a cup of tea or raise your arm. Those are possibilities. And their status qua possibility is what informs your intention.

 * *V*:
I don't decide to have either of the two intentions

 * *Me*:
The intention is the decision.

 * *V*:
I helplessly have one

 * *Me*:
You're just saying you don't decide to decide. As if that's relevant.

I agree. You don't decide to decide. You just decide.

 * *V*:
I'm saying there isn't even one decide in there

 * *Me*:
That's silly.

 * *V*:
It's pre decided for me to live out however it's been decided on my behalf

 * *Me*:
You're just changing the subject again otherwise I think you're just saying gibberish.

You're deciding to have this conversation. And I'm about to decide to end it because it's so silly.

 * *V*:
Hahahaa

 * *Me*:
And I have to go to sleep

 * *V*:
Im living out the experience of participating in the conversation because of my internal compulsion to do so

;)

Have a good night
