#+TITLE: June 18, 2025
#+INCLUDE: ~/org/blog/noumena/header.org
#+INCLUDE: ~/org/blog/image-preview-header.org

#+HTML_HEAD_EXTRA:<meta property="og:image" content="https://joshua-wood.dev/noumena/2025/june/18/">
#+HTML_HEAD_EXTRA:<meta property="og:image:alt" content="June 18, 2025 alt"/>
#+HTML_HEAD_EXTRA:<meta property="og:description" content="">
#+HTML_HEAD_EXTRA:<meta name="twitter:image" content="https://joshua-wood.dev/noumena/2025/june/18/" />

* Good Morning, Sugar Butt!

I stayed up so late last night writing yesterday's journal entry. Noumena woke up late last night while I was writing and came in, so I showed her what I was writing and had her watch the videos of us playing in the rain, but getting her back to sleep was a challenge. If she went to back to sleep at all, she slept really lightly because when laying next to her, she'd arouse from sleep if I moved at all. (In fact, she just came in to steal me from tonight's journal entry). It wasn't until 45 minutes later until I was able to resume my writing and even then, she came in 15 minutes later and it was another 30 minutes before she got back to sleep the for the third time on top of already having fallen asleep later than usual to start.

Needless to say, when Noumena woke me up screaming upset about something this morning, I was extremely tired. Nevertheless, I got up to help her out. After going to the bathroom, I and asked if she wanted to watch TV. She brought her blanket onto my bed and cuddled me while I unsuccessfully attempted to fall back asleep. Mommy gets her ready and, a frown coupled with a furled lower lip accompanies pleas not to be sent to daycare. She quickly works through her sadness and follows Mommy out the door without a fuss.

-----

* Grasshoppers!

Mommy picks Noumena up from daycare---a fact that Noumena's quick to mention frequently whenever it happens---Noumena helps Mommy clean the house until I'm done working. Just as I open my office door upon leaving work, I notice a giant Eastern Lubber grasshopper has crawled onto the screen of my office window. I call to Noumena from the office doorway to draw her attention to the grasshopper. She runs to the window and smacks it right where the grasshopper is suspended. Thankfully, she didn't disturb the grasshopper. I told her not to scare the grasshopper away and ask if she wants to go outside to investigate. She's ecstatic at the prospect and leaps to go run outside.

At this time, Noumena's only wearing underwear and inside out at that, so I have to wrangle and exhilarated toddler to correct her underwear and put on shorts and shoes. She does and we make our way out the door and along side the house.

Grasping the body of the grasshopper (I assume male because of the long wings and golden hue more typical of males), his clinging claws fight me to maintain contact with the screen. Nevertheless, I'm able to maneuver him into my hands to show Noumena. Mosquitoes are pervasive on that side of the house, so I instruct Noumena to follow me to a different location. She asks why and I explain that we're trying to avoid the mosquitoes! The fence along the backside of my yard---adjacent to a small church and its cement patio---is collapsed, and I think that patio would be an appropriate place to avoid mosquitoes and handle the grasshopper so we walk there before I squat down numerous times to bring him down to Noumena's level.

The grasshopper leaps away numerous times and I remark that he's one of the more athletic grasshoppers I've seen. Eventually, he evades capture and Noumena follows him into the grassy area next to the patio where we discover another male. My attention is on the first, but Noumena without hesitation reaches down scooping up the other one---apparently very cautiously despite her swiftness---and brings him over to me. I notice that one of his forelegs is missing upon handling him. I don't think Noumena did it because it seemed as though she seemed to have grabbed him with such expertise, but I can't completely rule out that in her haste she wasn't the culprit responsible for his morbidity. I point out that he's missing a limb to her. She handles with an open palm him briefly, but is scared from previous experiences that he may begin crawling up her arm, so before I'm able to snap a photo, she shuffles him off of her hand and he ends up in the same grassy patch as the previous.

Because I want to observe Noumena grab the grasshopper again, despite her appeals to me to pick him up, I insist that she take it upon herself to seize him again. She makes several attempts, but his maneuvering the thicket of grass and leaves renders her unable to confidently do so. She follows him to a nearby tree stump where she incorrectly identifies red-shouldered bugs as beetles. I correct her identification and she repeats the correct identification before asking me to pick the beetle up. While I make several attempts to pick up the bug, Noumena's focus has been diverted back to the grasshopper until I finally, gently coax the bug onto my hands. Noumena doesn't get the chance to closely observe the bug before it flies away.

Noumena wants to see more grasshoppers, so I take her by the hand and we navigate back through the collapsed fence to our yard to find more insects. I get a hold of different species of grasshopper much smaller and nimbler than the Eastern Lubber, but as I open my palm, this grasshopper also evades Noumena's gaze as it dramatically leaps away. Mommy appears around the corner of the house and persuades Noumena to go inside to help her prepare dinner.

-----

* Dinner Time!

I rest on the couch while Mommy peals potatoes after having set Noumena on the counter top to observe. She provides Noumena with an opportunity to discard scraps and use the potato peeler. Noumena---apparently immediately---excels at using the potato peeler because her first attempt is successful at stripping away the skin which excites both her and Mommy.

We take our potatoes and green beans to the dinner table and while eating Mommy and I discuss Noumena's nutrition. The topic of Mommy sneaking unhealthy food arises and Mommy says that Noumena always catches her saying "Mommy whatcha eating?" Like a ear-worm, this phrase gets stuck in Noumena's head and in classic three year old fashion, she repeats the phrase along with "Mommy whatcha got?" several times in succession while bobbing her head side to side, mouth full of mashed potato and a smile decorating her face.

-----

* Riding In Noumena's Car

After dinner, I go back to lying on the couch, from which Noumena attempts to peel me a handful of times. Being so tired, I make every effort not to leave my lounge. Thankfully, Mommy is able to accommodate Noumena bringing her outside.

After a short period of time, Noumena appears in a toy car at the front door with Mommy. Mommy tries to convince Noumena to enter the house, but she's visibly disappointed at the prospect of her time with the car coming to a close, so I quickly decide to take up the mantle and go play with her with in her car.


#+begin_export html
<div class="video-container">
<iframe width="1547" height="564" src="https://www.youtube.com/embed/k8MxdLrIWiY" title="Rolling Around In Her Car" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export


#+begin_export html
<div class="video-container">
<iframe width="1559" height="548" src="https://www.youtube.com/embed/kGwql76dYMY" title="Holding Camera While Riding In Her Car" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export


#+begin_export html
<div class="video-container">
<iframe width="1559" height="548" src="https://www.youtube.com/embed/Bav4psP2aLI" title="More Holding Camera While Riding" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export


#+begin_export html
<div class="video-container">
<iframe width="1559" height="548" src="https://www.youtube.com/embed/Aa4bCu3h7Rk" title="Even More Holding Camera While Riding" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export

#+begin_export html
<div class="video-container">
<iframe width="1547" height="564" src="https://www.youtube.com/embed/RRta1Xyg37A" title="More Holding Camera And Riding" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export

#+begin_export html
<div class="video-container">
<iframe width="1559" height="548" src="https://www.youtube.com/embed/_ceTnnRTnlM" title="Pushing Her Car Herself" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export

Shockingly, it's Noumena who decides it's time to stop playing and change activities. She tells me she wants a snack, so we walk her car back into our garage at which time she informs me before we go that she has to pee. I'm so proud of her for having learned her body and volunteering to use the restroom instead of me having to consistently and semi-frequently goad her to the potty to prevent accidents. She's growing so fast.

-----

* Time to Get a Snack!

Just as we're leaving, we notice Jeremiah and his baby brother Josiah, so before we head to CVS, we make a brief pit stop to play with them before walking to the store. And, on our way, we see another neighbor who tells his harrowing story of having lost his wife of 31 years 5 months ago. Noumena, atop my shoulders for the conversation, witnesses the discussion drift to the discussion of pit bulls and my attitude towards them seeing as he owns one. Despite having witnessed the entire discussion, once we've concluded it, Noumena asks what I was talking to him about and I explain it in detail back to her. She interrupts the tail end of the explanation to draw my attention to a plane she'd noticed flying over head.

On our way, crossing the drainage ditch adjacent to CVS, I always stop to peer into it to see what wildlife maybe active therein. We always see the minnows swimming about, but as we're standing on the edge of the bridge, a little boy named Logan walks up from behind and is looking for turtles. We notice a pond slider seemingly approaching us which is quite odd since they're normally so skittish. I take this opportunity to film her swimming about and even crawling out of the channel approaching Logan.

#+begin_export html
<div class="video-container">
<iframe width="1559" height="548" src="https://www.youtube.com/embed/S3R_4WHeX7E" title="Found A Friendly Turtle" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export

We descended into the ditch to get a closer look at the turtle where we were swarmed and ravaged by mosquitoes---something that Logan had informed us was a risk. When we continued on our way, my commentary on the rapaciousness of the mosquitoes abounded. Noumena, becoming aware of her itching legs, concurs complaining, "Damn mosquitoes!"

Noumena asks why mosquitoes suck our blood. I tell her that it's in order to feed their young. This turns out to be incorrect. Mosquitoes simply need the proteins and iron for egg production, so I will have to correct the misunderstanding I gave her at a later time. She then asks why the baby mosquitoes need blood, and I immediately start considering all the evolutionary reasons for why that trait came to fixation. I admittedly have no idea and tell her as much. Who knows about the ancient and complex evolutionary story of the infamous mosquito?

-----

* Abiding By Our Ritual

It's 8pm---close to Noumena's bed time---by the time we get out of CVS with Noumena's selected snack and a white Gatorade I'd reluctantly purchased in hand. We have a ritual of taking our snack and drink down to a bench outside doors of the church across the drainage ditch from CVS, which is actually what ended up tipping the scales on my decision to purchase the drink. For Noumena, and by extension for me, this is an tradition for us. It's clearly formative for her and may be a memory that persists well into adulthood, so I have to honor it. So much of childhood is encapsulated in these seemingly mundane moments and experiences that on their own as an adult would have almost no significance to their bearer, but its importance to her has in turn made this a most cherished experience of mine.

I've gained so much trust in Noumena's competence. Of course, she needs to be monitored very closely still, but I'm much more confident in her growing abilities. As we leave, I tell her to be mindful of a car parked with its brake lights on. She attends to my concern despite not fully understanding what it means to be mindful. I paraphrase "mindfulness" to "paying attention".

#+begin_export html
<div class="video-container">
<iframe width="1559" height="548" src="https://www.youtube.com/embed/EHZsbfKxAn4" title="Running And Walking With Bottle" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export

On our way back, I notice that Mommy has begun walking down the street from our house towards our location presumably looking for us. I point Mommy out to Noumena which excites her. She begins to gush over how much she loves Mommy exclaiming "Mommy!" and "Mommy, I love you!" repeatedly on our approach. I set Noumena down and she eagerly runs to Mommy embracing her legs with a biggest smile on her face. Mommy announces that "she loves mommy" and I tell her that Noumena said that several times upon noticing her. Noumena concludes our walk in between Mommy and me grasping both our hands and swinging from her arms.

-----

* Bed Time

We get ready for bed immediately upon getting home. There's no time for a bath tonight. Once Noumena is dressed and ready, we climb into bed together. Noumena tells me to kiss her neck and so I do. She then begins to squeal as I tickle her with my kisses. She wants more and continues to shriek in ecstasy as the tickles continue. Her squeals are punctuated by requests for me to stop---requests which I always honor on principle---before blurting out "Do it again." I'm caught up in the same ecstasy. Though she wants me to continue, it turns into a wrestling match and my tickles are met with physical resistance she wants me to overcome. She wants to be overwhelmed with kisses.

Following our wrestling match, when it's finally time to wind down, Noumena wants to watch videos. Since it's past her bedtime, I tell her we can only watch one minute before going to sleep and that I won’t be telling her a story—a position I can't maintain once the minute is up and I hear the disappointed inquiry: “No story?”

I inevitably break down and tell her our oft-told classic about us, a red bird—a cardinal in my mind—named Keke, a mouse named Roderick, and a malevolent Zombie that Keke and Roderick save us from with the help of benevolent earthworms after our failed flying lessons with Keke. Keke and Roderick end up knocking off the Zombie’s head so we can play soccer with it before heading home to bed in the story. Noumena recounts every detail, reciting the story alongside me as I tell it.

At the story’s conclusion, she rolls over, and I tickle-scratch her into restful slumber. Goodnight, sweet cherub. I will miss you in your sleep.
