#+TITLE: October  3, 2023
#+INCLUDE: ~/org/blog/noumena/header.org

* Morning

Despite having poorly slept the night before last, I was determined to get back on track last night. After finishing the household chores late last night, I prepared mine and Noumena's breakfast of our protein oatmeal and that's we ate this morning. Atypically, Noumena seemed rather discontent in her crib this morning forcing me out of bed earlier than I'd have liked. It was 8am and she was making quite a ruckus so I knew I had to pull myself from bed, so I did. This, however, gave us plenty of time to eat our breakfast easily. After we finish eating, I get Noumena dressed in her light purple outfit and we head to daycare. When I dropped her off, I joined her with the kids in the circle and after a very brief period, she was comfortable enough to leave her daddy's side to go mingle with the children. As much as I love clingy Noumena, I'm overcome with pride with independent Noumena.

* Picking Up Noumena

Noumena's mother wanted to visit her today, but she was ambivalent about whether we wanted to go somewhere or come over. I didn't want to go out to eat, so I told her we would pick her up. She rode with us home entertaining and reading to Noumena on the way.

When we arrived, Kisa was in the yard. While still in the car, I asked Noumena if she wanted to greet Kisa. Before she was even out of the car she began to turn her head clearly searching for Kisa. I got her out of her car seat and set her down on the ground to greet Kisa.

#+begin_export html
<div class="video-container">
<iframe width="1870" height="717" src="https://www.youtube.com/embed/bXNsByKTojk" title="Greeting Kisa When We Arrive Home" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export

* Dinner And Hanging Out At Home

Inside, I had remembered that I had put laundry in during the day, so I got it out of the dryer and started folding the laundry with Noumena periodically taking breaks from playing with Mommy to help out a.k.a. mess up all the clothes I had folded.

To allow me to finish folding, Mommy took Noumena into the bedroom to watch some TV while I continued, but after a short period of time, Noumena began to get cranky. She hadn't had dinner yet, so her mother surmised that she was hungry so she sat Noumena up in the high chair as I warmed her soup. Once the soup was warmed, I brought it to her to start feeding her straight away. As she started to eat, I made some bread and butter to go with it. When retrieving the butter from the fridge, I saw the smoked gouda cheese I'd bought and decided to give her a slice of that as well. She definitely enjoyed her dinner. I washed dishes as Noumena ate.

Mommy spent time with Noumena in the living room and bedroom while I finished cleaning up. After a short time, I prompted them to take a walk and Mommy agreed.

* Walking To The Tidewater Acres Park

Leaving the house, I set Noumena on the ground straight away to walk with us. We got all the way to Harley's house about half a block away before I picking her up on my shoulders to run back and forth with Harley along her electric fence. After, we proceeded to the park Noumena pointing out the black owl statue and cats along the way only stopping to visit another neighborhood dog whose name I don't know.

Once again, when we entered the park, I gave Noumena the choice to choose between the swings and the slide as her first course of action. As expected, she wanted to show Mommy her skills, so she of course opted for the slide, scaling the platforms with ease following Mommy to take her first trip down the slide. It had rained earlier, so I cleaned the bottom of the slide then rushed to the top to beat Noumena to it so that I could slide down using my clothes to dry off the remaining water. She slid down several times before the amount of mosquito bites Noumena's mother and I had to endure became overwhelming causing us to leave. Apparently Noumena had been a victim of a few bites from mosquitoes herself because on the way home she started to scratch her hand. I took special note of it because it was the first time I'd seen that behavior. As far as I can tell, it was the first itch Noumena intentionally scratched motivating me to tell her mother that I thought Noumena had acquired self awareness despite what any mirror test said and we enjoyed a small philosophical exploration as to whether that inference was warranted.

* Taking Mommy Home

As we walk through the doors I notice the empty fireplace mantle. since Noumena's mother had removed the television from the mantle to take it into the room, there was an empty space just begging for Noumena to be seated on it in order for me to remove her shoes. I removed them narrating as I did so and set Noumena down to join Mommy on the couch to read the books that Mommy had purchased for her. When 8pm rolled around, Noumena's mother asked when I would take her home. Befuddled, having totally forgotten that we picked her up, I exclaimed that we'd better go now since Noumena's bath time was at 8:30pm. I was confident that Noumena would fall asleep in the car, and on the way to drop Mommy off she did, but when Mommy got out of the car, she awoke and stayed awake almost all the way until we'd arrived.

* Bath And Bed Time

We still had 10 minutes before bath time upon arrival, so we sat on the floor so I could read to Noumena. I read through 100 pictures and moved on to the next book of 100 words, but by that time Noumena had grown weary of reading. Instead, she picked up the sleeve that the books came in and handed them to me. Placing it on my head intrigued Noumena and so she handed me one of the books. I placed that one on my head as well and this became our game. Soon all the books were stacked on my head along with the packets of stickers that they came with. It had reached 8:35pm, so I told Noumena it was bath time and she followed me into the bathtub to draw the bath.

Having used my distraction technique with the faucet, shampooing and scrubbing Noumena down was surprisingly quick leaving ample time to simply enjoy the tub. She has a small rubber hippo constituted the same way as your average rubber ducky, so I mimicked how a hippo really would behaving in the water to amuse her. Her foam letters were more interesting to her, however and so I would stick them to her body and she would stick them into her mouth for me to bite down on the other end while the tub drained. I removed her toy basket from the hooks and told her to put away her bath toys. She put away every last one herself!

After getting her dressed in her pajamas, brushing her teeth and feeding the pets, I thought for certain she'd fall asleep immediately. We listened to /Isn't She Lovely/ and she had fallen asleep in my arms, but when I set her down she began to cry. I thought her cries would subside shortly, but I was wrong and she was making a big scene when I left the room. I gave her a minute to herself, but when the cries didn't die down, I had to reenter to put her back to sleep. We finished the playlist---listening to /Stand By Me/ and /Just The Two Of Us/ before laying her back down. I'm not sure why she was sleeping so lightly, but even after 10 minutes of rocking, she was still discontented when I laid her back down. Fortunately, the cries were milder so I let her sob a bit and she was soon asleep.
