#+TITLE: October 12, 2023
#+INCLUDE: ~/org/blog/noumena/header.org

* Morning

I woke up late yet again, but thankfully I had prepared breakfast for us last night. Noumena surprisingly hadn't woken up when I woke up at 9am. She gave me plenty of time to get ready before going to her room to wake her up. When I took her out to the dining room to eat, she saw her elmo sippy-cup and pointed to it making mild whines and gesturing towards it. I let her drink the water that was in there before heading back to the kitchen to refill it. For some reason, Noumena was very thirsty this morning. We ate our oatmeal together and several times throughout the meal.

A few days ago it was rather cold. I hadn't checked how warm it was going to be outside, but since it wasn't too cool in the house, I took a slight risk and got Noumena dressed in shorts and a shirt. Thankfully, when we went to the car, it really wasn't that cold and I knew it would warm up throughout the day. I took her to daycare, dropped her off and headed home to get started with my work day.

* Picking Up Noumena From Daycare

Noumena's mother's car was in the shop so she asked me to help her pick it up after work. Since her mother is so close to Noumena's daycare, I went to pick her up before Noumena so Noumena could be surprised by her mother when picking her up. We went in and Noumena was absolutely ecstatic to see her mother picking her up. As usual she ran directly to her, but since she was so surprised and excited to see her mother, her arms shook violently as she rant to her mother only outstretching them when she got close. Her mother picked her up and then Noumena saw Daddy and reached her arms out to me and I carried her out to the car. We drove to pick Mommy's car up and head home.

* Spending Time With Mommy At Home

Mommy had reached home before us and was there to greet Noumena as she entered the door. I thought I could set her down and have her run to Mommy, but as usual, Noumena is very clingy so when I set her down she immediately wanted to be picked back up.

Mommy had purchased her an owl Halloween costume and was very excited to have Noumena try it on. Noumena was less than excited. It was big and came in a 4 parts: the body with arm holes, a hat with an owl face on it, and 2 talons slippers meant to wrap around her shoes. We only got the body suit portion on and only for a brief period and I was unfortunately unable to snap a picture. Noumena definitely wasn't digging it, so it was funny watching her ambivalence as was trying to accept what was going on, but also did not want to wear that costume.

After Noumena had taken it off, Mommy read Noumena her owl magazines and played with her while I prepared soup as an easy dinner for us. The lentil soup I made was rather thin and the vegetables weren't really conducive for easily picking up as finger food, so she sat on my lap for me to feed her. Noumena ate a fair amount but definitely less than I had anticipated. Eventually, she just started tossing the buttered bread to Chalmers, so I recognized she had had enough. I set her down to play with her sensory box while I finished up.

Mommy had a meeting to attend, so after having taken a brief rest, we walked with Mommy out to her car, Noumena kissing her several times along the way. She gives Mommy a final hug and kiss at her car and we head to the park.

* Tidewater Acres Park

Despite the fact that it had rained basically all day and the park was definitely wet, I decided that a little water never really hurt anyone and Noumena definitely can't stand to be inside, so we throw caution to the wind and head out to get wet. On our walk, I thought we would be met with disappointment because it seemed as though Harley wasn't out, but just as we were about to overtake Harley's lawn, she come rushing out to greet us. We run back and forth with her a couple times---Noumena as gleeful about it as ever---and continue on our way. Right across from Harley's yard in her neighbor's yard, I notice a gray rabbit with a white face. We stopped to investigate, but I don't think Noumena could see the rabbit so clearly. Since it was in other people's yard, I didn't feel comfortable setting her down to rush over there and investigate, so I just hunched over to observe for a few seconds before we move along to the park.

#+begin_export html
<div class="video-container">
<iframe width="1870" height="733" src="https://www.youtube.com/embed/WFT37KJ2InU" title="Playing In Water And Dragging Daddy Around At Park" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export


Kids always surprise you. My impression was that the wetness of the park would prompt any different interaction from Noumena than usual. I was wrong. For Noumena, the wetness was a unique and interesting feature. Instead of playing like normal, everything with water beads settled on it became a tactile focus. She would move and play with the beads of water instead of using the equipment. She wouldn't even go down the wet slides. Instead, she stood at the top and played with the beaded water. There was a lot of water collected on the slides, however, so perhaps she just didn't want to get wet. When she did attempt to go down a slide finally, I set her on my lap to go down getting wet so shouldn't wouldn't have to endure any of the discomfort of getting wet.

There wasn't much to do at the park---understandably so since there didn't seem to be any of the cats around and no one else wanted to be at the wet park so we were all alone. Shortly, Noumena ran for the gate and as I do typically when she does that, I picked her up, hoisted her on my shoulders and told her we were headed home. We took the long way home and for the most part she was content on my shoulders. There was a brief period where she wanted to get down, and when I wouldn't let her, she started having a little tantrum and hitting my head. I grabbed her arms and started petting my head telling her she needed to be nice to Daddy. She began petting herself and was content for the rest of the walk home.

* Home

Once we arrived home, I thought maybe Noumena hadn't eaten enough, so I tried to get her to eat more soup. She really must have been full because she wasn't interested in eating whatsoever. So we sat down, read some books together and she helped Daddy fold laundry. Well, Daddy folded laundry and she just put the clothes that I had dumped on the floor for folding back into the laundry basket. When she filled it up, she would have me dump them back out on the floor again. At one point, she would grab the clothes that I was folding out of my hands saying "mine". At some point I wouldn't let her do this, so she started throwing another small tantrum. It's funny, though, because she must have realized it wasn't all that big of a deal, because it was very short lived and she went right back to putting the clothes back into the basket.

#+begin_export html
<div class="video-container">
<iframe width="1870" height="733" src="https://www.youtube.com/embed/DvjDmioElk4" title="Being Kinda Mean To Kisa" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export

* Harvey's

I had run out of oats realized I didn't have anything to make Noumena for breakfast, so we decided to make a quick trip to the grocery story that's just down the road to get some. When we parked, I told her that if she held onto Daddy's hand in the parking lot, she could walk into the store with me otherwise I would have to carry her. She obliged and we went in following another father and daughter duo who were talking about the food they were going to get. It was pleasant for both Noumena and me. Once we got in and I started pushing the cart, Noumena wanted to be the one pushing the cart. It was hard to get on video, but I got a little bit of it.

#+begin_export html
<div class="video-container">
<iframe width="1870" height="733" src="https://www.youtube.com/embed/VNu3O8BrwOY" title="Pushing The Cart In The Store" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export

* Bath Time

It was just about approaching bath time when we got home. I've begun undressing her in my bedroom as I can throw her clothes into the laundry basket in my room reducing cleanup a little. Since she likes to put them in the laundry basket, I always let her do it. This results in a naked baby walking down the hall into the bathroom with me in the cutest display ever.

I always drape the towel over Noumena's head whenever I pull her from the tub. Tonight, I think I left the towel draped over her head a little to long as I held her in my arms to dry her off. She didn't like it but when I removed it, she seemed to discover her hair. She played with it all the way to her changing table and even while I was changing her continued to play with it. Even after I brushed her teeth, she was still playing with it. It must be so interesting to discover you have hair for the first time and I actually got it on video!

#+begin_export html
<div class="video-container">
<iframe width="435" height="774" src="https://www.youtube.com/embed/g6RkhQ81n5A" title="Noumena Discovers Her Hair" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export

* Bed Time

/Isn't She Lovely/ really is like a sleep trigger for Noumena. She didn't really seem tired when I was holding her in the dark before it started playing, but the moment it comes on, her head immediately collapses against my chest. I lay her down when /Stand By Me/ starts to play and I caress her through the song. She drifts to sleep without a single fuss.
