#+TITLE: Secular Liberalism and Moral Psychology of Identity
#+AUTHOR: Akeel Bilgrami
#+INCLUDE: ~/org/blog/philosophy/header.org

/The endeavors of the secullar liberal state to bring about reform of illiberalpractices through legal interventions fail sinice it nlmakes no appeal to the substantive conceptions of the good the community it aims to reform may cherish. Coinmunitarianismn takes this lack of reason-giving apparatus of the liberal state to justify its critique of the latter as essentia!ly coercive, and advocates intra-community reform via intra-community democracy. This article arglues agaiinst both these positions. It pleads that the state can be a site of initiating reform by addressing different communitarian perspectives from within their own internal substantive commitment ts and making the m aware of their internal inconsistencies so as to eventually engender a common secular outcome./

* I

IT is for some time now that the tension between state and community has had political theory in its grip. Theorising about the liberal state has been particularly constricted by this grip since any effort the theory has made toward the idea of the rights of communities, for instance in the form of minority rights, has necessarily had the consequence that it must concede to illiberalism towards individuals, if such illiberalism is indeed practiced by the community towards any of its individual members. This is a familiar paradox of liberalism and it is particularly familiar in India since it surfaces so much in our ongoing debates about Muslim personal laws.

Current and traditional political theory (constricted as it is by the tension between state and community) has the resources to offer two opposed general directions of resolution. One is toward the pole of a secular liberal state, which imposes legal interventions that amount to reform of such illiberal practices. The other is toward the pole of internal reform within the' communities against their own illiberal practices. There may be debate and controversy about specific paths followed in each direction. In the statist direction, we may worry about whether a community has the preparedness or not for the imposition by state of such reforms.[fn:1] we may worry about whether the right to exit is a realistic and powerful enough liberal tool[fn:2] we may worry about the relative roles of legislature and judiciary in bringing about reforms, and so on. In the internal communitarian direction we may worry about such things as whether or not reform should take place via representative institutions within communities or whether instead they should be allowed to emerge less formally by mobilization on the sites of intracommunitarian civil society. But these are details, some of which may only be relevant contingently in specific contexts. My concern in the first half of the article is with the larger theoretical picture, and the point I want to begin with is just the observation I have made above, that the conceptual frameworks of liberal political theory hitherto have only one of these two directions of resolution to offer, a sort of Homeric liberal choice, a constricting disjunction. I believe the disjunction is as intolerable as it is un-compulsory. To try to put it right is the central preoccupation of this article.

Just in case there is unclarity on this point, what I am trying to put right, and in general the entire issue I am addressing in addressing this disjunction, must not be run together with a quite different issue of whether it is a good thing, or even a consistent thing, for liberal doctrine to countenance group or collective rights. On that issue, this article takes no position, even though its author happens to have roughly worked out opinions on it. So, the reader should not be misled by the fact that the concrete setting of some of my discussion in the paper mentions minority rights and the question of Muslim personal law in India, to think that the issue under philosophical discussion is one about the worthiness (or not) of group or community rights in general. The issue rather is this. Given the fact of group or community rights (i e, minority rights), and in particular given the particular consequence of this in the case of Muslims in India where the fact of such rights has resulted in legal terms to granting Muslims their own unreformed personal laws, which as we know are in many respects illiberal in their treatment of Muslim women, the question is: Is the specific disjunction I have just mentioned of the either/or of statist reform versus internal communitarian reform, a well formulated pair of theoretical options for liberalism?

* II

To address this issue in liberal political theory and eventually to repudiate this disjunctive formula, I will first dwell at some distance from liberal political theory in the more abstract ground of moral psychology in order to use some of its concepts and conclusions to construct an argument and an alternative framework for theorizing about the secular state.

By moral psychology. I mean the psychology of agents by which their choices and actions are explained, and in particular explained normatively in the sense that the explanation does not merely say why they chose or did what they did, but also sees it as essential to explanation to assess whether what they did was rational by the lights of their own desires and values. And I do not just mean that one explains why they did what they did in some non-normative way first, and then makes the normative assessment whether what they did is in accord with their desires and values. Rather such an assessment is built-in to the very idea of explaining why they did what they did by citing their desires and values. Thus this normative element in the study of human individual and social behaviour is not some extra thing tacked on to an otherwise purely descriptive enterprise. No social science despite the pretensions of its second term ("science") can leave out this normative aspect of explanation without changing its own subject beyond recognition.

To begin with, a bit of terminology. For the convenience of abbreviation, I will use a single term desires to cover all those motivating states of agents which economists and other social scientists, decision theorists, and philosophers (not to mention, literary people) variously refer to as values, commitments, preferences, subjective utilities, interests, inclinations, motives, etc. The term will therefore cover all such states of mind, from the desire to drink tea to the desire to work for social justice. So despite its restricted popular meaning, my use of the term "desires" is intended to be as wide as to cover all these states of mind, and should not therefore give the impression that my interest in rationality is a narrow interest in a hedonic calculus. "Desires" in this use of the term, when coupled with our beliefs and other cognitive states, make sense in this normative way of why we do anything that we intentionally do.

I should also add by way of preliminary caveat that my insistence on the relevance of moral psychology begs no questions either in favor of methodological individualism in the social sciences or in favor of a voluntarism in the study of historical events. Perhaps I should put the point in the converse. Any methodological holist position or any position that stresses structural and determinist explanations of historical phenomena can leave out the moral psychology of their subjects only at the cost of becoming desperately implausible, to the extent that they are not entirely hazy.[fn:3]

Let me now introduce three ideas I will need in the construction of the argument. The first I will call reinforcement among our desires. A way to characterise this is to explore the idea of a relation among our desires that is stronger than mere consistency among them. Consistency among desires merely requires that they are mutually implementable. But two desires may be consistent with one another in this sense and have nothing to do with one another in a psychological economy. My desire for tea happens to have nothing to do with my desire to do philosophy, and they are both mutually implementable. On the other hand my desire to do philosophy and my desire to be respected by my peers are related by more than mere consistency, they are more than merely mutually implementable, they, as I said, reinforce one another.

However, though reinforcement is in this way more than mere inconsistency, it ought not to be confused with another relation between desires, which is the means/end or instrumental relation. Reinforcement is not a means/end relation because if I were asked whether I pursue my desire to do philosophy in order to fulfill my desire to be respected by my peers my answer might well be "no".

So reinforcement is a relation between desires mat is stronger than consistency without collapsing into instrumentality. This is a point of some importance, since it has not been obvious to many who study the rationality of our wants and values and actions that there is a relation between desires other than consistency or means/end. It is hard to say much more about it as a relation because it is an irreducible relation. The best we can do is to give examples to make it intuitive, as we already have. So if someone is sceptical about there being such a relation as reinforcement between our desires over and above consistency among them, we can pose the following challenge to her: Tell us how you will mark the intuitive difference in the relation between the following two pairs of desires without bringing in the relation of reinforcement between desires: ( 1) My desire to do philosophy and my desire to drink tea, and (2) My desire to do philosophy and my desire to be respected by my intellectual friends. There clearly is an intuitive difference between the two pairs, and there does not seem to be any way to say what makes the relations in these pairs of desires different, except by saying that the first pair of desires are merely consistent but do not (in the "normal" case) reinforce one another, whereas in the second pair the desires do also reinforce one another.[fn:4] At this point, there will be a natural temptation to deny this and say: "Well yes, there is something more than consistency involved in the second pair but that can be captured by saying that while the first pair is merely consistent, the second pair in addition has a means/end relation between the two desires." This temptation should be resisted because, as I said above, someone holding the second pair of desires may very well answer "No" to the question: Do you desire to do philosophy in order to be respected by your intellectual friends? If so, for that agent, means/end will not capture the intuitive difference in the relation between the desires in the second pair. Only reinforcement will.

I am spending some time on this point because it is an important one to make against those who think that any serious and intrinsic conception of rationality is not applicable to such things as desires and values, but is restricted only to beliefs. Despite their well known antagonism, both Humean and Kantian traditions of thinking about human behaviour and moral psychology (for very different reasons) share such a sceptical attitude about allowing desires to be the subject of a rich notion of rationality. And since so much of current thinking about this subject sees itself as broadly influenced by one or other of these traditions, this sceptical attitude is very widespread. According to this widespread picture, desires may be subject to an instrumental rationality but they do not possess any intrinsic rationality except for the very thin notion of consistency among desires (which, as I said earlier, amounts only to their mutual implementability.) The notion of reinforcement, by contrast, brings with it a thicker conception of rationality and allows us to think of desires (and not just beliefs) in terms of a coherentist conception of rationality, where coherence is something stronger than consistency. That is why the idea of reinforcement allows us to get beyond the narrowing Kantian idea that our moral rationality cannot traffic in anything so contingent and non-universal as desires, at the same time as it surpasses the equally narrowing Humean idea that the only rationality that motivating states (what he called the "passions") are subject to, is instrumental.

One final word in the exposition of this crucial idea. Obviously, reinforcement has its other side. That is, just as desires can stand in relations of reinforcement to one another, they can also stand in the opposite relation of informing one another. Such I suspect is the relation between my desire to do good philosophy and my desire for an active social life. With this simple and irreducible relational idea of reinforcement (and infirmity) among desires in place, we can stipulate a definition of values as well as of rationality. A person's values are a subset, a special case of, her desires. An agent's values are those among her desires that are most highly reinforced rather than those which are infirm. And an agent is the more rational the more her actions are in accord with her values. This is all pretty hasty and crude, of course, and needs many layers of elaboration, qualification and refinement, but I should be forgiven for not doing so here, since I am merely setting up a very rudimentary apparatus for use at some distance from here. [As an aside, I repeat here but will not keep doing so that though all my examples have been of individual moral psychology, I see no reason to deny, in fact I do not see how we can fail to assert, that groups and collectivities can have a psychological economy. Thus, for instance, we may talk of the desire of the vanguard of the French revolution to consolidate private property and contrast it with the vanguard of the Russian revolution which had the desire to abolish it. Any idea that one could come to any historical understanding or explanation of these two revolutions and their differences by leaving out states of mind of this kind, borders on the incoherent.][fn:5]

After 'reinforcement', I turn to my second key idea, which I will simply steal from Aristotle. He called it "akrasia", the medievals called it "inontinence", and we may, following more recent terminology, call it weakness of will. Informally it is described as: thinking the better but doing the worse. But we may now give a somewhat more formal description of it using the idea of reinforcement as defined above. Weakness of will is that form of irrationality where the most reinforced among our desires point to one sort of action, but what we actually opt for is something less reinforced in our evaluative economy.[fn:6] Weakness of will is the practical or moral counterpart of the cognitive phenomenon that Kuhn described as the frequent irrationality of the "normal" scientist, which might properly be described as weakness of warrant, or believing what has less than maximal reinforcement among our scientific beliefs.

The third and last moral psychological notion that I will use is that of identity. Following some of the basic arguments of an earlier paper of mine ('What Is a Muslim: Fundamental Commitment and Cultural Identity?', EPW, May 16-23, 1992), the notion of identity can be characterised in terms of what I there called an agent's most "fundamental commitments". These are desires that she most identifies with. How are these to be characterised? It is not enough to repeat that these are the desires that are highly reinforced because those will be too many to deliver anything so focused notion of identity. To the extent that we believe in the notion of identity, we will have to do better and specify desires that have an even greater centrality in our psychological economy. These are specified in counterfactual terms. A desire is a fundamental commitment if one wants it fulfilled even were one not to have the desire. In case this sounds too abstract, it can be indexed to times. A desire is a fundamental commitment at a given time, if at that time one wants it fulfilled at a future time, even if one believes that at the future time one may not have that desire. This temporal elaboration of the counterfactual will be crucial to my argument against the classical liberal picture. For now an intuitive sense of such a commitment can be given by an example. Many of our desires are not fundamental commitments in this sense, but a few indeed are. Take for example, the fact that certain sections of the Iranian government are explicitly arguing that increasingly modernizing influences around them may well have the effect in the future that they will lose their desire to live by Islamic tenets, nevertheless they now want their future to be one where they are in fact living by Islamic tenets, even if they do not have the desire to do so then. (And they are in fact arguing that they should entrench things so that that can happen.)

Commitments which have this looped counterfactual form, stand out even among our most reinforced desires, and have a right to be seen as rigorously reflecting our identity shaping commitments for they reveal our deepest self-conception in a way that vague existentialist rhetoric about authenticity fails to do. And formulating the idea of identity along these lines has the distinct advantage that it does not amount to thinking of identities in any essentialist or immutable way. These are not primordial or permanent identities since what defines them are desires which are not themselves permanent or even necessarily extraordinarily abiding, but rather desires which are for something that is more permanent than the desire itself may be. Commitments so defined are therefore quite susceptible to change as well as to conflict with one another. What makes them distinctive, and deep or 'fundamental', is not their immunity from these things but rather it is captured entirely by what is revealed in their counterfactual form. (And I hope nobody is confused by my term 'fundamental' to describe these commitments to think that they have anything to do with 'fundamentalism'.) With these three moral psychological notions in place, I return now to liberal political theory.

* III

Liberalism's most honored slogan says this: Individuals must be left unimpeded to pursue their own conceptions of the good life". Properly qualified and refined this stands as the most general defining mark of liberal doctrine, subsuming specific instances of it that specifically mention one or other domain of application, such as that of speech and thought, of religion and worship, of ownership of property, and so on.

The slogan divides into two and each half mentions a key notion, that of noninterference ("unimpeded") and that of conceptions of the good life. The idea of "conceptions of the good life" is left almost entirely open since it is just the idea of the values and aspirations of agents, which may be various and variously specific. These are none other than a subset of what we have, in our use of the term, called "desires". They could include any substantive set of desires, from a religious way of life to a life playing, or even watching, cricket. The idea of noninterference, of course is also the idea of a value or good. But as such it is also intended in a critical way to stand in contrast with substantive goods and values, whose pursuit it asks to be left unimpeded. What is the intended contrast in liberalism between the value of non-interference in the pursuit of substantive values and the substantive values themselves? There are various familiar answers to this question, ranging from the universality, and the relative non-negotiability of the former in comparison to the substantive values, to the fact that it is procedural rather than substantive since it generates entitlements in a way that one does not routinely expect of the substantive values. That is to say, within certain qualifications which I mentioned when I introduced the slogan, the idea of non-interference is one which provides a constraint on certain forms of behaviour (those that amount to interference) and in doing so it entitles others to pursue other forms of behaviour freely (those which promote their substantive conceptions of the good.) These latter, the substantive values, on the other hand do not themselves have this procedural property of providing constraints and therefore generating entitlements. In any case, whichever of these answers we stress, the crucial liberal assumption is that non.interference as a good cannot be a good which is weighed on the same scale as the substantive goods whose pursuit it makes freely possible by placing various constraints. This much is essential to any version or variant of the doctrine of liberalism. The idiom of "rights" is the natural idiom in which to describe the idea of such a special good or value, and the idiom is frequently on our lips.

Let me then make a disclosure of personal opinion. Putting aside the domain of private property and of economic behaviour generally as a serious arid systematic exception, the idiom of rights and the procedural constraints it imposes on states (and other institutions as well as on individuals) seem to me entirely salutary.[fn:7] And the idea that the value it expresses is not to be weighed on the same scale as substantive goods is necessarily true because it is innocuous. After all it just spells out the claim that these are procedural constraints which those substantive goods are not.

But all these unimpeachable claims are susceptible to an ambiguous reading. And the ambiguity, when properly stated, separates out the standard and classical liberal tradition from other sorts of position that might also aspire to liberal ideals outside that tradition. The rest of this paper will try to give a rigorous basis for this separation and then apply it to a concrete political issue and historical context.

What defines the specifically classical liberal understanding of the idea of noninterference is not just that it is a right or constraint but that what justifies our taking it to be a right or constraint cannot be derived from any of those substantive conceptions themselves since that would ultimately make the value expressed in the constraint (non-interference) as contestable as the substantive values they are derived from.

Now if we wished to deny this defining point of the classical principles of the liberal state, we would necessarily have generated a quite different reading of the idea of rights one that has not sufficiently been theorized because criticism of liberal doctrine has predominantly been motivated by a communitarian trajectory that sees the classical tradition of thought on the liberal state as lacking the resources to cope with the claims of community and then,just as surely as that tradition which it is criticizing, this criticism of it sees no scope either for another reading of the idea of rights. It is that crucial space, buried by the classical liberal tradition and which remains undiscovered by its communitarian critics, that I want to try and unearth. My diagnostic claim will be that both parties to the dispute are blind to it because they both work with an impoverished conception of the moral psychology involved in the subject of their disagreement.

So. in effect, I have made a second disclosure of personal opinion. I do not feel the sentimental glow for the notion of community and of tradition felt by the critics of liberalism, and I think the focus should rather be on the shortcomings of classical liberalism's understanding of the moral psychology relevant to their own cherished themes.

The traditional liberal claim that the idiom of rights expresses claims which cannot be made contestable by deriving their justification from any of the substantive values whose pursuit they make freely possible, has a venerable history but it was most explicitly stated and elaborated for the first time in Mill's careless masterpiece on the subject,[fn:8] and in more recent times it has had its most sophisticated flowering in a contractualist version of Mill's argument in the writings of John Rawls.[fn:9] I will focus on Rawls.

His argument tor the claim is to be found in the celebrated method by which he settles on the basic liberties of liberal theory. Since the method is so well known and well-studied, I will be brief in the exposition. These liberties are part of the content of a principle (the first of his two "principles of justice") that Rawls says we would choose in any social contract in which we did not have the information which would lead us to choose principles that are biased in our own favor. In particular, we would contract into this principle of noninterference adumbrating these various liberties when we lacked knowledge of our own substantive conceptions of the good, as well as lacked knowledge of other things which might give us clues about what substantive values are (e g. our status in society, our family and other sorts of background, our professions, etc). If the principle of non-interference is chosen under these circumstances and is rationally chosen, then clearly (that is to say, by definition) its justification will make no appeal to substantive conceptions of the good. And, for Rawls, the fact that we have rationally made the choice under these circumstances would be part of the justification for adopting these liberties (and the policies and institutions that administer them) in the actual societies in which we live.

Rawls therefore is fully aware that moral psychology is of central importance to the argument. He cannot fail to be since, as I just said, the question he sets himself is what would it be rational for someone to chose as principles to be governed by if he lacked information of his own substantive values and commitments. So, if while considering the matter of whether to choose a particular principle one contemplated circumstances in the future in which one thought that one would not be rationally motivated to adopt it, and one nevertheless chose the principle, it follows that one has with rational justification judged those circumstances irrelevant. To repeat, the idea is that the most general principles to be governed by in actual societies would be just and unbiased if they were principles which would be chosen in such a state of ignorance about our substantive conceptions of the good (and about our social circumstances). And when these choices are rational, it is because behind this "veil of ignorance", we have chosen them no matter what we contemplate ourselves as being when the veil is lifted, i e, no matter what substantive conception of the good we contemplate ourselves as having."[fn:10]

Let's then turn to the question of what it would or would not be rational for us to commit ourselves to in these circumstances. Here, we may introduce, as an example, the second of our disjuncts, "community", and since it is so much on our minds in current debates let the example be one of community defined by politico-religious commitments. (Rawls himself has often been exercised by such examples.) Suppose then while we are considering which principles to chose in this state of ignorance, we contemplate that we will find when the veil of ignorance is lifted that we have a highly religious conception of the good, with detailed substantive commitments to a polity ruled by a set of religious laws (say, the sharia), to exercise censorship against serious religious dissent (e g, against a blasphemous book), and that most others in the society and nation share these views (here I run out of an actual example since I do not believe that that is true even of Iran). Could one while contemplating the possibility find motives to commit ourselves to a principle of non-interference such as the one we have been discussing'?

Rawls obviously must think one can, since his first principle of justice precisely speaks to these standard liberties carried by the ideal of non-interference, and Rawls believes that we would rationally contract into it behind the veil of ignorance. But at first sight, it is hard to see why, if one contemplated oneself to be the kind of religious communitarian just sketched, one would choose, for example, the particular form of non-interference and liberty enshrined in the right to free expression. At any rate that has been the general communitarian dissatisfaction with Rawls. Rawls, it is said, cannot deal with the commitments to religious and other communities, and it is said that his theory is narrowly addressed only to a certain sort of detached, modernist contractor who is anyway inclined to liberalism. If that were not so, why should someone chose such a principle of liberty of expression, if he contemplated that when the veil is lifted he might be someone with the substantive values of a religious doctrine which demands the censorship of blasphemy? It may well be irrational for him to choose it, and if so, then liberalism will not have an argument for one of its central principles.

But Rawls has an answer. The question, as I said, is really a question in moral psychology. And Rawls in more recent writing subsequent to /The Theory of Justice/[fn:11] has fortified his case with a further argument that explicitly appeals to a moral-psychological consideration to show that even if one contemplated that when the veil was lifted, it would be revealed to one that one had these substantive religious values, it would /still/ be rational to chose the principle of liberty of expression. The consideration he appeals to is a psychological counterpart to his starting point of ignorance of one's own substantive commitments, a psychological counterpart which Rawls indexes to the future. He says that even such a religious communitarian will have the elementary psychological knowledge that, like anyone else, he is capable or susceptible to changes of mind and viewpoint, and therefore changes in his desires, in his substantive conceptions of the good. So, if behind the veil of ignorance one is contemplating that when it is lifted one might find that one is such a religious communitarian, one will also contemplate that in the future one might change one's mind and cease to be one. Now if one contemplates this too, then one will want  make sure that one will have the chance to fulfill any future desires that one has adopted which are not that of the religious communitarian. But one may well not have the chance to fulfill them if one contracts and binds oneself to principles approved only by the religious communitarian one presently contemplates oneself to be. In fact to ensure that one protects the fulfilability of one's future, possibly changed, desires, one better contract into the liberty of expression and other basic liberties since those desires may not be fulfilled in a society which suppressed dissent and other non-religious points of view.

As I said this argument from the changeability of our desires just puts into. the psychological considerations available to agents choosing these principles, a version of ignorance (this time about possible future commitments of theirs), and asks them to take out an insurance policy for possibly very different commitments in the future, just as in the initial contractualist thought experiment in A Theory of Justice, he asked them to take out an insurance policy for what our present conception of the good might turn out to be when the veil is lifted and we are informed about ourselves. So to repeat: the idea is that if someone behind the veil of ignorance, contemplating himself to be a religious communitarian, also contemplates the fact that he might have in the future conceptions of the good which are not the ones he presently has, ones which in fact might be quite radically different from the ones he presently has, he will want to insure that in the future he will not be badly off, which he will be if he repudiates the principle of liberal rights of non-interference on the basis of his contemplated present religious communitarian commitments alone.

Such a proposal presupposes that the psychological economy of agents have in them a belief that they might at some future point have a quite different set of substantive commitments than they now are contemplating themselves to have. and a desire that these revised commitments be successfully fulfilled. Rawls regards this as a sort of higher order desire for the successful fulfillment of our revised or changed desires. Armed with this higher order desire, even somebody contemplating that he is a religious communitarian of the sort mentioned above, would rationally choose the principle of liberty as non-interference, and commit himself to it and see no rational justification for undermining the commitment when it was revealed to him that he had a religious conception of the good. The moral psychology that Rawls proposes has that in his psychological economy, the lower order desires of the contemplated religious communitarian will conflict with his higher order desire for revisability of desires and their successful fulfillment, a desire which he shares with all other agents, if he is rational, and in the contest the higher order desire will win out.

That is Rawls' final word on behalf of classical liberal principles and some of you will recognize how it is a sophisticated contractualist analogue to Mill's famous meta-induction from fallibility to argue for the same conclusion.[fn:12] How shall we assess Rawls' argument?

It is here that the earlier excursus in moral psychology impresses with its relevance. Recall that I had introduced and defined three notions, that of reinforcement among our desires, that of weakness of will as a specific form of irrationality, and that of identity as shaped by certain kinds of very specifically defined fundamental commitment.

Let's begin with the direct and sharp relevance of the last of these. Identity was defined as being constituted by fundamental commitments which took a certain looped counterfactual form, indexed to times. It required of an agent that she make a rather specific sort of sacrifice for those of her desires which are at present her fundamental commitments. This is because she is prepared at the present to, in the future, live not according to the conceptions of the good that she has in the future, but rather to live then according to the conception of the good she now has instead. If that is the moral psychology of identity, then the very notion of identity is something that undermines Rawls' fortified argument for his principle stating the liberal rights.

Let me explain by first recalling our dialectic so far. I remind you that the difficulty for Rawls for which he must invoke the higher order desire about revisability, was one where it did not seem rational that we should behind the veil of ignorance commit ourselves to his liberal principle, if we contemplated that when it was lifted and we were informed about our own substantive conceptions of the good, we would find that we had the conception of the religious communitarian. The appeal to a higher order desire regarding the satisfaction of our revised desires, in the fortified argument, was supposed to make it rational after all to commit ourselves to the principle because that way we would be taking out an insurance policy for possible future conceptions of the good which were significantly different from our religious communitarian one. But now, suppose that the contemplated religious communitarian has what I have defined as fundamental commitments to his substantive religious values in the sense I sketched earlier, i e. the commitments to those values have the looped counterfactual form indexed to the future. In that case it may not be rational for him to adopt Rawls' principle of liberal rights, despite the considerations of revisability of desires. This is because his fundamental commitments are structurally defined in a way that preclude making any sacrifices now (sacrifices that would ensue from adopting the liberal rights, e g, the tolerating of blasphemous publications, etc) for a different psychological make-up in the future, and on the contrary demand he make the opposite sacrifice in the future (eg, accepting the possible non-satisfaction of different future conceptions of the good) for his deepest identity-forming commitments of the present.

The situation is simply this. Rawls has given an argument for a liberal principle that requires us to possibly make sacrifices in the present for the fulfillment of our desires in the future, but the most rigorous description we have of the moral psychology of identity asks us to make sacrifices in the future for the fulfillment of our present fundamental commitments that shape our identities. It would appear that things are at a stand-off.

At this point, let me invoke the other two of the three moral psychological notions I had introduced. The first of these is the idea of reinforcement among our desires. Suppose now that our religious communitarian being contemplated has not only a fundamental commitment in the sense defined but also that that commitment is highly reinforced, in the sense defined, by the other substantive desires in his value economy. Supposing this immediately resolves the stand off and puts Rawls' position in an unrecoverable disadvantage. Why? Because Rawls cannot make any similar appeal to reinforcement from substantive conceptions of the good for his higher-order desire for the satisfaction of future desires since that higher-order desire is introduced by him only behind the veil of ignorance where, /ex hypothesi/, there are no substantive conceptions of the good. That is the whole point of his strategy. For it is this strategy which places him in the center of the classical liberal tradition, a strategy formulated in order to give philosophical support via a sophisticated contract theory, to that classically defining interpretation of the liberal constraints, i e, an interpretation that sees them as not being justified by appeal to substantive values. This is the position I am seeking to oppose by making the notion of constraint ambiguous, by inviting us to conceive a liberalism where the constraint provided by its principles remains a constraint, but nevertheless is also justified by appeal to our own substantive values as they reinforce one another in an internally coherentist framework of moral and political rationality.

That brings me finally to the third moral psychological notion, that of weakness of will, to complete my description of the point of my argument against Rawls and this version of liberalism. The point can be put straightforwardly. If the contemplated religious communitarian in Rawls' thought experiment opts for the liberty of expression behind the veil of ignorance, then his moral psychology can be demonstrated to exhibit a specific kind of irrationality, that of weakness of will. For he would be opting for an outcome which is not only in conflict with his fundamental commitments (which in itself is not decisive since it gives rise only a stand-off) but also choosing something that is much less reinforced by his other desires. To do this last is to be no different, say, from the weak-willed alcoholic who desires to sober up and fulfill all his other desires (say to be a good husband and father, a good professional, etc) that are better reinforced than his desire for alcohol, but nevertheless opts for his relatively unreinforced desire for alcohol. To sum up in a facetious word, a proper understanding of moral psychology can only deliver the verdict that sometimes (in the face of strong communal identities) the grand liberal tradition may have to secure its liberal principles by asking us to be addicted to liberalism.

That brings to a close the argument against the classical liberal reading of the ideal of non-interference and of liberal rights and constraints generally. The strategy of my argument has been to show how there can be no justification of the notion of liberal rights that can be guaranteed to meet two conditions at once: (1) that it makes no appeal to an agent's or community's substantial values, and (2) that it sees the agent or community as rational, in the specific sense of not being weak-willed. In short, there is no guarantee that an adoption of secular liberalism by a society will be rational if it is not justified by appeal to some substantive values of the members of the society. And since presumably one would want liberal principles to be a rational adoption, we had better give a quite different reading to these ideals and rights than the is found in the classical liberal tradition.

There is a point worth noting. My argument against classical liberalism, as represented by a tradition from Mill to Rawls, is entirely independent of the truth of communitarianism. It is based entirely on considerations of moral psychology as I defined them and elaborated them in Section II. I have, of course, chosen the example of (religious) communitarianism to make my moral-psychological case. But that is merely an example and a quite different example could have been chosen, I chose this one because my eventual interest (in the next section) is a specific historical and political context of secularism and communalism in India. But an), example that involved the moral-psychological considerations of identity in the sense I have defined it, with reinforcement from other desires in the sense that I have defined it, and giving rise to the threat of weakness of will in the sense I have defined it, could have equally made the point again Rawls. Identity (to take just one of the three moral-psychological notions) is a perfectly general notion involving fundamental commitments as I have defined them structurally and generally in counterfactual terms. It by no means necessarily involves communitarian fundamental commitments in particular.

There is another related point. Even if one chooses an example of communitarian identity as I have in making my argument against the classical tradition, there is a distinction to be made of some significance which is often neglected in discussions of liberalism and its opponents, and it is a distinction which I crucially intend to apply it to a particular political context later on. This is the distinction between a normative angle on communities as opposed to a descriptive acknowledgement of them. Communitarians have a normative angle of regard for communities. They think that it is only within communities and a tradition that individuals form their identities and genuinely flower. So they value communities and decry the modernist tendency of individual detachment from community caused by the more abstractly configured post-enlightenment constructions of the nation and the state and its various liberal principles and agencies. A quite different angle on communities is the descriptive one, an angle that can be taken even by an anti-communitarian. This is where one only acknowledges the fact that many sections of a given population may have fundamental communitarian commitments, without oneself thinking this to be a good thing at all. In fact one can make such a descriptive acknowledgement and take the contrary normative stance of thinking community to be a crippling curb on individual assertion and self-respect. The point for now is that even if one took this last stance one could embrace my argument against Rawls. All that my argument requires is the descriptive acknowledgement that there are groups who have a certain moral psychology involving certain kinds of communitarian commitments. In short, an anti-communitarian could use a communitarian example to criticise the classical liberal tradition, as I have done. In fact, as 1 will argue in the next section, it may be well for an anti-communitarian to chose such an example because she will be in a better position then to fashion an eventually more stable secular liberalism, if she took into account the descriptive fact of communities and communitarian commitments.

I am laboring to stress this distinction between the normative and descriptive attitude towards communities partly so as to prevent the co-opting of my argument against the classical liberal tradition into the currently fashionable anti-liberal communitarian critique of the modernist legacy of the enlightenment,[fn:13] a critique which repudiates the very idea of rights and of citizenship as being destructive of tradition and community. My argument does not show nor is it intended to show that there is anything wrong with the notion of rights. What it does show, if it is effective, is that there is no justification of liberal rights in the way that a familiar tradition from Mill to Rawls has tried to argue for it, i e, without any appeal to the citizens' substantive values and conceptions of the good

A reader may think that it is odd that in my view the standard and most sophisticated philosophical arguments for liberal rights may be found deeply wanting, and yet the notion of rights itself is not found wanting. He may think that if rights are dependent on ordinary and highly contestable substantive values for their justification, they must lose their special status as procedural constraints standing separately from substantive values. These thoughts are confused because they run together modes of justification for a conclusion with the conclusion itself. If one kept these two quite different things apart, there is nothing odd whatever in the claims of my argument. It is true that rights now become more contestable since justifying them will mean taking on arguments dependent on substantive values for premises, values that are in contest with other substantive values. But it is a non-sequitur to conclude from this outcome that rights themselves are undermined. Rights, on my view, remain rights. That is, we may still feel that there is need for basic constraints of a certain kind on all citizens, and therefore we may still think of certain values of ours (such as noninterference in certain domains) as standing apart from other values in being procedural rather than substantive, as generating entitlements in the way that substantive values do not. All that would be affected by my argument is that rights so conceived (both by the classical liberal and by me) are the conclusions of justifications of a very different sort. That is what I meant, when I said toward the beginning of this section, that the unimpeachable claims of liberal doctrine can be ambiguously read. Once disambiguated, the situation is simply this. My argument shows that any justification of rights must appeal to the very substantive values with which rights themselves are quite properly contrasted. Whereas the classical liberal position aspires (unsuccessfully if my critique is effective) to justify adopting rights in exactly the same sense (constraints generating entitlements, etc) without appeal to substantive values and instead via a purely philosophical argument of the sort I have sketched and criticised in detail in this section.

Let me end this section by generalizing into a methodological lesson, my critique of the classical mode of justification of liberal conclusions. To do so, I will introduce two terms, "internal reasons" and "external reasons", familiar to moral philosophers. The critique, to the extent that it has been effective, is a specific case of a perfectly general methodological point. If we have properly understood the point of the particular argument I made against Rawls, a much more general way of putting the point would be to say that all reasoning about moral and political value is internal reasoning, i e, internal to the substantive commitments of those with whom one is reasoning. We cannot get outside of the agents we are reasoning with to give them reasons. Rawls' appeal to a higher-order desire for the satisfaction of our revised desires in his contractualist thought-experiment, Mill' s appeal to a meta-induction regarding fallibility, and other such arguments in the classical liberal tradition are all efforts to give arguments for noninterference that are based on universal considerations which are intended to be quite independent of and external to the specific and substantive values that agents might possess. And that is why their mode of justifying their otherwise impeccable liberal conclusion fails. There is no such archimedean point in reasoning, (whether Rawls' or Mills' or any other). In a  word, there are no external reasons.

The general methodological idea that there are no external reasons, that there are only internal reasons appealing to substantive values of agents, has liberating possibilities for political theory, and I have tried in other recent work to use this idea to refashion two notions in the Marxist tradition, which have been unjustly discarded altogether in recent political theory because it was (to some extent rightly) thought that they are too closely tied to external reasons -these are the notion of "false consciousness" and the notion of what Isaiah Berlin anxiously described as "Positive Liberty".[fn:14] But here I want just to see through its consequences for an issue I raised at the very beginning of this paper, the issue of the seemingly unavoidable disjunction of statist reform versus internal reform, where the adopting of the one can only be understood as being at the cost of the other losing ground. A proper understanding of the notion of internal reasoning should instruct us how to dismount this seesaw.

* IV

In my earlier paper "What is a Muslim",[fn:15] which I cited above, I had looked to the structure of the moral psychology relevant to the reform of Islam, most particularly the reform of Islamic personal law. In that paper I had without argument made an explicit assumption that there were no reasons but internal reasons, and I had said that rather than plonk down basic liberal truths of the classical liberal tradition established on externalist and purely philosophical grounds, one should provide internal arguments appealing to the substantive values of historically situated Muslim populations to convince them to conclude in favor of internal reform. In a subsequent paper on secularism, called 'Two Concepts of Secularism: Reason, Modernity and the Archimedean Ideal',[fn:16] I had again, without argument, made the same anti-archimedean (anti-externalist) assumption, and sought to sketch a conception of secular liberalism compatible with the assumption. In the present paper so far, I have tried to actually present an argument for this assumption that I have constantly been making without argument. That was the argument I just gave against the classical liberal's (e g Rawls') archimedean efforts at justifying liberal rights.

This overall, accumulated. position,[fn:17] however, expressed as it is in the rhetoric of internal vs external reasons is poised for being subject to a spectacular misinterpretation. (I am being a little coy when I say "poised" since I in fact spent three months recently trying to correct this misinterpretation among some of my closest friends in Delhi.)

Let me explain by briefly considering a certain Foucauldian position which is adapted by Partha Chatterji in his recent paper on secularism.[fn:18]

Chatterji argues that in a multi-communal society like India, which has granted minority rights to minority religious communities in its constitution, secular liberalism is powerless to cope with the need for personal law reform. But he'thinks this.need not be devastating for those who find the personal law of one or other community unacceptably illiberal. And he boldly proposes that the answer to this impasse is that we should extend the notion of democracy and its representative institutions to intracommunity sites, opening up thereby the possibility of internal reform of personal law. Now, a careless and skipping reader of my paper, seeing the word "internal" in my use of the notion of "internal reasons", and seeing it again in Chatterji's account of "internal reform", may conclude that we have convergent views, even though I have made no commitment to or even mention of intracommunity democratic institutions, and insisted throughout on the necessity for statist reform. My point here is not just to say that this is a dumbfounding conflation, but to explore quickly how Chatterji's Foucauldian position and mine differ, for the difference is essential to this paper's promised task of superseding a certain disjunction.

Chatterji is driven to his conclusion about intracommunity democracy in India as a result of a crucial use he makes of an idea in Foucault's the idea of governmentality.[fn:19] The critique of sovereignty inherent in Foucault's idea is put to use by Chatterji to rule out the possibility that there can be any statist reform which is reason-giving and non-coercive. (Even if we disagree with Chatterji on a number of things, we may grant to him the general connection between reason-giving and non-coerciveness. In other words, one may take for granted for the moment that any statist imposition which is not at least implicitly reason-giving will be coercive, just as if I impose something on you without giving any reason, i e, without at least implicitly intending to appeal to something you would find evaluatively in favour if it from within your set of values, it would be coercive, in at least one intuitive sense of the term.) What Foucault and Chatterji do is to use this general connection between giving reasons and non-coercion to arrive at a specific conclusion about how liberal states must be coercive. Essential to their way of arriving at this conclusion, is the appeal to a relativism about the very notion of reasons.

Though he does not say anything explicitly about external reasons, Chatterji following Foucault assumes that the liberal state and its principles are founded on an externalist conception of reason which is indifferent to specific identities, and again, though there is no explicit argument against the shortcomings of external reason of the sort I have tried to present in the last few pages, it is very clear from his paper and a series of his other works, that he is deeply convinced of its shortcomings (on grounds no doubt very different from the ones I present because they depend on a normative communitarianism which I shun). And consequently. because he thinks the basis of the state committed to liberal and secular principles is indeed external reason, which is deliberately blind to communitarian identities, his view is that a community cannot intelligibly give reasons for resisting the anti-communitarian homogeneity inherent in the inevitable secularizing motion of so-called "nationalist" and "progressive" statist ideologies. To enter into the space of reasons at all is to surrender to and be overwhelmed by this alien, modern set of tendencies destructive of community. As lie puts it: "To say 'We will not give reasons for not being like you' is to resist entering that deliberative or discursive space where the technologies of governmentality operate. But then in a situation like this, the only way to resist submitting to the powers of sovereignty is to literally declare oneself unreasonable."

The general trajectory of his paper, and that sentence in particular, reveals something extremely startling and interesting. And that is that Chatterji, for all his manifestly communitarian sympathies, shares an assumption with his most bitter dialectical foe, the classical liberal tradition. I will describe it in the idiom and framework I have been using earlier in the paper. It is the assumption that if, in the face of identity constituting fundamental commitments, one cannot make coherent the classical liberal picture of reason or justification for the liberal and secular state, then reasons must fall out of the picture and the liberal state must necessarily be coercive because incommensurate. That is the crux of his use of Foucault's notion of 'governmentality'. But -remarkably -it is also the crucial assumption (as we have seen in the last section) of the reading of the notion of liberal rights that is found in the classical liberal tradition. Here too it is taken for granted that if there were no archimedean reason given for the justification of these constraints or rights, if their justification were derived from substantive values and commitments, then there is nothing to stop the slide into relativist communitarian mayhem. Chatterji would find the description "mayhem" tendentious, but he would be in total agreement that there was a correct point there, which he himself would describe more sympathetically than as "mayhem". Hence, for both classical liberalism and for Foucault, it is "external reasons or bust!". Despite their deep differences of attitude toward the liberal state, for both of them there is a common assumption, which is that the liberal state is necessarily (and not just in specific historical cases) archimedean. And if archimedeanism (i e, if the external justifications of secular and liberal principles) is not able to deal with the moral psychology of communitarian identity, then for both of them, the liberal state must necessarily pass into something else, something more coercive against communities, which, in turn, must be protected in various ways against its coercive power. Thus communitarianism. This is the tension between the liberal state and community that I mentioned at the outset. Its just that now we are in a position to understand the philosophical trajectory by which we have been landed with this seemingly unavoidable tension in our conception of the relation between state and community. And it is a philosophical trajectory in which the classical liberal and his Foucauldian critic are co-propellers.

I find in this assumption that they both share, the assumption that one must chose between an archimedean liberalism and communitarianism, a quite impoverished conception of the theoretical options; I have already addressed this issue by making theoretical space for an alternative reading of liberal principles provided on the basis of a quite different mode of justification for them than is found in classical archimedean liberalism, but a reading which at the same time makes no normative commitment to communitarianism either. I now want to concretely occupy this space by going on to argue against a very specific concrete instance of this shared assumption, a very specific consequence of their seeing the options in the restricted way the assumption sees them. The failure of the traditional liberal and the communitarian to see any other options to their own and to each others' doctrines translates into the following scenario in the context of a specific issue such as that of Muslim Personal Law in India today, a scenario in which the entire debate must be governed by a certain disjunction, a certain either/or: if there is to be change in Muslim Personal Law, it must either be statist reform by a secular liberal state imposing its archimedean secularism or it must be internal reform via the civil society or some more formal institutions within the communities. This is just a concrete version of the impoverished theoretical options. I mentioned a moment ago. And the theoretical framework I have been setting up in which moral psychology is exploited for political-theoretical analysis offers a tentative way out of such an impoverishing and disjunctive option. Perhaps 'impoverished' is the wrong word to describe what I am offering a way out from since it would be quite wrong to think that what is on offer is an enriching of choices with some third option. Rather what is on offer is to question whether the two disjuncts of the disjunctive option are really disjoint. In other words, the theoretical space created by this paper allows us to refuse to see why it is that theorizing about the secular state should, in this particular and concrete context, have it that internal reform cannot take place on a statist site.

This may seem initially startling, a contradiction in terms, but the suggestion is that it will seem so /only/ within the standard framework, one which, as I said. is shared by Chatterji as well as his dialectical enemy, the classical liberal. My proposal for an alternative seeks a way to refuse to allow that the liberal secular state necessarily be seen as coercive in the Foucauldian way against the values of a community just !because one recognizes the limitations of classical liberalism's archimedean aspirations.

Since for Chatterji internal reform is /ex hypothesi/ non-coercive, if it can be shown that a liberal secular state provides for internal reform in one perfectly plausible sense of that term, then even he would have to grant that such a state is non-coercive. To show this one has to show that the relations between state and community are still within the range of reasons. For, as we saw above, it was the denial oft his possibility that underlay Chatterji's Foucauldian anti-statist proposal for exclusively intracommunity reform via intra-community democracy. But, as I have been arguing, the rejection of archimedeanism, of external reasons, still leaves it open for the state to be the site for internal reasoning, whereby the substantive values of communitarian commitments can be addressed and, substantive internal reasons be given to communities to agree to a secular outcome. (In fact if necessary different internal reasons can be give to different communities, depending on the make-up of their internally reinforced values, for a common secular outcome.) Such a common secular outcome even though one starts with the descriptive acknowledgement of communities to be addressed by internal reasoning by the secular state is what I had, in my earlier paper, Two Concepts of Secularism', called a 'negotiated' secularism.[fn:20] And it provides tor a genuinely liberating perspective which is hidden from view only to the extent that one dogmatically reads the sense of constraint expressed by the idiom of rights exclusively in the classical reading of it. The perspective comes into sight as soon as space is made available for the notion of internal reasons. Chatterji raises the specter of governmentality only because he sees no scope for internal reasons. Exclusively non-statist intra-communitarian internal reform, therefore, is the last resort of relativists, who can find no role for internal reasons. But a proper understanding of the moral psychology in my framework should demonstrate that relativism poses no such drastic threat. Why not?

One answers this question by getting clear on what it is to give an internal reason to another with whom one is in conflict or with whom one is disagreed.

Relativism is the consequence of thinking that if there is no transparent or externally established value with which a liberal can trump those with whom she is disagreed (e g, if the archimedean version of liberal truth is unavailable) then liberalism has nothing to resort to by way of reasons, and everything else will seem like the coercions which Foucault described in terms of the phrase governmentality". So, the Foucauldian says, instead of being coercive we must leave it to those one is disagreed with to sort out things for themselves and hope they will come around to agreeing with us (intracommunitarian democracy being a natural proposal to try and achieve this in the concrete case we are discussing). If we intervened, for example by invoking the liberal state's backing as the carrier of liberal principles and truth, it would amount to coercion (governmentality) based on no reason (there being no other kind of reason but external reasons,-which admittedly, as we saw, are powerless as reasons in the face of communitarian identity). So the implication is that one cannot give an internal reason to an other. They must do it themselves with their own representative institutions

That implication is what I am denying. The possibility of giving internal reasons to another, which I am insisting on, is just the suggestion that despite the powerlessness of external reasons, it is still possible to be non-coercive because it is still possible to not ignore the point of view with whom one is in conflict. It is still possible to appeal with reason to the other's point of view in order to resolve the disagreement in our own favour. How'? The giving of internal reasons to another does not consist in just plonking down a reason by claiming for it that any rational person must embrace it (as Rawls does for instance when he appeals to the suasion inherent in his higher-order desire to have our future desires protected and fulfilled). Rather the giving of internal reasons to another necessarily seeks to find the other's moral-psychological economy infirm in the relations between its substantive desires, in the sense defined in Section II. (Or more strongly, if that is possible, to find it inconsistent.) That is, it hopes to find the moral psychology of the other lacking in internal reinforcement of some of the desires it espouses, in particular the desires with which we are disagreed.[fn:21] If one can demonstrate to the other that that is so we would be giving them internal reasons, reasons from within their own point of view, from within their own over all corpus of desires, to change their mind on the particular matter of disagreement. Now of course there is no guarantee that there will be such scope for giving internal reasons in all cases of conflict or disagreement with another. That is why there is perhaps no non-trivial /a priori/ argument against relativism about values and that is why, no doubt, some cases of conflict will be very hard. Any theoretical view that was blind to this would be unrealistic. All the same there is no reason to think that there is any permanent difficulty or impossibility in the providing of internal reasons to another in cases of conflict. In fact it is the possibility of such reason-giving to an agent or community with whom we are disagreed, which is a permanent one, since agents and communities, unlike perhaps rational automata, are not monsters of consistency. Nor are they ever likely to be possessed of a maximal psychological and evaluative equilibrium, i e, possessed of maximally reinforced desires in the sense we have defined earlier. Their desires and values are often in internal conflict, and certainly they are permanently in potential internal conflict since agents and communities live in an environment that is changing, and such changes will often inject conflict into their values.

This is just what Hegel called History and the dialectic it engenders. If we keep firmly in mind the cautionary remark stated in the footnote attached to this sentence. one very useful way of reading Hegel's primary insight here is precisely to see History as the movement and sway of internal reasoning in society with the state as the moral agent which is the seat and source of such reasoning.[fn:22] What Foucault fails to see despite some extraordinarily acute specif historical diagnoses of various social institutions, is that the success of these historical analyses yield him his heated relativist conclusions in political philosophy only because he is deaf to this Hegelian insight about History. As I said, it is true that there perhaps is no a priori argument against relativism once we see that the application of all archimedean strategies in politics such as Rawls and Mill will sometimes render the moral-psychological economies of certain agents and communities weak-willed and irrational. Even so, I am claiming that the right picture of moral psychology with its permanent potential scope for internal reasons should cause a sea of governmentality and relativistic anxiety to subside. Perhaps relativism is a genuine and intractable threat in situations where one is disagreed with another whose values are perfectly consistent, maximally reinforced, and permanently so. But it is safe to say that that is a contingency which is so remote, if it is coherent at all. that relativism can be dismissed as a possibility raised only by moral and political theorists who simply have not paid enough detailed attention to moral psychology and asked under what conditions is the giving of internal reasons to another agent or community impossible. The conditions, as I have just noted them, are so rarely likely to obtain, if they are even so much as conceivable, that it is quite theoretically unsound to formulate a framework for secularism, as Chatterji does. that elevates them to the normal circumstances which secular doctrine must address. Relativism. even if one cannot show it to be logically mistaken, all the same appears as a real threat only to those who have responded too generally and too carelessly to the (admittedly) archimedean excesses of classical liberalism. Chattcrji, despite the imagination and occasional rigor of his thinking, is one such. Relativism may not be refutable on logical grounds as archimedean conceptions of reason might imply, but equally relativism cannot be thought to describe the normal conditions for which theories and political frameworks and institutions must be constructed. What I am suggesting by contrast is that a clear conception of the scope for internal reasoning in politics captures far better than either archimedean liberalism or communitarian relativism the normal conditions in which multi-communal societies find themselves.

So, in our concrete case, I am arguing that we can dismount the seesaw of statist versus internal reform by clearing space for the liberating idea that internal reform can happen on a statist site. By this, I mean that the state can bring about reform in a way that appeals to (some of) the value-commitments of communities whom it is seeking to reform, in particular by appealing to values which stand in infirming tension with those values and practices which it seeks to reform. In other words it is the state which addresses them internally in a way that they themselves might have done on intra-community sites in Chatterji's conception. The general point is that internal reasons can be given to a community by another, by the secular state. and so the idea of internal reform can be transformed from something which necessarily happens on intra-community sites (as in Chatterji's picture of things), to one which can happen on a statist site. And if the notion of coercion is contrasted with the notion of reason-giving, a state which arrives at secular outcomes in this way need not be seen as any more coercive than the procedures by which these outcomes are delivered on intra-community sites. To see things this way is to see the liberal state as being able to provide a field of force of internal reasons addressing different communitarian perspectives from within their own internal substantive commitments and unsettling them into awareness of their own internal inconsistencies so as to eventually provide for a common secular outcome each on different internal grounds.

Such a theoretical view of the liberal state is of course dramatically different from the way in which the liberal state appears in Rawls and Mill. In a moment I will say more historically specific things about such an alternative to their conception of the liberal state. But first I want to stress that it is not merely different from Mills and Rawls and other such archimedean positions in the liberal tradition, it is also measurably different from the face-saving retreat of recent political theorists in the face of communitarian attack, which take all the content out of liberalism in order to save some of its universalism. Thus take for instance Laclau in a recent paper called the 'The Question of Identity'.[fn:23] After considering in detail the difficulty that ethnic identity raises for the universalities of secular liberalism of the classical picture, he explicitly rejects all 'secular eschatologies'. as he calls thm, and is prepared to see universality in politics retreat to the sparest minimum that makes democracy possible in the first place. Pointing out that even the particularists talk in the idiom of rights when they demand rights for minorities, he finds in this idiom a universalist discourse that enables democracy, even if not the full prestige of secular liberalism. He frankly admits that universality so conceived has no body and content, it is, as he puts it, a whole vocabulary of empty signifiers which surface precisely in such paradoxical phenomena as communitarians necessarily succumbing to the rhetoric of minority rights. But why should we allow the difficulties raised by identity to abandon full secular outcomes for such manifestly skimpy universals in liberal politics? To see the state as a possible field of force for internal reasons is precisely not to adopt the strategy of retreating to thinner and thinner neutral ground that all communities and particular identities must minimally share. It is rather precisely to give up on seeking neutral common agreement which may be necessarily thin gruel in a multi-communal society, and instead for the state to seek for the thicker brew of a fully secular outcome via a signing up to a common secular outcome for different and therefore non-neutral reasons from within their own very different substantive value economies. This is exactly what I had in the earlier paper on secularism called an 'emergent' and 'negotiated' secularism.

Let me, then, re-introduce explicitly a theoretical term here tor this idea of internal directed changes sought by the state within the value commitments of communities, and call them 'negotiations'. I call it a theoretical term because it is a term of art, a placeholder for anything which brings to effect a certain kind of value outcome via internal reasoning. A secularism, which is the outcome of changes so achieved, would then be a 'negotiated' secularism, and if the changes were brought about on statist sites, it would be the achievement of a non-archimedean secular state, one to which no doubt both the classical liberal and Foucault would take grave objection the classical liberal because she allows no ambiguity in its reading of the notion of liberal constraints expressed in liberal principles, and Foucault because his exaggerated anxieties about relativism have generated his peculiarly influential kind of anti-statist neurosis.[fn:24]

I am keen to stress the highly theoretical nature of what is intended here by the term 'negotiation' because I want to warn against an unthinkingly vulgar interpretation of the idea that might result by confusing it with what the term connotes in more common usage. In particular I want to warn against what is intended as either certain limited forms of alliances or certain cynical concessions by the state to communities for manifestly unsecular outcomes.

Thus, for instance, it stands apart from something like the Leninist concept of class alliances, where the agreement concerns only circumstantial matters, but the identity of the most reinforced desires, the values, remain unrevised by the negotiation. It stands distinct from this concept since what negotiation is intended to achieve is a revision in communitarian commitments, revision toward secularism via internally directed reasoning.[fn:25]

So also it stands distinct from the sort of thing that Sumit Sarkar attributed to me in a recent paper before criticizing my idea of a negotiated secularism. He says:

#+begin_quote
Through a detailed critique of Partha Chatterji and Ashis Nandy, Akeel Bilgrami. I think, rightly rejects as unsustainable any vision of secularism which harked back nostalgically to the idea of a pre-modern India. His alternative, however, is to acknowledge that secularism as a value through negotiation... Partha Chatterji, interestingly, comes to a rather similar conclusion... At the practical or pragmatic level the curious thing about Bilgrami and Chatterji is their lack of originality. This, after all, is what the much-abused Indian secular state policy at its worst has often amounted to: efforts at placating conservative or communal Hindu and Muslim community leaders simultaneously. The classic recent example would be Rajiv Gandhi in 1986, opening the locks of Ayodhya and surrendering to Muslim fundamentalist pressure on the Shah Bano case...[fn:26]
#+end_quote

Well, I have already said something at the beginning of this section about conflating my position with Chatterji's. And I do not know what to say about originality, since I was not in any case trying to be original, I was only trying to say what I thought was true. It did surprise me though to be told that what I did say was anticipated by Rajiv Gandhi. In fact when I first heard and read Sarkar's charge, it flabbergasted me to learn that Rajiv Gandhi's playing of the Hindu card and then the Muslim card during this period should be seen as an instance of what I had in mind by the use of the term 'negotiation' [fn:27] since it was part of that point, and in tact it was explicitly part of the point of the entire paper that Sarkar was criticizing, that we need a diagnosis of why an avowedly secular state seemed so often to appeal to the most shrill and communal among the voices in a community, when it did appeal to the community. Far from commending this sort of cynical sops to the reactionary communal elements in communities, the paper was demanding a diagnosis for why "negotiation" (in the very specifically theoretical sense in which I had introduced the idea) was abandoned for those sops. Why, for instance, in the very example that Sarkar cites, did Rajiv Gandhi take it for granted that he should not listen instead to the voices of the impressiveness of Muslim women who demonstrated outside the parliament during the episode of the Muslim Women's Bill? Or to put it more generally and diagnostically. how is it that al avowedly secular state finds itself repeatedly failing to be in a position to confidently assume that the moderate voices in a community (which even if less shrill are surely the more numerous) are the more representative of public opinion on such things as the status of a mosque or of personal laws, or in an earlier period, the status of Urdu, and soon.[fn:28] How is it that when it does repeatedly appeal to or address an issue that is necessarily located in community, the state has tended to appeal to the far smaller but more vocal reactionary element. In short, how is it that the state has over decades failed to democratize the vast mass of ordinary people in a community, so that the reactionary element is seen to he exactly what it is, a small and unrepresentative minority within the community? And I had suggested that part of the longer diagnosis of this phenomenon might be that even before statehood was acquired, secularism was the archimedean rhetoric of a party which for six decades was nevertheless marked by the making of concessions to the Mahasabhite and then subsequently other Hindu Right leaders within the Congress Party and the leaders of the communal Muslim elements outside the party. I had speculated that the pursuit of a less archimedean rhetoric and a greater such democratisation for which there would have to be more descriptive acknowledgement of communities, would have allowed for the sturdy engagement of contestation by internal reasoning with the communities, and may have preempted the need for constantly having to make concessions to the most communal elements to keep them subdued. Sarkar thus came to cite his example of negotiation as a criticism of my view only because he quite failed to see the point of what I had termed 'negotiation', which was a process whose outcome was not intended to be such appeasement, the outcome was supposed rather to be secularism via internal reasoning with the communities' other values.

The ideal here is necessarily a delicate one to bring to practice. But as an ideal it strives to do at the site of a state what Chatterji thinks can only be done at intra-communal sites. Chatterji's argument is a simple one and it has its logic. Though he does not put it this way, it is a way to put it: if you grant rights to minority communities, then there is a danger that a small sub-minority of shrill reactionary voices within it will dominate the communitarian space you will create, so you must introduce intra-communal democratic and representative institutions, to stay their influence. But the logic need not get going in the first place, if the state were to be the site and the instrument where this democratisation happens.

What a secular state, trying to cope with communitarian political voices on specific issues of the sort mentioned above, can do to give those voices the confidence to attend to the conflicts within their own thinking and values, and then internally reason them toward progressive and secular commitments is not an easy question. But no Hegelian question is easy. What gives confidence and what overcomes defensiveness in a community is various, and it is impossible to generalize about independent of very local context. It is for this reason that the conditions that make possible a negotiated secularism should not be pinned down more specifically than the concept in its generality allows. It is for this reason that I have insisted on defining the term in a "whatever-it-takes" formula, and then tried negatively to say what it definitely is not.

It is possible that a refusal to acknowledge communities and communitarian issues even descriptively and a focusing instead exclusively on the issue of class a familiar, longstanding, and extremely attractive strategy would be effective. But it is not at all obvious first of all that ongoing issues such as personal laws of Muslims will go away so simply, and by such an indirect strategy, and in any case it is not obvious that the sort of Left programed that would have to be effective for that to happen is one that we can expect to be implemented in our immediate times. Speaking historically, I think it is not at all obvious that even its most vigorous proponent in the mainstream national movement Nehru himself seriously believed that it could be implemented except for about two and a half years in the 1930s.

None of this suggests that the Left Programme should be abandoned, only that other secular strategies should not be abandoned in the interim. Nor do the other strategies have to be in any antagonism at all with genuinely Left thinking, so long as such thinking does not confuse normative and descriptive attitudes toward community and assume that all descriptive acknowledgement must amount to a normative one, or assume that a mere descriptive acknowledgement of community will thwart the ideals of the Left toward class equality. There is no reason for a Left Programme to think any of these things because these are all confusions and non-sequiturs.

My seemingly paradoxical proposed strategy for a statist version of internal reform has two ingredients that are essential and which will remove the air of paradox. One is the democratisation of the community and the second is the arrival at secular outcomes by internal reasoning with the community (for both of which one has obviously to have what I called a descriptive acknowledgement of community) .[fn:29] Without the first ingredient, the second is not likely to occur. And the connection between the two is not hard to see. The two ingredients are connected by a background premise essential to the strategy and framework I am proposing, a premise, which I actually take to be true even in a country like Iran today. And that premise is the simple fact that in any religiously characterised community, such as Muslims and Hindus,[fn:30] the large majority of its members are not 'extremist' or 'absolutist' or 'fundamentalist' (all these expressions apply to slightly different things, but for the moment I will not be sensitive to the discrimination). The large majority of the members of such communities whether in Teheran, Bradford, Bosnia, Ahmedabad, Mumbai, or Ayodhya, are either indifferent to the enthusiasms of the extremists, absolutists, and fundamentalists, and busy with their own various occupations and preoccupations, or they are positively against. the disruptions that those enthusiasms bring into their lives and the distortions that they bring into their understanding of quotidian religious practice and doctrine.[fn:31] It is a distinct minority within the community which has the fundamentalist enthusiasms, even though because it makes the loudest noise this may not seem so and it certainly does not seem to have been taken to be so by successive recent occupants of the Indian state.

Beginning with this empirical premise, the strategy's appeal to its first ingredient, democratisation, is just the following. Given that the majority in a community are not in any case actively or deliberatively opposed to secularism, how is it that this distinct majority can be put in a position to be seen as exactly that, the majority, the voice more representative of the community's position on such matters as secularism and reform than the fundamentalists. 'Democratisation', in my picture, is a label for the process by which the state sees to it that they come to have this position and can confidently assume them to truly have this position when issues such as reform of personal law come up. For once they can be seen to be the more representative voice, internal reasons can be given much more easily to the overall community to embrace the reform of various things that the state wishes to impose.[fn:32]

Democratisation is a necessary condition for successful internal reasoning with the community because until it is achieved, even this majority which has no deep shared value commitments with the minority of absolutists, is not likely to oppose the latter. Often there is a seemingly understandable reason why the majority within the community fails to stand up to the absolutist minority. Often it is due to a certain defensiveness against outside pressures on the whole community (whether it is the pressures on Muslims of India created by the forces of hindutva or the pressures created on Muslims in west Asia by the neo-colonial presence of the west and its client states such as Israel, not to mention Saudi Arabia and Kuwait). There is a feeling among the majority within the community, even though they have no sympathy for absolutist tendencies and enthusiasms of the minority, that in the presence of these external pressures on the community as a whole, they would be letting down the community as a whole by opposing the minority of absolutists within it. I have written about such defensiveness in detail in my paper 'What is a Muslim?'. I would not rehearse that discussion here. Enough to say here that it is the task of the state in such a situation to help overcome this defensiveness precisely by democratizing the community so that its most representative sections can have the confidence to resist both the external pressures and the internal pressures of the minority whom they oppose a good and necessarily dual struggle since it is succumbing to the latter pressures which gives propaganda strength to external pressures in the first place (witness the hindutva propaganda on the Muslim refusal to accept any criticism of their personal laws). Until,the democratisation takes place and the majority within the community is filled with a certain confidence of its place in the community as the representative voice, they will never allow those of their values that reinforce the need for reform in the community's practices to trump those other values which are engendered by the defensiveness, and so internal reasoning is not likely to have the effect of promoting internal reform.

That explains a little the. role of democratisation as a necessary condition for the success of internal reasons toward secular outcomes. (I will give further below two historical example of efforts at democratisation which can lead to a progressive secular outcome by internal reasoning.) Its not as if Chatterji does not see this point. But Chatterji thinks this democratisation should happen via intra-communitarian democratic institutions because his relativism makes him start with the assumption that internal reasons cannot be given to a community by any other than the community itself, i e, it cannot be given or provided by the state. Since I think the relativism is not a threat, I think his starting point is wrong; and I also think that his positive proposal for intracommunity democratic institutions to effect the democratization's has its perils. It is rather the secular state' s obligation to produce such a democratisation.

The perils in Chatterji's proposal are obvious. An institutional setting of formal democratic representation within the community would have the effect of entrenching the community in a way that goes well beyond the descriptive acknowledgement of community into a normative promotion of it. Being a communitarian, Chatterji may not find this perilous, but others who also want internal reform but who do not share that normative commitment to community may find this a case of keeping the bathwater. At any rate, a case of taking several steps back in order to take one forward.[fn:33] If one wants to avoid these backward steps, how else may one think of democratizing communities?

There is no alternative but this: for the state to actively bypass the elite or reactionary leadership of a community, i e, bypass this small but vocal minority (found, for example among Muslims in India, in such leaders and spokesmen as Bukhari or Shahabuddin) and intervene in the creation of a broad-based or mass politics directed towards community in order to democratize them.

If my dialectic,which begins with a certain empirical premise is right, this is a necessary precondition for the state' s capacity to create a field of force for internal reasoning that might yield a negotiated secularism, as I envision it. Until such democratisation occurs it is premature to ask the question, what are the institutional sites where the state can provide for such a field. On legal matters such as personal law, the eventual sites are bound to be sites such as the constitution, the legislature and the judiciary. But there is no canonical format for the effecting of internal reasoning with communities, i e, no canonical format for what I have called 'negotiation'. Recall that 'negotiation' is not intended by any means to be an elite settlement by discussions around a table. The notion of 'negotiation' does not necessarily even imply as I hope is clear by now that communities must sit and talk together.[fn:34] No more so than 'co-ordination' in co-ordination theory implies necessarily that the groups or agents that co-ordinate must convene and talk themselves into a coordination equilibrium. The state can be the moral agent which effects co-ordination without in any way spoiling the ideals and ideas of co-ordination theory. Exactly so for my notion of negotiation. This is why in my earlier paper I had also interchangeably called it an 'emergent' secularism. So it is not possible to say that secularism 'emerges' or the state 'negotiates' things to arrive at a secularism via some particular canonical format, and it is not in general within the scope of this paper to articulate detailed institutional blueprints for what is to be done by a secular state such as India to implement the framework the paper has developed, especially prior to any effort by the state to democratize the communities. It would be pretending to more predictive power about the exact and detailed consequences of specific democratizations, to do so. This is because diverse contexts in which different methods of democratisation are attempted would yield diverse institutional settings. But all the same there are very interesting (if not sustained) historical antecedents to the idea I am pursuing, and all that this paper can do now after having sketched the beginnings of an alternative theoretical framework, is to cite them so as to give a rough sense of what in concrete terms it's framework envisions. Let me close, then, by citing two.

One is the Muslim Mass Contact Programme launched briefly by the Con Party in the late 1930s, which was a reve moment in the national movement. What programme revealed was a somewhat pan acknowledgement on the part of the Con Party that their archimedean rhetoric their rhetoric of 'compositeness' )[fn:35] was  ineffective and had done nothing very m to democratize the Muslim voices in the country so that the progressive among them could emerge as the representative voice. The archimedean stance of Congress secular rhetoric had all along been something like this: "Being secular we stand for everyone and don't distinguish between communities!" How did the mass contact programme I am invoking reflect a repudiation (albeit a brief one) of this archimedean rhetoric? The very fact that it was a Muslim Mass Contact programme was an acknowledgement at least implicitly -that the party's archimedean secular stance had been quite blind to the need for descriptively acknowledging Muslims and then democratizing them so that they did not get hijacked into the narrow and elitist communal direction that Jinnah's politics was aiming to direct them. It is not at all surprising therefore that the programme angered Jinnah and filled him with a sense of danger, for it hit him where he was most vulnerable, his elitism and his capacity to manipulate a visible, vocal, and well-placed minority among Muslims capable of sounding communal anxieties to the colonial state.[fn:36] It is only such a democratisation of a community at the level of its masses that could have the effect of giving its non-communal leadership a position of center stage as representing the community, a necessary step for an eventual secular outcome. It would not be idle, in fact it would be most interesting, to speculate whether the Muslim Mass Contact programme, had it not been prematurely and abruptly arrested by the Congress Party's own leadership, would have had the sort of democratizing effect within a community whose name the movement took, and therefore had the confidence inducing effect within the community, which I am claiming is a necessary condition to achieve the eventually negotiated alternative to archimedean secularism on the one hand and to intra-community internal reform on the other. Admittedly in this case the democratisation would not exactly have been done on a secular statist site since an independent state had not been achieved, but it would have been a genuine proxy for it since after all it would have been at the site of a secular party gearing itself to acquire statehood. That is enough for me to make the point I want to make against Chatterji's anti-statism and his insistence on intra-communitarian sites for democratisation and reform.

Another historical moment (also very quickly aborted) which is not quite so clear a case of an effort at democratisation by mass contact, is still interestingly revealing of how a broader section of a community can be given confidence by a state and then induced by internal reasoning toward a secular outcome. I have in mind Bengal in the time of the C R Das Pact. Consider the following very specific case. A close look at the details which surrounded the woman suffrage bill which was passed in 1925 in the provincial legislative council, after having been defeated four years earlier, suggests very strongly that it was the pact (adopted in 1923) which was central to this progressive and secular legislative reversal. Muslim members of the legislative assembly had voted predominantly against the bill in 1921, but by 1925 it was the Muslim members, specially the Swarajist Muslims behind C R Das, who had been emboldened to vote for it in large enough numbers to make the difference and get the bill passed.[fn:37] And they did so despite the fact that the party exercised no whip and in fact made an explicit decision not to put pressure on them to do so. The pact gave them the confidence to allow the arguments appealing to their own nationalist and secular values (arguments which were pressed upon them by their nationalist colleagues) to internally trump their own other values by which they themselves had argued for the opposite conclusion four years earlier, viz, that stricter observance of purdah among their women would inhibit them from voting and put the community to a disadvantage. I think one can see in the dialectic of this legislative turnaround and in this moment of the Bengal Pact, which was in other ways too a very dynamic period in Bengali colonial history, a sense of what I had in mind by a field of force of internal reasons being carried out on a statist site by which a progressive and secular outcome can be achieved. The pact and its architect bypassed the aristocratic and the westernized Muslim leadership and appealed directly to a far larger class of Muslims in the districts. Such a broad-based support for Das's Swarajist politics no doubt came partly as a result of the pact's fairly generous concessions to Muslims on the matter of their representation in the council and in local bodies and government appointments, which in today' s politics would be rightly considered a non-secular arrangement. But despite this perfectly correct contemporary response to such arrangements, it would be quite anachronistic (in a context shaped by the Montague-Chelmsford reforms which had explicitly articulated a policy of separate electorates for communities) to say that that such concessions as the pact made then to a community that formed the majority in the province, was an entirely unworthy method of giving the community the confidence it needed to reason its way to a less insular and more progressive politics. And in any case, it was not just these concessions that lay behind the democratisation for, as Chatterji himself points out in an interesting article,[fn:38] the background of the Non Cooperation-Khilafat movement did much to broaden the base of Muslim politics in Bengal a background which made a considerable difference to the pact's capacity to convert Muslim leaders to the less insular and more progressive way of thinking. Hence even though the pact was not endorsed by the National Congress Party, and its good effects in Bengal were all quickly reversed after Das's death when communal politics returned to Calcutta and Bengal, the fact is that for a very dynamic and revealing period of three years or so, this pact, which was unlike all previous Hindu-Muslim pacts in intention and effect, went beyond elite settlements on seats and offices to the democratisation of the Muslim community. And the general point I want to stress in raising this example of the pact is that it was the provincial state under Das that was responsible for this democratisation which in turn allowed, as in the specific legislative example I gave, for the community's leaders to be internally persuaded out of their communally defensive resistance to a progressive piece of legislation.

These are all details, details about how the state needs to intervene and democratize in a way that the state can then on all matters regarding the secularization and reform of a community's practices assume that the (moderate) majority within a community (which has no absolutist objection to secularism) is the voice which gets heard, thereby allowing for an internal basis for the state's liberal and secular reforms. All of this requires a descriptive acknowledgement of community by the state, which archimedean secularism refused, but it requires no normative commitment to community, which communitarianism pursues.

Getting back then to the overall theoretical framework, I hope these details convey something at a concrete level of the theoretical space I have been trying to clear in these pages. That space was the space which lay buried under a thoroughly misleading and conceptually impoverishing disjunction that I began with. It is a space sensitive to the moral psychology of identity which is missing in the classical liberal formulations of secular liberal doctrine such as Mill's and Rawls', at the same time as it is a space that does not permit any scope for this sensitivity to degenerate into a relativistic and anti-statist communitarianism. Chatterji, and Foucault' s disciples generally, have their right to be despairing of the state in the face of its many failures, though one wishes they would remember its many successes as well. But despair is one thing to which anyone has a right depending on how they perceive and interpret the facts around them. It is quite another thing to erect their despair into a philosophical doctrine that entails an a priori pessimism about the state. This space, which Chatterji fails to find, is one that gives one an equal right to take a different attitude than despair in the face of the state's failures, since it allows us a question which for him is necessarily bogus, the question: "Why can't we struggle to improve the state?" This paper has tried to give a very abstract and perhaps needlessly complicated argument to make that space and that simple question possible. Political theory generally, and liberal doctrine in particular, desperately need rigorous formulations to fill such a space.[fn:39]

* Notes

[fn:1] As is well known, the directive in the Indian Constitution about uniformity in the civil code was delayed in its application due to the sense of its framers that Muslims were not yet in a state of preparedness to embrace it.

[fn:2] It is a natural worry that, in certain contexts, the idea that members of a community (say, traditional Muslim women in India) can simply up and exit their community so as to be free of the oppressiveness of some aspect of personal law, is not a realistic idea. There may be too much by way of internal inhibition as well as external constraint for them to be able to do this easily. In these contexts, the right to exit will not be a powerful enough liberal tool, merely an academic and formal liberal proviso. As I have argued in my paper "What is a Muslim?" over and above the right to exit, another thing for liberals to strive for is to democratize the community away from its absolutist leadership so that a sense is created in the community that if the secular state requires it to give up on this or that element in a legal code, it would not mean that it has destroyed the Muslim identity of its members. The idea that one sheds one's Muslim identity if one gives up on some laws is an idea based on a highly codified concept of identity, and need be no part of the self-conception of Muslims, so long as they are not dominated by an unrepresentative fundamentalist leadership which dogmatically distorts the psychology of identity by insisting on such a codified conception of it. For this a certain sort of democratisation has to take place, on which more toward the end of this paper.

[fn:3] I have written elsewhere on the compatibility
of an intelligibly formulated determinism with agency and moral psychology. See the last few pages of 'Two Concepts of Secularism: Reason, Modernity and the Secular Ideal', Economic and Political Weekly, July 1994, and also 'Self-Knowledge and Resentment' in Knowing Our Own Minds, Crispin Wright and Barry Smith (eds) (Oxford University Press, 1997). It gets a more theoretical treatment in my Self-Knowledge and Intentionality (forthcoming 1998: Harvard University Press). As for methodological individualism, I am, for the purposes of this paper, assuming that everything I attribute in moral psychology to a community can be translated without residue into attributions made to individuals under the aspect of their communal identity. Thus, the idea that Muslims desire or value x can, if one wishes, be translated as the idea that many or most individuals, qua Muslims, desire or value x. So, no attributions of desires or values to communities made in this paper have to be seen as non-supervenient on individual attributions, in order to make their point.

[fn:4] I say "in the normal case"" because of course someone can strain and contrive to cook up scenarios in which for some person the desire for tea may be linked with more than consistency to the desire to do philosophy, in which case the contrast between the two pairs will be lost. In that case one will just have to appeal to different examples to raise the point of the challenge. The challenge holds just in case there are any cases of relations where there is an intuitive relation between desires which exceeds consistency in this way without collapsing with instrumentality. The fact is that any psychological economy is ridden with such relations between desires, and that is why reinforcement is such an important and central notion for the study of rationality.

[fn:5] Saying this here does not take a stand on the question of supervenience of these attributions to collectives upon attributions to their constituent individuals. See the closing remark in note 3.

[fn:6] I use the word value 'economy' and psychological 'economy' earlier to talk of a corpus of values, and desires more generally, which have internal relations with one another, relations that contribute to their overall rationality. This is a quite specific use of the term and I hope the reader will not be tempted to think that this use of the word has anything to do with recent uses of such expressions 'moral economy'. It does not.

[fn:7] The reason for this exception to an approval of the ordinary conception of rights should be obvious and familiar. The case for rights of individuals against, in particular, a socialist state is notoriously weakened by widespread historical contingencies in which the full exercise and protection of these rights predictably leads to measurable deprivations for large sections of the society.

[fn:8] John Stuart Mill, Chapter II in "On Liberty", Three Essays (Oxford University Press, 1975)

[fn:9] Rawls, Theory of Justice (Harvard University Press, 197 1) and Political Liberalism(Harvard University Press 1994).

[fn:10] This is the most interesting way of reading Rawls, since it makes the project intellectually the most ambitious. If we did not demand that the principles should be chosen no matter what we contemplate ourselves as being, then those contracting might gamble that they would not have this or that substantive conception of the good when the veil was lifted, and so might choose principles which are indeed biased in favour of the range of substantive values in favour of which they have gambled. This would not yield principles of justice, or justice as fairness, to use Rawls phrase. And then to rule out such outcomes, some constraints of a sense of fairness would have to be built in to those contracting, which would make the theory much less ambitious, i e, the method would begin to look like one of fairness in-fairness out.

[fn:11] See Political Liberalism, op cit.

[fn:12] Mill's argument, crudely put, says that we should embrace freedom of expression as a principle even if we are very devoted to our opinions and find dissent from them repugnant, because it has often been the case in the past that people (including ourselves) have held their opinions devoutly and these opinions have turned out to be false.

[fn:13] I do not actually think that there is a well formed debate about the rights and wrongs of modernity. I have argued so in my paper 'Two Concepts of Secularism: Reason, Modernity, and the Archimedean Ideal', Economic and Political Weekly, July 9, 1994. Also in another paper entitled, 'Nationalism, Secularism, and Modernity' in ' Bhargava (ed), Essays on Secularism (Oxford University Press, India, 1997)

[fn:14] 1 have done so in the last part of my article 'Two Concepts of Secularism', op cit and in an unpublished manuscript entitled 'Marx and Self-Deception'.

[fn:15] op cit.

[fn:16] op cit.

[fn:17] Actually the accumulation has been longer and thicker in the stewing. Apart from the papers just cited, and also the papers cited earlier on redefining certain Marxist notions along internalist lines, there were papers which discussed the Rushdie controversy along these internalist lines, arguing that the best defense of Rushdie was not to plonk down the free speech principle as an archimedean liberal truth but to argue for the principle by appealing to values internal to Muslims. See 'Rushdie and the Reform of Islam', Economic and Political Weekly, March 24,1990, and 'Rushdie, Islam and Post-Colonial Defensiveness' in Yale Journal of Criticism, 1992.

[fn:18] 'Secularism and Toleration' in Economic and Political Weekly, July 9, 1994.

[fn:19] Michel Foucault, 'Governmentality' in Graham Burchell, Colin Gordon, and Peter Miller (eds), The Foucault Effect: Studies in Governmentality, (University of Chicago Press, 1991)

[fn:20] op cit, I had also there called it an "emergent secularism". More recently Charles Taylor has also written a fine article on secularism along these lines in terms of the notion of an 'overlapping consensus' which is to be published next year in a volume of essays edited by Amiya Bagchi. My present paper and his paper were both presented at a conference on 'Multiculturalism and Governance' held in Kasauli in March 1995. Professor Bagchi's volume is to be a publication of that conference's proceedings.

[fn:21] The reader must keep in mind firmly the broad sense of "desires" with which I began.

[fn:22] Of course in one sense it would be a highly revisionist reading of Hegel, since it would not embrace any of the determinist and historicist trajectories that surface in his writings. There is no suggestion in what I am saying of the idea that History and the internalist dialectic it engenders leads inevitably to liberal or any other consummations.

[fn:23] In Wilmsen and Mcalister (eds), The Politics of Difference, University of Chicago, 1996.

[fn:24] 1 use the term neurosis, despite its edge, deliberately. And I cannot resist recounting an exchange to justify its use. After giving this paper in Calcutta recently, I was asked a question (with a slight sense of challenge) about whether I did not think that all of the states which I thought progressive were coercive. I responded that I did not think it terminologically useful, for instance, to describe the incipient welfare state in Britain immediately after the second world war as 'coercive'. And as a counter challenge intended half in jest, I asked whether the person asking me the question would describe an agency of the state which offered an individual free surgery when he was in dire need of it and wanted it, as 'coercive'. The reply came quickly: Yes, it would be properly described as 'coercive' since the individual would very likely not know the rules and principles of the state's bureaucracy by which the free surgery was being made available, and that was proof that the state was an external agency to which one simply submitted without any detailed knowledge of its workings over us. To my mind here 'coercion' has become a ludicrously cognitive notion (a grotesque caricature of the cognitive turn that Foucault brought to the notion of power) as if one would be 'coerced' by a breeze that one was enjoying just because one did not know the principles by which it blew over one! 'Neurosis' seems to me a quite apt description for what such anti-statism has become

[fn:25] Of course Lenin was quite right that if one understood the concept of class properly, then class alliances would necessarily be of this kind. Its not that I am saying that he was wrong to say what he said about such alliances, its rather that I am saying such alliances are not what I intended by 'negotiation'.

[fn:26] Sumit Sarkar, 'The Anti-Secularist Critique of Hindutva: Problems of a Shared Discursive Space' in Germinal (vol 1, 1994).

[fn:27] Even more numbingly crude a confusion lay in another charge that my descriptive acknowledgement of communities amounted to a vision like the millet system during the Ottoman period, where for instance Russian and Greek Orthodox communities were accepted as living under their own codes of law. (This, despite the fact that I had stated repeatedly in that paper that such an acknowledgement was to be the first step to finding a way to arrive at a uniform civil code.) I was in fact amused to hear that this was the reason cited for not reprinting my article 'Two Concepts of Secularism' in the publication of a leftist journal. Of course, it is perfectly natural for a leftist publication to not want to reprint an article which made such a claim. The scarcely credible thing is rather that such a claim could possibly be seen by a cleat-headed and honest reader to be even remotely implied by the words I wrote.

[fn:28] There is no reason to believe that the vast masses of ordinary Muslims and Hindus distant from the elite bargaining at metropolitan political sites, had the sort of deeply felt reactionary communitarian commitments needed to bring about outcomes such as the bill in question, or (in the case of the Hindus) the destruction of the masjid at Ayodhya and in earlier days the suppressing of Urdu in Northern India.

[fn:29] But, equally, descriptive acknowledgement of communities without these two elements is obviously not enough for if it were, it might take the form of cynical appeasements to the most communal and reactionary element of the communities, as in Sarkar's example which I discussed above.

[fn:30] I will repeat here something I have been saying as caveat in all my writing on this subject. The very idea of a religious community is a,problematic one since 'Muslims' and 'Hindus', as categories which we invoke, are meant to describe a collection of people who are in many senses neither religious nor a community. Like all such categories they homogenize diversified social phenomena. But this anti-homogenization point can also be made into a banality, and it does not follow from it that we shouldn't invoke these categories at all. In describing the politics, say of the Hizbullah in Lebanon ora prominent strain in the Algerian opposition, it is perfectly natural to describe the ideologies as consisting of a highly politicized vision of a religious community. Does it mean that all Muslims share this ideology? Does it mean that Muslims everywhere do not have other identities than their Muslim-ness? Of course not. But the having of multiple identities does not cancel the idea that in certain historical and political contexts, religious identities might dominate many of the other identities, in some populations in some parts of the world. And much of the broader application of categories like 'Muslim', as I have said in earlier papers, comes from the fact that many others who may not share any of these ideologies or even these contextually dominant identities in their personal lives, do not (out of defensiveness against external alien forces) reject the ideologies and contextually dominant identities of the absolutists. See the next few paragraphs in the text for more on this defensiveness. See also 'What is a Muslim?', op cit.

[fn:31] In my earlier papers on Rushdie and in 'What is a Muslim?' I had referred to this majority within a community as "moderates". I am not happy with that term, but do not have another to put in its place.

[fn:32] I intend this point to be general and not one just about Muslims and internal reform. That is why I mentioned Mumbai, Ahmedabad, etc, above. I believe that if democratisation had occurred of Hindus too, then the state could have confidently assumed that the majority of Hindus felt nothing very strongly about opening of the locks at Ayodhya and left things well alone. Its only because a minority of Hindus had lobbied in the public domain in a frenzy while the majority had remained silent (a failure of democratisation) that Rajiv Gandhi could play what he himself called the 'Hindu card". Failure of democratisation is reflected in the fact that Hindu opinion was thought to be represented by this shrill minority.

[fn:33] Given his general anti-statism, there is in any case a somewhat inconsistent disregard on Chatterji's part for the coercive possibilities of intra-communitarian statism that would be created by his own proposal. After all if individuals within the community dissent from majoritarian outcomes in the deliberations of a community's representative institutions, why should this not amount to those individuals being coerced just as much as communities claim to be coerced by secular majoritarianism at the extra-community or national level. There are two (related) reasons I can think of for why Chatterji should be blind to this possibility: (1) his communitarianism conceives communities as the ultimate repository of social good, so statism within the community cannot be objectionable; and (2) statism is acceptable within the community and not at the level of nation because individuals have primordial allegiances only to communities, and not to more abstract things like a nation. Both these reasons would allow him to disregard the worry about the intra-communal statism being coercive of individuals within the community since, given the first reason, coercion cannot occur where one is constituted by what is supposed to be coercive, and, given the second reason, one could not be coerced by the agencies of something to which one has a primordial allegiance, only by the agencies of something to which one lacks such an allegiance. I find both these rationales very suspect. In the first, such a strong conception of the social constitution of the individual by the community amounts to a rather dangerous theoretical consolidation of traditionalism and social conservatism. In the second, I don't believe that there are any primordial allegiances, that is to say allegiances which could not be overturned as a result of lacking reinforcement in the sense defined above and when they are so overturned, the agencies of the intra-communitarian state should seem no less coercive to Chatterji than the nation-state.

[fn:34] Not that it need always be a bad thing if they did so. Its just that that is not the point of the notion of 'negotiation' any more than it is (as I say below in the text) of the notion of 'co-ordination' in co-ordination-theory. Even Sarkar in the preposterous example he cited does not seem to think it is a case of leaders getting together and negotiating. But I can see how the word 'negotiation' might lead a reader to think that it is, if he does not pay attention to what else is being said, and to that extent I should perhaps have chosen another word. I had, in fact, in the earlier paper also used the term 'emergent' secularism as a synonym of 'negotiated' secularism and as an antonym of "archimedean" secularism. Even so Gyan Prakash seems to have been misled by the word 'negotiation' to miss the point when in a comment on a paper of mine given at Columbia University, he suggested that my view of how secularism was to be achieved sounded too much like a debating society ideal. The examples of negotiating moments which I give below in the text, and which I had cited in the paper he was commenting on, i e, Bengal in the period of the Das Pact and the Muslim Mass Contact Programme, do not seem much like debating society events. But, in any case, I don't even think that the ordinary use of the word 'negotiate' (quite apart from my theoretical introduction of it as a term of art) always requires any thing like people getting together and talking. We often say "She negotiated that difficulty very well" or even "She negotiated that crowded intersection very well" without there being any suggestion of getting together and talking with others. It just means that she came out of these situations very well by acknowledging a certain problem and deploying the means she had at hand. In my usage; the state similarly negotiates an outcome (a secular outcome, in this case) by acknowledging the descriptive fact of communities, and deploying the means (democratisation and internal reasoning) which it has at hand, and this need not in any way involve the communities getting together and talking. (The historical examples I give below certainly do not involve it.)

[fn:35] Congress talk of 'compositeness' was their occasional effort at stepping down from the high horse of archimedeanism to acknowledging the problem raised by the descriptive fact of communities. In 'Two Concepts of Secularism' I had criticised the disingenuous talk of"compositeness" by the Congress Party as a specific way of avoiding the tasks of democratisation.

[fn:36] There has been a tendency to think that Mass Contact Programme was restricted to a very small area. For a good corrective to this see Mushirul Hasan's essay 'The Muslim Mass Contact Campaigns' in Mushirul Hasan (ed), India's Partition (Oxford University Press, India, 1993)

[fn:37] For details, see Bengal Legislative Council Proceedings, September 1921 and August 1925.

[fn:38] 'Bengal Politics and the Muslim Masses, 1920-1947' in Mushirul Hasan (ed), India's Partition.

[fn:39] In writing (and then in revising) this paper, I have been much helped by conversations with Sumit Sarkar, Tanika Sarkar, Aijaz Ahmad, Partha Chatterji, Alan Montefiore, Sugato Bose, Isaac Levi; Carol Rovane, David Bromwich, Stephen White, Gyan Prakash, Ravinder Kumar, Kumkum Sangari, Rajeev Bhargava, Javeed Alam, Garrett Deckel, and Zoya Hasan. Comments from members of audiences at Bombay University, the Nehru Library at Teen Murti in Delhi, Centre of Social Science Studies in Calcutta, Institute of Advance Studies in Shimla, and the conference on 'Multiculturalism and Governance' at Kasauli have also been helpful. A number of the themes of this paper are discussed in much greater detail in my forthcoming book Politics and the Moral Psychology of Identity (Harvard University Press and Oxford University Press, India).
