#+TITLE: Actual Justice Warrior is an Insane Racist Freak
#+INCLUDE: ~/org/blog/politics/header.org

* Introduction
In response to the controversy regarding Banko Brown, Actually Deranged Racist Freak (a.k.a Actual Justice Warrior) DE-cided to embellish the recorded events surrounding the incident. I posted a twitter thread about it, but I will post the contents of the thread in this block and link it for posterity sake.


* Tweet Thread
#+begin_export html
<blockquote class="twitter-tweet" data-theme="dark"><p lang="en" dir="ltr"><a href="https://twitter.com/IamSean90?ref_src=twsrc%5Etfw">@IamSean90</a> 🧵You should take down the video where you claim that Banko Brown &quot;decided to lunge at the security guard with a knife,&quot; and paint Brown as an attempted murderer.<a href="https://t.co/O5j4nkWbHN">https://t.co/O5j4nkWbHN</a><br><br>You said that Brown, &quot;drew a knife,&quot; and that, [1/22]</p>&mdash; Josh Coder (@JoshCoder) <a href="https://twitter.com/JoshCoder/status/1653962352167976962?ref_src=twsrc%5Etfw">May 4, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export


* AJW's Interpolation
You should take down the video where you claim that Banko Brown "decided to lunge at the security guard with a knife," and paint Brown as an attempted murderer.

#+begin_export html
<div class="video-container">
<iframe class="video" src="https://www.youtube.com/embed/I8jDoHymRBI?start=558" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export


You said that Brown, "drew a knife," and that, "the security guard did not pull the trigger at the moment the knife was presented," but this isn't even supported by your OWN SOURCE THAT YOU SHOW ON SCREEN WHILE YOU SAY IT.


#+begin_export html
<div class="video-container">
<iframe class="video" src="https://www.youtube.com/embed/I8jDoHymRBI?start=535" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
#+end_export

Contrast what you said with your own source:

#+begin_quote
AJW: "Banko decided to lunge at the security guard with a knife".

Source: "Brown threatened to stab Anthony."
#+end_quote

Now ask yourself this, can one threaten to stab someone without actually possessing a knife? Yes. Obviously.

Contrast again what you said with your own source:
AJW: "Banko decided to lunge at the security guard with a knife".
Source: "According to the [aforementioned anonymous] source, that is when Brown approached Anthony, who fired his gun."

Now ask yourself, can one "approach" without "lunging" with a knife? Again, Obviously yes.

One wonders then where on earth you got this interpretation. The only reasonable thing to conclude is that you're a racist freak and that's what explains your interpolation. How is it racist? Well, if a black person threatens to stab someone, you conclude they must have a knife even though that wasn't mentioned. If a black person "approaches" someone, they must be "lunging" in your eyes.

It gets even worse than this. Here are several sources contradicting your claim, which you clearly didn't research whatsoever:

#+begin_quote
"[District Attorney Brooke Jenkins] says there's no indication brown was armed."
[[https://youtu.be/oBCjyLECsJo?t=40][- ABC7 News Bay Area]]
#+end_quote

#+begin_quote
"However, [District Attorney Brooke] Jenkins noted that the only weapon found in the incident was the gun used by Anthony."
[[https://www.cbsnews.com/sanfrancisco/news/banko-brown-fatal-shooting-san-francisco-walgreens-security-guard-no-charges/#:~:text=However%2C%20Jenkins%20noted][- CBS News]]
#+end_quote

#+begin_quote
"Investigators tell us that there was no weapon displayed, but that this 24 year old threatened to stab the guard."
[[https://youtu.be/RPploAgIdHA?t=155][- KTVU FOX 2 San Francisco]]
#+end_quote


* A Good Explanation
Now that there's contradictory evidence to your claim, one has to wonder, once again, why did you eisegete what you did into the text? One explanation, and a good one at that, is that you're a DE-ranged racist freak. You might wonder what makes it a good explanation. Well, from your other video thumbnails and titles, you can tell it's very important to you to point out the race of victims of crimes when they're white and their victimizers are black. For example "BLM Activist FRAMES White Girl" and "White Family Targeted Media Silent," but defend white people who kill black people like "The Ralph Yarl Hoax." This is the evidence that confirms the hypothesis that you racistly interpolated stuff into a source you cited because you're a psychotic racist freak.

The other interpretation is that you lied. You knew exactly what you were doing and you just lied. But why would someone lie about this? Well, Brown was black and you're a racist freak, is a good explanation for that.

To be fair to you, although I don't know why anyone would be fair to a psychotic racist freak, you might retort that all of the source that contradict the idea that there was a knife were all posted after the article you posted. Indeed, the last source was in fact a video published 2 hours after your video. I don't however, think this makes your case any better. What this signifies to me is that you were so eager to spew psychotic racist rhetoric that you didn't even want to sit on your insane eisegesis for a few days to see if any new evidence came to light. Instead, read it, pushed record, and didn't even think to update the recording in the subsequent days prior to its release.

This is however /*/TOO/*/ charitable as one of your other two sources came out only a day before your video as did the two sources I posted that demonstrate there was no knife to the best of our knowledge.

Another thing I find bizarre about your video is you claim that you didn't know Brown's gender. I wasn't even searching for the gender, and I found several sources saying Brown was a transman... including IN THE DESCRIPTION OF ONE OF YOUR SOURCES!!! It reads: "A vigil was held Friday night to remember Banko Brown, a man killed in a shooting at a Walgreens in San Francisco"
https://youtu.be/b1Yzx1FBqac

I just can't believe you'd be confused about this. Jesus, you really are just a lazy racist moron.

The worst part of all this is if you weren't so insane, you could have been a little bit more covert with your racism and made essentially the same argument you're making. In several of these sources the DA makes it clear that the video footage shows that Brown was violent, thus justifying the self-defense adjudication. That means  you didn't have to be insane and interpolate or blatantly lie, whichever it was you did, in order to make your point. You could have gone the much more dog whistly approach, but instead just DE-cided to make shit up either because your DE-lusional racist brain read word that weren't there or you were just so racist you had to lie.

Just as a bonus, I searched "little mermaid" on your channel home page. How could I have possibly guessed that I'd find your "commentary" on it? 🤔🤔🤔🤔🤔
