#+TITLE: The Logical Problem Of Evil Is Unassailable
#+DESCRIPTION: Notes on the Logical Problem Of Evil Dialectic
#+AUTHOR: Josh
#+INCLUDE: ~/org/blog/philosophy/header.org

#+begin_quote
  Good is /opposed/ to evil in such a way that a being who is wholly good eliminates evil as far as he can.
  - J.L. Mackie
#+end_quote

There is a quote that is falsely but nevertheless frequently attributed to Dostoevsky: "If there is no God, everything is permitted." It's meant to convey the sentiment that moral facts are somehow dependent on God's existence. Never minding any error theoretic concerns one might have for rejecting this claim at the outset, I will show that the exact opposite of the conveyed sentiment is true. If God exists, everything is permitted.[fn:1]

* Descriptive Evil

As emphasized in the J.L. Mackie quote above, my argument from evil rests on only a single assumption: /Good is opposed to evil/. That said, the argument doesn't require that evil be a normative notion. To give an analogy, imagine a perfectly effective chair-prevention machine. In every world this chair-prevention machine, it spans all of spacetime and prevents chairs from every coming into existence. This is what it means for this chair-prevention machine to be opposed in a non-normative sense to the existence of chairs. Any time in these worlds a chair is about to be produced, as long as the chair-prevention machine at that time, it will prevent that chair by whatever means it has. If there are chairs that exist prior to the machine existing, they will be destroyed immediately conditional on the existence of the machine. Remember, this machine is perfectly effective.

Perhaps my interlocutor will say that this notion of opposition begs the question. After all, it becomes fairly trivial to how to construct the argument from this notion. This notion implies the following conditional is true:

<<premise-1>>
 1. If God[fn:2] exists, then evil does not exists.

Taking [[premise-1][1]] into consideration, we can easily assume the existence of God and Evil to derive the contradiction.

** Argument 1

<<premise-2>>
2. [@2] God Exists.
3. Evil Exists
<<premise-4>>
4. [@4] God does not exist. [1,3 modus tollens]
5. God exists and God does not exist. [4, 3 conjunction]
6. Evil does not exist [1,2 modus ponens]
7. Evil does not exist and Evil exists [3,6 conjunction]

But let us examine the other option as I see only one. At the very minimum, there has to be some sense in which good is /inconsistent/ with evil. The robust notion outlined above certainly meets that criterion, but what other option is there? Well, one might say that the other option is that good is in no way itself evil. /i.e./ if something is perfectly good it is in no way evil. One way of thinking about this is by analogy with color. Something cannot be completely red and also green in any way. Likewise, something cannot be perfectly good and evil in any way and vice versa. The unfortunate consequence of this view, however, is that God's existence is perfectly compatible with everything besides God being evil.

Here will be the only time I go into examples of paradigmatic instantiations of evil only because I don't think the what counts as an exemplar of evil is particularly relevant to the conceptual scaffolding that causes all the issues, /i.e./ kittens may as well be evil and it makes no difference to the argument. That said, the Holocaust is widely regarded as such an example. The view outlined above commits one to saying God's existence is perfectly compatible with the equivalent of the Holocaust happening at every moment since the beginning of time and endlessly into the future without any of the compensatory goods purported to have come from the Holocaust in this world. a world where no one has ever sinned and is thereby innocent suffering unending torture and agony realized to its greatest possible extent for all time is compatible with Gods existence.

This route, although technically consistent under my assumption, obviously comes at great cost and I view it as a type of conceptual reengineering meant only to avoid the conclusion of the logical problem. It's similar to defining evil as any set of innocuous objects like tables and chairs. After all, presuming God is essentially not a chair, those things are also opposed to God in this way and no one rendering the argument is arguing as the content of their argument that God is inconsistent with the existence of tables and chairs (even if it turns out such is a consequence of these arguments). I'm therefore inclined to dismiss this response as question-begging. Even if I'm wrong about this, consider the bullets we've bitten just to get to this point.

 * Evil is a descriptive notion. It's therefore unclear how it's relevant to morality at all.
 * God is compossible with everything else besides God being evil however it's cashed out.

* Normative Evil

Things worsen when evil is considered a normative notion. While I don't think the inference structure from above fundamentally changes if we're using a normative notion of evil, /i.e./ it's still the case on the normative notion that since good is opposed to evil, if God exists, there is no evil, a unique problem arises exclusive to this notion.

Normativity relies on there being a trifold distinction in place: all actions or states of affairs are either merely permissible, obligatory, or impermissible. Merely permissible means neither obligatory nor impermissible. Obligatory and impermissible are the inverse of each other. If some action or state of affairs is obligatory, it is impermissible to refrain from taking said action or refrain from acting to bring out that state of affairs. If some action or state of affairs is impermissible, it is obligatory to refrain from acting in such a way or such state of affairs must be prevented or ceased as soon as possible[fn:3]. This distinction applies to all normative domains. As such my argument will be normativity-type agnostic[fn:4].

Using these concepts, the issue should become immediately apparent. If evil is to be understood in any way as impermissible, then it ought not be allowed. Given that God is perfectly efficacious and perfectly good, see that some action or state of affairs ought not be allowed, he would prevent it. As such, no evil would exist.

No responses to this problem I'm raising work, and all of them turn on the same error, which I will call the compensatory goods[fn:5] error. The reason none of these responses work is because in order to do so, they /divest evil of its normative character/. As is implied by their name, these compensatory goods only compensate by effectively /nullifying/ any normative force the connotation of evil has. Because of these goods, it's no longer the case that these purportedly evil actions /ought not/ be taken nor that these purportedly evil states of affairs /ought not/ obtain. The effect is that the distinction collapses between that which is impermissible and permissible.

We can create the following argument:


** Argument 2
<<premise-8>>
8. [@8] If God exists, there's no distinction between that which is evil and that which is merely permissible.
9. If there's no distinction between that which is evil and that which is merely permissible, then evil does not exist.

We then derive [[premise-1][1]] via hypothetical syllogism.

10. [@10] If God does not exist, then evil does not exist. [8, 9 Hypothetical Syllogism]

At which point, inferences [[premise-4][4-7]] follow from assumptions [[premise-2][2-3]].


* Responses

** Question Begging
Following this, I may be again accused of begging the question. After all, why would someone who believes God's existence is compatible with evil agree to [[premise-8][8]] without already believe that no God exists or that No evil exists?

Let's look at how we arrived at [[premise-8][8]]. I first said that compensatory goods divest evil of its normative character, but why would I say this? The simply answer is why else would God allow it? Pick your compensatory good be it free will or soul-building--defense or theodicy.

* Definitions
*** Omipotence
+ A property of an agent whereby the agent can do any logically possible action.

*** Omnibenevolence
+ A property of an agent whereby the agent exemplifies no evil properties.

*** Omniscience
+ A property of an agent whereby the agent knows all knowable propositions and believes no false propositions.

*** Evil
**** Normative Notion
+ The normative conception of evil is just understood as something which one ought not bring about.
+ Evil properties are properties of states of affairs that ought not be brought about.
**** Non-normative Notion
+ The non-normative conception of evil is understood as inconsistent with good.
  + e.g. A perfectly effective chair destroying machine, /i.e./ a machine that destroys chairs the moment they come into existence, is not consistent inconsistent with chairs existing.

* The Argument

1. If evil is understood as a state of affairs that ought not be brought about and God is understood as an omnipotent, omniscient, and omnibenevolent being, then He would prevent or eliminate evil.

2. Evil is understood as a state of affairs that ought not be brought about and God is understood as an omnipotent, omnicient, and omnibenevolent being.

3. Therefore he would prevent or eliminate evil.

4. If God exists and he prevents or eliminates evil, there is no evil.

5. God exists. (assumed from traditional theism)

6. There is no evil.

7. There is evil. (assumed from traditional theism)

   + Reductio ad absurdum.

* Responses
** Free Will Defense

* Footnotes

[fn:1] Although perhaps trivial, I will show that even if there's a descriptive, substantive way of cashing out evil on a normative error theory, the sentiment is true that if God exists, everything is permitted.

[fn:2] God here is understood as perfectly efficacious, all knowing and wholly good. In this way we can see how God is analogous to the perfectly effective chair-prevention machine.

[fn:3] There are further distinctions often made here, but they're entirely irrelevant. One such distinction is so-called supererogatory goods---goods which are said to be so without being obligatory. In this context this distinction makes no sense as goodness is being understood normatively. When goodness is not obligatory, it removes the normative character of goodness. /I.e/, it makes it the case that goodness is no longer some action one /ought/ to take nor is it a state of affairs that /ought/ to obtain. As such, this conception of goodness is vulnerable to the arguments made in the first section on [[Descriptive Evil]]

[fn:4] Certainly, the most widely relevant type of normativity likely to be relevant to this discussion is a categorical normativity, /i.e./ actions which one ought or oughtn't take or states of affairs which ought or oughtn't obtain without qualification. Whether moral norms can be reduced hypothetical norms or if there's some new type of normativity will be irrelevant just so long as there's some sort of precedence relation between the norms, /e.g./ categorical norms take precedence over hypothetical when in conflict. Such precedence will be necessary to keep the view minimally consistent. Without that, when norms come into conflict, it would commit one to a contradiction with respect to which action they want to take. /e.g/ it's hypothetically imperative that I hit a pedestrian on my way to work so as not to be late, but it's categorically imperative that I not hit a pedestrian. Without a precedence relation, I both ought to hit the pedestrian and it's not the case that I ought to hit the pedestrian.

[fn:5] Compensatory goods are understood as goods which are said to compensate for the supposed evil.
