#+TITLE: IN DEFENCE OF SOCIALIST PLANNING
#+AUTHOR: Ernest Mandel
#+INCLUDE: ~/org/blog/politics/header.org

In his book The Economics of Feasible Socialism Alec Nove criticizes the methods of Marxist economics, as misleading or irrelevant for the task of building socialism, and rejects the goal of Marxist politics---socialism without commodity production---as impossible of realization. Any effective answer to his objections must follow the same procedure that Marx employed in his study of the emergence of capitalism. In other words, it should not start from an ultimate ideal or normative goal to be achieved, but rather from the elements of the new society which are already growing within the womb of the old---from the laws of motion and inner contradictions of the capitalist mode of production and of existent bourgeois society. What has been the basic historical trend of capitalist development, from the Industrial Revolution onwards? A growing objective socialization of labour. All the interconnected laws of motion of the capitalist mode of production---the constant search for increased intensity and productivity of labour in the work-place; the relentless pursuit of new markets; the pressure to labour-saving technological change (rise in the organic composition of capital); the growing concentration and centralization of capital; the tendency of the rate of profit to decline; the outbreak of periodic crises of over-production and over-accumulation; the remorseless trend towards the internationalization of capital---all these together issue into this one end-result.

* 1. Objective Socialization of Labour
What does the objective socialization of labour mean? In the first instance it signifies the growing interdependence of both work-processes themselves and of the choice and production of the goods we consume. Such interdependence involved at most a few hundred persons for the average inhabitant of a European or Asian country in the fourteenth century. Today it embraces literally millions of people. But objective socialization of labour also betokens something yet larger. For what it implies is a dramatic extension of the planned organization of work. Inside the factory, once industrialization gets under way, it is not the market but planning which reigns supreme. The larger the factory, the greater the scale and volume of such planning. With the emergence of monopoly capitalism, planning reaches out from the factory to the firm---that is, in the modal cases, to multi-factory institutions. With the development of transnational corporations in the contemporary world, planning has become international---often indeed, juridically speaking, multi-firm in scope.

The consequence of this secular process has been a radical reduction in market-allocated labour under late capitalism, as compared with directly-allocated labour. The principal reason for this decline in market allocation of labour is not to be found in growing public intervention in the economy, or the emergence of the welfare state, or the conquests of working-class struggle---although all of these have contributed to the end-result. It lies in the inner logic of capitalism itself, and its peculiar dynamic of accumulation and competition. Of course, directly allocated labour can be accompanied by monetary book-keeping---as it is in the bureaucratized planned economies of the ussr, China or Eastern Europe. But this does not make it identical to market allocation. When General Motors has the spare parts of its trucks manufactured in factory X, the vehicle bodies in factory Y, and the assembly performed in factory Z, the fact that computer print-outs containing monetary cost calculations of the most minute type accompany the transport of the spare parts does not mean in any way that plant X ‘sells' spare parts to plant Z. Sales imply changes in ownership, and with it an effective fragmentation of decision-making reflecting a real autonomy of property and financial interests. It is not the market but the planned target of truck output which determines the number of bodies to be manufactured. The body-building plant cannot ‘go bankrupt' because it has delivered ‘too many' units to the assembly plant.


Naturally, a capitalist market economy still rules in the sense that all these processes are typically limited to the stage of intermediate goods---that is, goods before they reach the final client (we say client rather than consumer here, because that client can also be another factory buying machines or the state purchasing arms). But its operation now has resort more and more to non-market mechanisms, not only in the sphere of production but of circulation. The fact that this economic socialization of labour under capital is accompanied by and intertwined with the growth of political forms of non-market labour allocation only makes the contradictions of the whole process yet more explosive.

** /‘Planning'/

We have been using the term ‘planning'. But the concept itself needs to be more precisely defined. Planning is not equivalent to ‘perfect' allocation of resources, nor ‘scientific' allocation, nor even ‘more humane' allocation. It simply means ‘direct' allocation, /ex ante/. As such, it is the opposite of market allocation, which is /ex post/. These are the two basic ways of allocating resources, and they are fundamentally different from each other---even if they can on occasion be combined in precarious and hybrid transitional forms, which will not be automatically self-reproducing. Essentially they have a different internal logic. They generate distinct laws of motion. They diffuse divergent motivations among producers and organizers of production, and find expression in discrepant social values.

Both basic kinds of labour allocation have existed on the widest possible scale throughout history. Both are therefore quite ‘feasible'. Both have also been applied in the most variegated fashions, and with most diverse results. You can have ‘despotic' planning and ‘democratic' planning (those who deny the latter have never looked at a pre-colonial Bantu village). You can have ‘rational' planning and ‘irrational' planning. You can have planning based on routine, custom, tradition, magic, religion, ignorance---planning rules by rain-makers, shamans, fakirs and illiterates of all kinds. Worst of all, you can have planning directed by generals; for every army is based on an /a priori/ allocation of resources. You can likewise have planning organized in a semi-rational way by technocrats or, at the highest level of scientific intelligence, by workers and disinterested specialists. But, whatever their forms, all of these involve direct /a priori/ allocation of resources (including labour) through the deliberate choice of some social body. At the opposite pole is resource allocation through objective market laws that /a posteriori/ counteract or correct previously fragmented decisions taken by private bodies, separately or autonomously from each other.

Similarly, market economies in the sense of /ex post/ allocations of resources have historically existed in the most variegated forms. In principle, there could be market economies with ‘perfect' free competition: though in practice this has hardly ever been realized. There can be market economies skewed by the dominance of powerful monopolies able to control large sectors of activity and so to fix prices over long periods. Markets can coexist with drastic forms of autocracy and despotism---as they did under eighteenth-century absolutism, nineteenth-century tsarism, not to speak of various sorts of military junta or fascist dictatorship in the twentieth century. But they can also be combined with advanced forms of parliamentary democracy, as they have been in the latter half of this century---if in less than twenty countries out of the one hundred and fifty or so that comprise the capitalist world.

Market economies may worsen the misery of broad masses, by an absolute lowering of their standard of living, as they did in most countries of the West for much of the eighteenth and nineteenth centuries, in Eastern Europe extending far into the twentieth century, and as they still do for at least half---if not more---of the inhabitants of the Southern hemisphere. They may also, in other circumstances, preside over significant rises in the average standard of living of the majority of the population, as they did in the West in the thirty years preceding World War I and the quarter of a century following World War II. But in all these contrasted cases it is still the market principle---that is, an /a posteriori/ allocation of resources determined by sales and revenue (under capitalism: profit)---which governs.

Historically, market economies reached their peak extension during the transition from petty commodity production to the initial phases of relatively small-firm capitalism, in the laissez-faire world of the mid-nineteenth century. Thereafter pure market principles of allocation entered into increasing collision with the exigencies of rationally planned production inside the large factory and the large firm. Engels formulated that contradiction strikingly in a famous passage in the /Anti-Dühring/: ‘The greater the mastery obtained by the new mode of production over all decisive fields of production and in all economically decisive countries, the more it reduced individual production to an insignificant residuum, the more clearly was brought out the incompatibility of socialized production with capitalistic appropriation . . . The contradiction between socialized production and capitalistic appropriation now presents itself as an antagonism between the organization of production in the individual workshop and the anarchy of production in society generally.'[fn:1] We have ourselves argued in /Late Capitalism/ that a more general law of motion of bourgeois society as a whole (social superstructures as well as social basis) can be deduced from this basic antagonism: to wit, the contradiction between capitalism's simultaneous tendencies towards partial rationality and global irrationality.

The two different systems of resource allocation are structurally related---indeed largely identical---to two contrasted ways of adapting output to needs. For every human society is in the last analysis oriented towards consumption---since without the consumption of producers (that is, the reproduction of their labour-power) there would be no output, labour or human survival at all. Now, there are only two basic ways of adapting current output to needs. Either these needs are taken as given at the outset, as assessed /ex ante/ by whatever is the dominant social body, and output is organized to satisfy them. Or else they are deemed to be unknown or at any rate uncertain, and the market is supposed to reveal them /ex post/ through the expenditures of ‘effective demand'.

** The Current Mood

After the Second World War, that demand was itself regarded by conventional bourgeois wisdom as to some extent subject to public shaping and intervention, in the epoch of counter-cyclical economics and welfare politics. But in the past decade there has been a sharp reaction against Keynesian ideas and techniques in the capitalist world, and an unbridled rehabilitation of the market and of commodity production as civilizational values in themselves. This change has had a deep influence on the Left as well. Today the whole body of socialist thought---which is older than Marx, but to which he gave scientific and systematic expression---that represents a critique of commodity production and of the market /per se/, and a profound historical demystification of the set of theoretical assumptions that descend from Hobbes, Locke and Smith, is in danger of being indiscriminately thrown over-board. For it is not just conservative academics or politicians but increasing numbers of socialists, above all many left social-democrats and Eurocommunists, who are now rediscovering and reincorporating into their social thought bourgeois axioms which have no scientific or empirical standing whatsoever: which are simply articles of blind faith and superstition. The logical---and widespread---conclusion of this shift of opinion is a disbelief in the very possibility of conscious planning, and an acceptance---if not cult---of the market which strikes at the very heart of the socialist cause. The real stake of current debates is not the short-term issue of how far reliance on commodity exchange is necessary in the immediate aftermath of an anti-capitalist revolution, but whether the long-term goal of socialism itself---as a classless society that may take a century to build---is worthwhile realizing at all, and why it is worth realizing. That was the fundamental issue for the line of thinkers that stretches from Babeuf and Saint-Simon to Engels and Luxemburg, and it remains the central question for us today, as we read Alec Nove's /Economics of Feasible Socialism/.

This brings me to a difficulty which confronts any attempt to respond to Alec Nove and other advocates of ‘market socialism'. They wish to analyse and correct the serious malfunctioning of the transitional economies in the Soviet Union, Eastern Europe and China, and in itself this is a legitimate and necessary preoccupation. We do not believe that these societies are in any meaningful sense socialist. Nor do we believe that socialism, as defined by Marx, is around the corner in these countries; in none of them is the radical suppression of residual market relations presently desirable or practical. But the whole thrust of Nove's book is to argue that ‘Marxist socialism', as classically defined, is not on the agenda anywhere and was a utopian project right from the outset. In other words Nove's argument relates not only to the period of transition, with its specific economic problems, but to the very nature of socialism. Evidence culled from the experience of the Soviet Union, with all its historic burden of backwardness, war devastation and bureaucratic misrule, is used to lend weight to classical arguments against socialist planning as such. The question should be asked: are not the particular problems of Soviet-type economies partly due to immature conditions for generalizing socialization? By contrast, I believe that it can be shown that there are objective tendencies in the most advanced countries which indicate the presence of the material, technical and human resources needed for planning; and at the same time these advanced societies also show the heavy cost that is paid for the absence of planning. Surely any realistic programme for tackling mass unemployment, the super-exploitation of women workers or ethnic minorities, or the vast problems created by the ecological irresponsibility of corporations and governments, will have to be based on the establishment of quite new social priorities by means of genuine socialization and democratic planning. Marx himself did not reject commodity production (‘market economy') for socialism just for reasons of economic efficiency---or out of blind faith in the proletariat. It would be quite wrong to dismiss the formidable corpus of socialist tradition which culminates in his writing simply because this body of work is also invoked in a misleading way by the Soviet advocates of bureaucratic centralization. To do so would be as misplaced as to reject the principles of human rights under the pretext that reactionary capitalists invoke these principles too.

** Too Many Decisions?
Let us now turn to some of the central objections that Alec Nove raises against what he takes to be the classical Marxist conception of socialist planning. Basing himself on his undoubted knowledge of the Soviet economy, he argues that there are probably about twelve million different goods under production at any given time in the ussr, and that only the market could ever perform the function of allocating these rationally---the number of decisions to be made is simply too great to be handled by any kind of democratic association of the producers.[fn:2] What are we to make of this argument? Let us first clear up an ambiguity in it. Nove's figure includes an immense number of intermediary goods and spare parts, as well as specialized kinds of equipment, which the ordinary citizen never encounters and never consumes. It also covers a great many variants of the /same/ consumer good. In Western societies these will range from ten different types of detergent to thirty varieties of bread, and so forth. Normal people will usually consume only one or two of such variations, not all of them. An awareness of this is important for circumscribing the difficulty with which Nove is concerned. For it is not in fact the case that the market in the advanced capitalist countries ‘allocates' millions of commodities---either consumer or producer goods. In the worst of cases, private consumers may purchase a few thousand different goods in the course of their whole life-cycle (even that would be an exaggerated estimate for many of them). They have no time to consume ‘millions' of different goods or to respond to ‘market signals' in ‘choosing' them. The notion---cherished by liberal economists and in his day by Stalin---that there exist ‘unlimited needs of consumption', whose satisfaction requires an ‘unlimited number of goods', is just plain silly. You cannot consume an unlimited number of goods in a limited time, and unfortunately our stay on earth is definitely limited!

The situation does not change substantially if one looks at producer goods (including intermediate products). The bulk of intermediary goods, as we have already noted, are not allocated through the market at all. They are made to order. This is obvious enough. But---what is less often noticed---the same is true of most larger machines today. You don't go shopping in supermarkets for hydroelectric dam turbines; you order them with very precise and minute specifications. Even if this is done through public tender, it is not at all the same thing as ‘market allocation'. The various tenders have not led to different products actually being made, between which you choose. They have led to only /one/ product actually being manufactured, which is /automatically/ used. The same procedure can obviously be followed without any market mechanism being introduced. Instead of rival tenders, you would calculate different product costs in differing producing units, and opt for the cheapest supplier, provided all quality and technical specifications were respected.

We thus arrive at a rather startling conclusion. /Already today/, in the most advanced capitalist countries, the bulk of both consumer and producer goods are not produced in any way in response to ‘market signals' shifting violently from year to year, let alone month to month. /The bulk of current production corresponds to established consumption patterns and predetermined production techniques that are largely if not completely independent of the market./ How has this come about? It is precisely a result of the growing objective socialization of labour.

Why can't the problem of allocating the resources needed for those products which are by and large known in advance be solved by the associated producers, with the help of modern computers which can certainly handle the ‘millions of equations' Nove finds so daunting? Of course, it is true that consumer habits are not immutable. Long-term changes in technology can radically transform the dominant product mix of consumer goods, as well as the ways of producing them. A century ago horse-drawn carriages and all their equipage were standard items of production. Today motor-cars have replaced them, with all their consequences (gasoline, highway construction, spare parts, and so on). A hundred years back, hardly any cement, steel or glass, and no aluminium whatsoever, went into house-building. Nowadays wood and brick play a much lesser part in the construction of most people's homes.

But changes of this kind only occur on a massive scale in the long run. Moreover, /the initial push towards them never comes from the market or the consumer/. It comes from the innovator and the associated producing unit. There were not ten thousand consumers desperately running round wringing their hands and shouting: ‘Dear Henry Ford, give us automobiles! Dear friends of Apple Corporation, please supply us with personal computers!'. There were businesses (innovating ones, indeed! Marx pointed out the need for constant technological change and innovation, induced both by inter-capitalist competition and class struggle between capital and labour, more than half a century before Schumpeter) launching new products on consumers to create the necessary demand for selling as many of their wares as possible.

* 2. Scarcity and Plenty

The problem of the sheer complexity of allocation in an advanced industrial economy is thus in large measure an illusory one, as presented by Nove. No one would deny that democratic socialist planning will confront its own practical difficulties, some of which can readily be foreseen and others for the moment less so. But there is no reason to suppose that these would be insuperable in the technical sense Nove suggests. His critique of the Marxist conception of socialism, however, is not confined to methods it proposes for the construction of a classless society, but extends to its definition of the goal itself. For the premise of abundance, on which Marx's idea of communism was founded, is---Nove contends---irredeemably utopian. Here is what he has to say on the subject: ‘Let us define abundance as a sufficiency to meet requirements at zero price, leaving no reasonable person dissatisfied or seeking more of anything (or at least of anything reproducible). This concept plays a crucial role in Marx's vision of socialism/communism. Abundance removes conflict over resource allocation, since, by definition, there is enough for everyone, and so there are no mutually exclusive choices . . . There is then no reason for various individuals and groups to compete, to take possession for their own use of what is freely available to all. Let me give as an example the supply of water in Scottish towns. Evidently, it is not costless: labour has to be expended on building reservoirs and pipes, purification and repair and maintenance and so on. However, there is plenty of water. It is not necessary to regulate its use through “rationing by price”, it is available in sufficient quantities for all purposes. It is not “marketed” in any meaningful sense, nor is its provision subject to any “law of value” or profitability criterion. There is no competition for water; there are no conflicts over water . . . If other goods were as easily and freely available as water is in Scotland, then new human attitudes would develop; acquisitiveness would wither away; property rights, and also crimes related to property, would also vanish.'[fn:3]

** Nove's Non-Sequiturs

There are a whole number of non-sequiturs in this key passage. Nove begins by telling us that ‘abundance' means absence of conflict over resource allocation. But he then quietly reduces ‘resource allocation' to consumer needs. For, of course, there would not be ‘plenty' of water in Scotland if fifty power-stations started to operate there. In other words, Nove makes the silent assumption that /what is ‘plenty' is determined by current local consumer needs/, and only by them, other things remaining equal. Or, to put it another way, he takes existing consumer habits (and production patterns) /for granted and for permanent/. But he does not make this premise explicit. For to do so Would undermine his initial claim that abundance is impossible and Marxian socialism unfeasible.

There is a further contradiction in the argument. On the one hand, Alec Nove notes that to keep ‘plenty of water' for the inhabitants of Scotland, labour has to be expended on pipes, reservoirs, maintenance and so on. Now labour is ‘relatively scarce'. The same labour that is invested in water pipes or reservoirs could be spent on any number of alternatives---building golf courses, power-stations or even missiles. Yet mysteriously, in spite of the general inevitability of ‘conflict over resource allocation', water can be distributed ‘free of price' in Scotland, and no conflict apparently arises over the allocation of labour involved. So the connection Nove, together with innumerable other economists, not to speak of sociologists and misanthropic philosophers, postulates between /overall/ scarcity of resources and /specific/ patterns of human behaviour is just empirically unproven---to put it no stronger. For the example itself demonstrates that it is perfectly possible for people to behave in a non-acquisitive way towards particular goods, in particular circumstances, provided a certain number of conditions are fulfilled.

What are these conditions? Why is it that ‘rationing by price' is unnecessary in the case of water consumption by Scottish citizens? Surprisingly, Alec Nove does not mention the obvious economic reason, although it is one over which Marxist and liberal economists would have no difficulty in agreeing---and which immediately explains why the same does not apply to potential multiplication of power-stations in the region. It is because /the marginal elasticity of water demand has become zero or even negative for the average private consumer/. There is probably some slight ‘waste' as a result of water being supplied free of charge. But that wastage is less than the ‘cost of pricing' this particular good (installation of meters, employment of control personnel, sending of bills, and so on). It simply doesn't pay to price water under these circumstances. Stable, foreseeable (tendentially declining) demand is the key operative empirical datum. All the rest flows from that.

But if water in plenty is conceivable amidst surviving scarcity of overall resources, why can't the same apply to other goods and services in similar circumstances? Can it really be that Scottish water is the only good for which elasticity of demand has become zero or negative? This is where Marx's ‘vision of socialism/communism' comes into its own. For with the advance of social wealth, the growth of productive forces and the emergence of post-capitalist institutions, the number of goods and services characterized by such inelasticity of demand, and thereby capable of being distributed free of charge, can progressively increase. When---let us say---up to 60 per cent or 75 per cent of all consumer goods and services are so allocated, this cumulative increase will have altered the overall ‘human condition' dramatically.

There is another /petitio principi/ slipped casually into Nove's conclusion. There he seems to be suggesting that ‘property rights' follow ineluctably from ‘scarcity'. But, of course, for scarcity to generate such rights, specific social institutions enabling, facilitating, upholding and defending private appropriation of the means of production, and cutting the mass of the producers off from free access to them, as well as to the natural basis of their livelihood (land, water and air), have to be created. These in turn will be linked to specific social classes, defending specific interests against other social classes defending other interests. ‘Scarcity' was certainly very real in a traditional Bantu village. But it did not lead to ‘property rights' on the land for thousands of years. So today, if the people of Scotland (or Britain, or Europe, or of a Socialist World Federation) were democratically to decide not to grant property rights to potential investors in hydroelectric energy, no economic law could mysteriously convert publicly into privately owned water, simply as a result of scarcity. They might then have to ‘pay the price' of dearer energy (i.e. a larger expenditure of available material and human resources on energy output) for their preference for plenty of clean, non-priced water for the consumer. But that would be their choice and right, as consumers and citizens.

For the same reasons, it is no less wrong to deduce a generic ‘human acquisitiveness' from scarcity. There is no such thing as general acquisitiveness. Rather inclinations to acquisitiveness are specific, and are related not so much to the scarcity of goods in general, or even to scarcities of particular goods, as to /the relative intensity of specific needs/. A Rolls-Royce is a very nice car. It is also very scarce. Many car drivers (and certainly most auto fans) would like to own a Rolls. But the overwhelming majority of the population is not involved in a mad scramble to get a Rolls. It does not calculate every penny to economize in order to get a ‘scarce Rolls' at any cost. It does not feel ferociously acquisitive about the limousine. It is not neurotically frustrated by knowing that it will never get one. So ‘acquisitiveness' can wither away long before ‘scarcity in general' has disappeared---just as it withered away towards water among the people of Scotland. /It is sufficient that the most intensely felt needs are satisfied, or that a saturation of consumption occurs in these fields/. That is the basic assumption on which Marx founded his vision of socialism. It is a perfectly realistic and conceivable one.

* 3. The Hierarchy of Needs

In responding to Nove's critique of the Marxian heritage, we have introduced the concept of ‘relative intensity of needs'. This notion has several important implications for a discussion of socialist planning, to which we should now turn. In the West today the variable intensity of needs finds expression in differential consumer behaviour towards ‘priced' goods and services (if also ‘unpriced' ones). But it does not have to be measured indirectly in money. It can be empirically ascertained by, for example, studying changes in physical consumption patterns when income suddenly declines (as it has done for vast numbers of people during the present depression). Certain widespread features will then clearly stand out. For some expenditures will be cut before others. Certain varieties of goods within each major category of consumption will be reduced, while others will be increased (more pork and less lean beef will be consumed). Expenditures on health will prove more rigid than on items of toiletry. These are not random preferences. One of the most important advances in knowledge brought about by capitalism---in a sense, it is a compliment to capital---is that because of the rise in the living standards first of the middle classes, and then of wider layers of the population, there are now a great deal of empirical, statistical data on consumption patterns that are remarkably similar across a large number of countries. These reveal an objective order of priorities common to hundreds of millions of people, over many decades. All responsible enquiry into human needs should start from that evidence.

What emerges from any such enquiry is a pattern which the Prussian statistician Engel already noticed one hundred and fifty years ago. Once needs become diversified with economic growth, a definite hierarchy can be discerned among them. There are fundamental needs. There are secondary needs. There are also luxury, or marginal, needs. Roughly speaking---and here we stand ready to be corrected by empirical data, not by metaphysical speculation---we would put in the first category: basic food and drink, clothing, shelter and standard comforts linked to it (heating, electricity, running water, sanitation, furniture); education and health provision; guaranteed transport to and from the workplace; and the minimum of recreation and leisure indispensable to the reconsti-tution of labour power at a given level of work pace and stress. These are the needs which for Marx /must/ be satisfied if an average wage-earner is to continue working at a given level of effort. They can be subdivided into a physiological minimum and a historical-moral supplement. They vary across space and over time. Their fluctuations do not depend only upon major changes in the average productivity of labour. They are also a function of the great shifts in the balance of historical forces between contending social classes. But at any given moment, in any given country, they are objective data---which are also clearly present to the consciousness of the great majority of the population. They cannot be arbitrarily altered (including by the operation of ‘market forces') without violent disturbances in the social and economic fabric.

In the second category of goods and services we would classify most of the more sophisticated foods, drinks, clothes and household appliances (excepting the fanciest ones), the more elaborate ‘cultural' and ‘leisure' goods and services, and private motor vehicles (as distinct from public transport). All other consumer goods and services would go into the third category of luxury expenditures. Of course, the precise frontiers between these three categories of needs are difficult to draw. The first is the easiest to delimit. The gradual passage of needs (and of goods and services fulfilling these needs) from the second to the first category is a function of economic growth and of social progress (in particular of the results of proletarian class struggle). Paid holidays for all are a recent conquest of the working class, dating from the great wave of factory occupations of 1936--37 and its later fall-out across the industrialized world. The distinction between the third and the second category is more a matter of socio-cultural preferences than an observable mass phenomenon.

But while all these points merit emphasis, the general pattern which emerges remains fairly clear. The hierarchy of human needs manifestly has both a physiological and a historical social basis. It is neither arbitrary nor subjective. It can be encountered on all continents, under the most diverse circumstances, albeit in non-synchronous fashion because of the uneven and combined development of economic growth and social progress. This hierarchy of needs is not the result of any /diktat/, either by market forces or by despotic bureaucracies or enlightened experts. It finds expression in spontaneous or semi-spontaneous consumer behaviour itself. The only ‘despotism' involved is that of the large majority. ‘Eccentric' minorities---who for the most part are not so few in absolute numbers---will not fit into the general pattern: teetotallers as against consumers of alcoholic beverages; smokers as distinct from non-smokers; vegetarians as against meat-eaters; people who refuse to look at television or cannot or will not read newspapers or books; others who decline ever to see a doctor or go into a hospital on principle. Nevertheless, given the fact that a very large number of people are concerned---hundreds of millions---the law of averages tends to balance out these exceptions and to maintain across time and space an emergent pattern that testifies to a definite hierarchy of needs among the overwhelming majority of consumers.

This hierarchy has one even more important aspect. Not only does elasticity of demand tend towards zero and into the negative from the top of the priority list downwards, item per item, with each successive stage of economic growth. It also tends to do so by major categories of needs. /Per capita/ consumption of staple foods (bread, potatoes, rice and so on) in the richest industrialized countries is today definitely dropping both in absolute physical quantities and in percentage of national expenditure in monetary terms. So is consumption of native fruit and vegetables and, at least in money values, of basic underwear and socks, as well as elementary items of furniture. Statistics also show that, in spite of growing differentiation of tastes and goods (many varieties of bread and cake, a much greater range of food and clothing generally), the /overall/ consumption of food and clothing and footwear tends to become saturated and even starts to decline, measured in terms of calorie-intakes, square metres of cloth and pairs of shoes. These realities completely refute the bourgeois and Stalinist belief in a limitless growth of the needs of ordinary people. Nothing is further from the truth, as measurable by actual consumer behaviour. Saturation of basic needs is a verifiable trend in the West, not only because of a decline in their intensity once a certain threshold is passed, but also because of a change in motivation. /Rational consumption patterns tend to replace supposedly instinctive desires to consume more and more/. Here what is ‘rational' does not need to be ‘dictated' (/should not/ be dictated) either by market forces or by bureaucratic planners or know-all experts. It emerges from growing consumers' maturity itself, as people's priorities shift and their self-interest becomes more self-aware.

Food consumption provides a telling example of this process. Since time immemorial, humanity has hovered on the brink of famine and starvation. Even in our own century, this has been the plight of the great majority of the population of the planet. Under these conditions, it is only natural that human beings should be obsessed with eating. Five years of acute food shortages in continental Europe during World War II were enough to set off a veritable explosion of gluttony once something like ‘unlimited food consumption' became possible again after 1945 (in some European countries much later). But how long did this spree last? Less than twenty years after food had once again become relatively plentiful (just one generation!), priorities started to shift dramatically. Eating less became the rule, not eating more. Health became more important than satiety. This change was not due to the ‘imposition' of new consumption patterns by doctors or the health industry. It was the instinct of self-preservation that prompted it. Long before the health industry had emerged, similar alterations of outlook were discernible among the rich ‘who had realized socialism for themselves'. Between the obese English or French ruling classes /anno domini/ 1850 and the slender American millionaires of a century later there was quite a gastronomic upheaval. Today, ordinary citizens in the West can take greater pleasure in more diversified meals. They can increasingly enjoy cooking itself as a past-time. But they will still tend to reduce their absolute intake of calories in order to live twenty years longer, instead of dying prematurely of over-eating and hardened arteries.

The consumption pattern of the sick---or valetudinarian---reveals a very similar pattern. That no one would opt to have their limbs or organs removed one by one through surgery just because the latter was free is obvious enough. But the sharp rise in the consumption of patent medicines after the War---like the increase in dental protheses and spectacles after the introduction of the nhs in Britain---was not merely, or even principally, a passive submission to the irresponsible advertising pressures of the pharmaceutical industry. It was essentially the expression of a backlog of unfulfilled basic needs. Once this backlog disappears and a certain threshold of saturation is reached, any careful and thorough campaign of education to show the ill-effects of over-consumption of medicines is likely to be effective. Medicine consumption will tend to balance out, and eventually decline (wealthier social groups already evince this pattern). Indeed it is not excessive optimism to note that systematic public education in the harmfulness of smoking has led to a definite decline in cigarette consumption, all of the tobacco industry's efforts to the contrary notwithstanding.

Two conclusions follow from these reflections. Firstly, as ‘scarcity' is increasingly confined to less essential goods and services, it will be quite possible to reduce the role of money in the economy as a whole, as non-priced goods and services become more numerous than goods and services bought. For the assumption that consumers can only determine their needs indirectly, by the allocation of their money incomes to different goods and services, is absurd. Why should individuals have to take the detour of the monetary form to ascertain what they require? The real situation is obviously the opposite. They want a certain amount of food, clothing or leisure, with particular preferences as to the kinds they like, and then they say to themselves: ‘I have so much to cover these needs, which means that I cannot satisfy all of them, and hence I must make my choices within them.' It is not that they first possess money and then go around saying: ‘Thanks to the cash in my pocket and the shop-windows in front of me, I now understand that I am hungry'! The simplest---as well as the most democratic---way of adapting material resources to social wants is not to interpose the medium of money between the two, but to find out people's needs just by asking them what they are.

Of course, the advanced capitalist countries of today which could together become a socialist commonwealth of tomorrow are composed of millions of different human beings with their own individual tastes and inclinations. In the transition towards socialism, all uniform standardization of output of the kind introduced by capitalism would be tendentially reduced. At a certain point of need-satisfaction---or saturation---there naturally occurs a change from passive to active consumption, and a greater individuation of needs which calls for more creativity in meeting them. By and large, it is likely that /new needs/ would fall into two categories. There will be those that are developed by adventurous and imaginative minorities, eager to experiment with novel products and services. But /mass/ production of new goods would not be automatic as a result of new inventions. It would have to be a conscious choice taken by the majority. Twenty per cent of the population would not have the right to impose the generalization of new goods on all citizens, although they could increase their own work-load to ensure their production. On the other hand, there will also be cases where the majority does opt for a quite new range of goods or services, and a fundamental readjustment of the general plan would ensue to accommodate the new need. In the history of twentieth-century capitalism, such great consumer revolutions have been relatively rare. Three major ones stand out---the motor-car, electrical household appliances, and plastic goods---which have radically changed the lives of hundreds of millions of people. Under socialism, such mass transformations would occur not ruthlessly and anarchically, but rationally and humanely, for the first time at the behest and under the control of those affected by them. commodity production and monetary exchange. At the same time, the intensity of social conflicts can diminish, provided that institutions exist which render the satisfaction of basic needs for all an automatic, customary, self-evident everyday experience. That would provide the subjective basis for the withering away of a money and market economy. For social strife is tremendously violent and bitter when food, land, basic work patterns, elementary education and health, fundamental human rights and freedoms are involved. But there are no examples of millionaires killing each other daily over entry to exclusive Bahamas beaches, or world wars breaking out over Old Masters or even seats on the Chicago Exchange (painful though momentary lack of these may be). Occasional political intrigues, large-scale corruption and even murder may be employed to resolve conflicts over the allocation of these ‘scarce resources'. But such imbroglios are not to be compared with the horrors of the Irish famine, the Great Depression, or the Indian caste-system. If conflicts of the kind generated by starvation, unemployment and discrimination were to disappear, we would have a different world---with other behavioural patterns and other mental structures. If ‘acquisitiveness' were restricted to luxury goods, and competition to a scramble for Cuban cigars, they would be qualitatively different phenomena from what is to be seen today. We do not hesitate to say that such a world would be a better one for 99 per cent of its inhabitants.

** Tyranny over Wants?
Nevertheless, there will be those who resist these conclusions. For as soon as we use the concept of a ‘hierarchy of social needs', in which some claim greater priority than others, a formidable suspicion arises, especially after the experience of bureaucratically centralized---that is, bureaucratically managed and mis-managed---economies in our time. By what right, in the name of whose authority, and with what inhuman results are such ‘priorities' to be imposed on real living human beings? Isn't that the ‘road to serfdom'?

This is an argument which socialists, more deeply devoted to human emancipation---that is, freedom---than the adherents of any other philosophical or political outlook, must take very seriously. But it is important to address it carefully and scrupulously. In a work recommended by Nove, /Dictatorship over Needs/, Ferenc Feher roundly denounces the rulers of the ussr, China and Eastern Europe for exercising a wholesale tyranny over the wants of their populations. The case he makes is a powerful one. But it is also a partial one, that contains a significant contradiction of its own. The source of that contradiction lies in a concept that recurs again and again, in the work not just of Ferenc Feher and Agnes Heller, but of Ota Sik, Branko Horvath, Wlodzimierz Brus and many other advocates of ‘market socialism'.[fn:4] It is no accident that the same notion is to be found equally in the writings of the more theoretically trained and intellectually consistent neo-liberals, not to speak of classical liberals like von Mises, von Hayek or Friedman. The concept in question is that of ‘socially recognized needs'. Now for all these theorists, whatever their other---major---differences, scarcity of resources is the bedrock on which economic theory (/all/ economic theory) must be built. But scarcity of resources automatically implies that /not all/ individual needs /can/ be satisfied. That is the silent premise behind the formula of ‘socially recognized needs': /individual needs are not automatically recognized by society. Only part of them are/. So a consistent individualist should conclude: the formula of ‘socially recognized needs' /implies in all cases a tyranny over individual needs by society/. That will be as true of a market economy as it is of a planned economy. The tyranny is unavoidable. The only question is the specific form it takes, and the socio-political consequences which flow from that form.

** Forms and Consequences

For liberals and market socialists alike, it seems obvious that the despotism of the market---‘rationing by the wallet'---is less painful for the individual and less damaging to personal freedom than the despotism of a plan---or rationing /tout court/. This may well seem plausible if one compares particular extremes in the Northern hemisphere---for example, rationing through income differentials in welfare-state Sweden with rationing by Gosplan decision in Stalin's Russia. But such extremes are historically the exception rather than the rule. If one takes the historical average of capitalist rationing through market relations and income differentials, characterized by great mass poverty and extreme income inequality (the average for the whole capitalist world over the past 150-- 200 years), the conclusion is far from obvious.

The less that basic needs are satisfied by current income distribution, the more indifferent people are to the specific forms which that lack of satisfaction takes. News agencies recently reported a Catholic priest in Santiago as stating that after the latest devaluation of the Chilean peso the city's poor (over fifty per cent of the population!) /could not even buy bread with their money income/. Milton Friedman and his Chicago Boys would have a hard time convincing them that they are ‘freer' than citizens of East Germany who do not suffer from lack of staple foods, whatever the tyranny exercised over their other, less basic needs. Contemporary Africa provides another example of these truths. When famine devastates the Sahel, is there anyone who would condemn food distribution by physical rations to the starving as a ‘dictatorial' allocation reducing them to ‘serfs'---where selling food to them would make them ‘freer'? If a grave epidemic breaks out in Bangladesh, is distribution of medicine in physical form resented as obnoxious compared with its purchase on the market? The reality is that it is much less costly and more reasonable to satisfy basic needs, not through the indirect road of allocation by money on the market, but through direct distribution---or redistribution---of the total resources available for them.

Money and market relations, by contrast, come into their own as instruments for enabling greater consumer freedom to the extent that basic needs have already been satisfied. For consumer freedom implies consumer choice, and confronted with really fundamental needs, the consumer precisely has no choice. You don't normally ‘choose' between bread and a seat in a jet plane, between elementary education and a second tv set, between health care and a Persian carpet. Money as a medium for consumer freedom is efficient only for decisions among what is relatively superfluous---given a high degree of income equality. As a means of determining the basic directions of social resource allocation, it is likely to be both unjust and inefficient.

Of course, if a society democratically decides to give an allocative priority to the satisfaction of basic needs, it automatically reduces the resources available for the satisfaction of secondary or luxury needs. This is the sense in which there is no escape from some ‘dictatorship over needs', as long as unsatisfied wants have not become completely marginal ones. But here is where the merits of the political case for socialism become most obvious. For is it more just to sacrifice the basic needs of millions, or the secondary needs of tens of thousands? To ask this question is not to sanction the frustration of the more sophisticated needs which have developed with the advance of industrial civilization itself. The socialist prospect is one of a gradual satisfaction of more and more needs, not of a restriction to basic requirements alone. Marx was never an advocate of asceticism or austerity. On the contrary, the concept of the fully developed personality that is at the very heart of his vision of communism implies a great variety of human needs and their satisfaction, not a narrowing down of our wants to elementary food and shelter. The withering away of market and money relations envisaged by Marx would involve the gradual extension of the principle of /ex ante/ resource allocation for the satisfaction of these needs to a greater and greater number of goods and services, in a wider and not lesser variety than exists under capitalism today.

* 4. Despotism over Producers

So far we have followed Alec Nove---and other critics of Marxian socialism---in focusing on problems of consumption. But this concern is, of course, in itself a one-sided one. For the average citizens of an advanced industrial country are not only and not even mainly---that is, for the greater part of their adult lives---consumers. They are still first of all producers. They still spend an average of at least nine to ten hours a day, five days a week, working or travelling to and from work. If most people sleep eight hours a night, that leaves six hours for consumption, recreation, repose, sexual relations, social intercourse, all taken together.

Here a double constraint arises, with which the champions of ‘consumer freedom' hardly deal. For the more you multiply the number of needs to be satisfied within a given population, the greater the work-load you demand from the producers at a given level of technology and organization of the labour process. If decisions about this work-load are not taken consciously and democratically /by the producers themselves/, they are dictatorially /imposed/ on them---whether by Stalin's inhuman labour legislation or by the ruthless laws of the labour market, with its millions of unemployed today. Surely any advocate of a juster and more humane society should feel as deeply repelled by this tyranny as by that over consumer needs? For the system of ‘rewards and punishments' through the market, ingenuously extolled by so many on the Left nowadays, is nothing but a thinly disguised despotism over the producers' time and efforts, and therewith their lives as a whole.

Such rewards and punishments imply not only higher and lower incomes, ‘better' and ‘worse' jobs. They also imply periodic lay-offs, the misery of unemployment (including the moral misery of feeling useless as a social being), speed-up, subjection to the stop-watch and the assembly-line, the authoritarian discipline of production squads, nervous and physical health hazards, noise bombardment, alienation from any knowledge of the production process as a whole, the transformation of human beings into mere appendices of machines or computers. Why is it obvious that millions of people should submit to such constraints just for the sake of assuring 10 per cent more ‘consumer satisfaction' to 50 per cent of their contemporaries, or even to only 20 per cent of them? But that is exactly what the market economies /force/ them to do, if they want to escape dereliction or incapacity to take care of their families and themselves! Is that a price worth paying for fundamental alienation in the production process? The least one can say is that the case is far from being proven. Might it not be preferable to forego the Betamax, the second car (perhaps even the first, if adequate public transport were available), the electrical meat-cutting knife, and to work ten hours fewer a week, with much less stress---if the satisfaction of all primary needs were not endangered by such a reduction? Who knows what the producers would decide /if they were really free to make a choice/---that is, if the alternative were not a fall in the satisfaction of their basic needs and a catastrophic increase in the insecurity of their existence?

In a market economy---any form of market economy, no matter how ‘mixed', including the economy of ‘market socialism'---these decisions cannot be taken freely by the producers. They are dictated behind their backs---either by employers deciding for them, or by ‘objective laws' over which they have no control. But there is nothing fatal about this despotism. The presumed emperor here really does have no clothes. There is no compelling reason to prevent the producers of a free community from saying: ‘We are one million. Working twenty hours a week, with twenty million hours spent using a given stock of equipment and observing a given organization of our labour, we are capable of satisfying x basic needs at this stage and for a foreseeable future---no more and no less! We can try, through rationalization of our technology and labour organization, to reduce that work-load in the coming twenty years to sixteen hours a week. We consider /that/ a top priority. There are still additional needs to be satisfied---but we are not ready to work more than five hours a week currently and four hours a week in twenty years, for the satisfaction of these additional needs. So we /fix/ a legal working work of twenty-five hours today and of twenty hours to be gradually introduced in the coming years---even if that implies that some needs will not be satisfied.' By what principles of ‘fairness', ‘justice', ‘democracy' or ‘humanity' are the sovereign rights to decide what time and effort to devote to the satisfaction of consumer needs snatched from the hands of the producers themselves?

* 5. Objective Informal Cooperation

Nove never directly confronts this question. But he would doubtless reply that his book contains a tacit answer to it. For throughout /The Economics of Feasible Socialism/ he argues that, even if the market has its drawbacks, the only alternative to it as a coherent economic organizing force is a powerful centralized bureaucracy. This is one of the leitmotifs of his work. But it is a dogmatic prejudice, which remains quite unproven. In fact, it can be empirically demonstrated that it is becoming increasingly untrue even today, both in the West and the East, before any Marxist form of socialism has been realized. For what Nove has overlooked is that the growing contradiction between the objective socialization of labour and the continued fragmentation of decision-making can less and less be contained either by the market or by centralized bureaucratic planners. What prevents both these clumsy and irrational systems from collapsing is the fact that they are in effect by-passed /by millions of daily acts of objective informal cooperation/.

What do we mean by this? To understand what is at stake here, it is necessary to make an important distinction. Money relations are not simply identical to market relations; for they can be quasi-market or pseudo-market relations. In such cases, the same monetary form conceals quite different real contents. Now a market economy is one that is /guided/ by price fluctuations. The ‘economic agents', be they consumers or firms, /react to market signals/. If no such reaction occurs, then it is hard to prove (unless it is an axiom that needs no proof---i.e. a revealed dogma) that the signal is economically relevant. But what do studies of actual consumer behaviour, including of working-class consumption, in the advanced capitalist countries tell us in this regard? They show that the great majority of currently produced goods are bought in customary shops, or from customary service distributors, /independently of price fluctuations/. It is no exaggeration to say that this holds for at least 80 per cent of the consumption of the average consumer.

Thus no current price fluctuation will induce a normal client suddenly to change their baker, grocer, bus or underground, their hairdresser, supermarket or even haberdasher, let alone their children's school or hospital. The ordinary person does not run around from one fruiterer to another to find out where a pound of apples is 5p cheaper. /Their time/ (and in many cases: habit, desire to talk to familiar vendors or other customers) /is more precious than these marginal differences/. Typically, it is only when economic catastrophes occur (oil prices increase 300 per cent, or income falls 30 per cent as a result of unemployment) that such consumption patterns respond to orthodox market signals---and even then by no means for all goods and services. The evidence indicates that ongoing non-market responses have superseded market reactions in many fields of daily economic behaviour. Even in working-class neighbourhoods, a suddenly cheaper supply of apples may be regarded with suspicion (‘lower quality?' ‘a publicity stunt?') and sell less and not more than fruit that is a little costlier. A relatively moderate increase, say 10 per cent, in the price of package holidays can stimulate rather than depress vacation expenditure, as long as income and employment remain unchanged.

Economic relations of this kind involve neither a real market economy, nor bureaucratically centralized planning. What they represent is elementary forms of spontaneous cooperation. They will often remain relatively stable for years, if not decades. Of course, they can be changed at will by the individual, or the household, and often are---but without any outside force dictating such changes, or any major economic upheaval occurring as a result of them. The same holds good for many inter-firm transactions. A frantic search among a multiplicity of suppliers in order to cut the materials' bill by 5 per cent will make no sense for a large company, if only because its customary suppliers will tend to guarantee reliable delivery times and a reasonable quality of goods, vouched for by experience, which more than outweigh small price differentials. That is how most business is conducted today in capitalist---and ‘socialist'---countries: based on habit, custom, routine and the natural cooperation that grows from mutual knowledge and foreseeable results.

** An Objection

But it may be objected: these millions of acts of voluntary cooperation, which are themselves not guided by either market signals or bureaucratic directives, are nevertheless underpinned and rendered possible by powerful forces for economic centralization, whether market or planned in character. Routine cooperation regulates only relatively small decentralized operations, not large-scale centralized ones. This objection contains an element of truth. But it is a smaller one than might appear at first sight. Its force rests on the contrast between---say---on the one hand the millions of customers who routinely go to small shops or supermarkets to buy their condensed milk, without watching small price changes over a wide area with eagle eyes to shift their custom to the cheapest outlet; and on the other the Nestlé or Carnation corporations, whom the market /forces/ to watch production costs and returns on that milk with eagle eyes indeed, on pain of bankruptcy. Has the ‘market---not actually obliged these giant trusts to fuse---or was it not the market?

Yet Nestlé's own distribution network to its thousands of retail outlets will be thoroughly routinized; and its output of condensed milk will be highly automatic and routinized as well. In fact the ‘market---scarcely enters into this circuit in any economically relevant way at all, since Nestlé, being a monopoly, can naturally impose sale prices based on average production costs plus a pre-established profit margin. People need milk in any case and consume it in more or less predetermined quantities, so the only economically significant facts here are what share of national income (or of national expenditure) will be devoted to milk consumption, and what part of production resources will be allocated to producing and distributing milk under optimal conditions of dietetics and hygiene. Given the advanced techniques already existent, all other fluctuations are absolutely minimal.

A still more striking example is the power industry. A national power grid---indeed the international grid of the eec and a few adjoining countries---does not need any market forces or centralized bureaucracy to function smoothly. The marginal elasticity of demand for electricity can be fairly accurately established on the basis of statistical series. The maximum load at given times throughout the year can be predicted in advance. Sufficient reserve capacity can be kept against any danger of sudden breakdown or steeply increased demand. The result is that the stable distribution of power among several hundreds of millions of customers essentially requires neither market forces nor big bureaucracies. It could largely be handled by computers working on the available statistical data.[fn:5] Indeed, it is a ‘pricing---of this good that is becoming increasingly irrational (at least for private consumers and the average enterprise---the few industries which are very large consumers of electricity could still be charged). If that were abolished, about 90 per cent of the existing bureaucracies of the power industry---West and East---could be suppressed altogether.

Such cases cannot be generalized to all goods and services, in every branch of industry or sector of society. Some problems of centralization are indeed technically of such a nature that routine cannot substitute for decision-making institutions. The /overall/ division of economic resources (on a national and international scale) between different branches of activity and sectors of society must be regulated by a deliberate agency. But precisely the trend towards wider and wider /de facto/ cooperation between ordinary people, which has developed side by side with the objective socialization of labour, shows that there /is/ a way out between the Scylla of blind market forces and the Charybdis of huge centralized bureaucracies: /democratically centralized---that is, articulated---self-management,based on deliberate and free cooperation./

* 6. Innovation and Motivation

But would this ‘third solution' not lead to an idealization of routine and custom---that is, to economic stagnation? Certainly not in the field of production, where the producers' interests in reducing their work-load and ameliorating human ecology would generate a built-in incentive to cost-cutting. Perhaps it would slow down the onrush of new consumer goods. An alteration in the current commodity stream would in itself scarcely involve much hardship---even the richest consumers have after all lived quite happily without electronic games or mobile telephones in the recent past. Only a misanthropic vision of humanity would gauge its relative progress or health by the increasing number of decreasingly useful gadgets its citizens consume. A socialist democracy would /grow/ in /civilization/ rather than in mere consumption---that is, in a broadening range of /meaningful human activities and relations/: the rearing of children and spread of education, caring for the sick and disabled, the practices of creative work, the exercise of the arts and the sciences, the experiences of love, the exploration of the world and the universe. Would a society that gave the highest priority to the fight against cancer and heart diseases, to the study of the development of children's character and intelligence, to the comprehension and reduction of neuroses and psychoses, be such a dull and unexciting one compared to the joyfully dynamic world we now live in? Is the freedom to live longer and in greater mental and physical health less important than the freedom to buy two colour tvs?

The absence of market competition in no way necessitates a lack of product innovation. Throughout history, indeed, most key discoveries and inventions have been made wholly outside any commercial nexus. Profit did not exist when fire was first conserved. Agriculture and metallurgy were not brought into being by the market. Printing was not invented for gain. Most of the great medical advances---from Jenner to Pasteur and Koch to Fleming---were not induced by hope of financial recompense.[fn:6] The electrical motor was born in a university laboratory, not a business workshop. Even the computer, let alone the spacecraft, was designed for public (albeit military) purposes, not for enriching private shareholders. There is not the smallest reason to assume that a withering away of market relations and monetary rewards would lead to the disappearance of technological innovation. For its impulses lie much deeper than mercenary competition---in the natural propensity of ordinary producers to save their own labour, and in the unforced intellectual-scientific curiosity of human beings.

Likewise, there is no foundation for the widespread notion that social equality is an obstacle to economic efficiency. Evidence to the contrary can readily be found in the Israeli kibbutzim, where a third generation is now growing up of people living in an environment characterized by a basic absence of money relations in the fields of both production and consumption. The kibbutz is, of course, is no sense a socialist community. On the contrary, it is a settler military village which has functioned as a colonial wedge against the Palestinian population, with all the strains and corruptions this role involves. Moreover it is embedded in a capitalist economy which subsidises it, and so is increasingly intertwined externally with capital/wage-labour relations. But precisely because of these unpromising conditions, it is all the more remarkable that the simple abolition of money and market relations within the kibbutz should have led to so many of the socio-economic results Marx and Engels forecast from it. In spite of the complete disappearance of monetary rewards and sanctions, people in the kibbutz produce normally and efficiently---in fact on average more efficiently than in the surrounding market economy. No new ‘non-monetary' kinds of economic inequality, privilege, exploitation or oppression have emerged. Violence and crime have all but vanished. There are no prisons or ‘corrective' labour camps. The average level of health, culture and well-being is strikingly superior to that of Israeli society as a whole. There is unrestricted political and cultural freedom. All this is confirmed not only by apologists for the system but by highly critical observers such as the psychoanalyst Bruno Bettelheim, the liberal Dieter Zimmer or the sociologist Melford Spiro.[fn:7] Of course there are plenty of conflicts---between generations and between genders, for one thing. The kibbutz is no fulfilled utopia. Individualist inclination and behaviour have by no means disappeared as a result of socio-economic equality. After all, why should it? The hallmark of a classless society itself would not be the similarity of the individuals who comprise it, but the greatest differentiation of the greatest number of individuals within it. The goal of socialism is not so much the socialization of the person as the personalization of society---that is, the fullest possible development of the unique personality of /each/ individual.

* 7. Articulated Workers' Self-Management

The issue of /motivation/---to efficiency, cooperation and innovation---is thus in no way an insuperable problem for a socialist democracy. A more immediate difficulty lies in the /institutionalization/ of popular sovereignty itself. How can a maximum of basic consumer satisfaction be combined with a minimum of producer work-load? Alec Nove rightly dwells on this contradiction, which no serious Marxist would deny. But to register that this is a real contradiction---that you cannot produce goods and services /ad infinitum/ in hours of human labour tending towards 1 or 0 a week, except with a ‘total' robotism still lost in the mists of a distant future---does not mean that you cannot dramatically increase the satisfaction of basic consumer needs for all human beings, while simultaneously reducing no less dramatically the burden and alienation of the labour of the direct producers. A system of articulated self-management could go far to realizing these goals. Its main mechanisms and institutions would function as follows.

Regular---let us assume for the sake of simplicity: annual---congresses of national, and as soon as possible international, workers' and popular councils would determine the great divisions of the national product, starting from coherent alternatives previously debated by all citizens in the election of that congress. The choices---that is, the main foreseeable consequences of each option---would be clearly spelt out: average work-load (length of the working week); priority needs to be satisfied for all through guaranteed allocation of resources (‘free' distribution); volume of resources devoted to ‘growth' (reserve fund + consumption of additional population + net investment as a function of technological choices again clearly spelt out); volume of resources left for ‘non-essential' goods and services to be distributed through money mechanisms; minimum and maximum money incomes; pricing policy for marketable goods and services. The global framework of the economic plan would thereby be established on the basis of conscious choices by a majority of those affected by it.

Starting from these choices, a coherent general plan would then be drawn up, utilizing input-output tables and material balances, indicating the resources available for each separate branch of production (industrial sectors, transportation, agriculture and distribution) and social life (education, health, communications, defence if that remains necessary, etc). The national or international congress would not go beyond these general instructions and would not lay out specifications for each branch or producing unit or region.

Self-managing bodies---for example, congresses of workers' councils in the shoe, food, electronic equipment, steel or energy industries---would then divide up the work-load flowing from the general plan among the existing producer units and/or project the creation of additional producing units for the next period, if the implementation of output goals made that necessary under the given work-load. They would work out the technological average (gradually leading up to the technical optimum on the basis of existing knowledge)---that is, the average productivity of labour, or average ‘production costs'---of the goods to be produced, but without suppressing the least productive units as long as total output elsewhere does not cover total needs, and as long as new jobs for the producers concerned are not guaranteed in conditions considered satisfactory by them.

In production units making equipment, the technical coefficients flowing from the previous steps would largely determine the product mix. In factories manufacturing consumer goods, the product mix would flow from previous consultation between the workers' councils and consumers' conferences democratically elected by the mass of the citizens. Various models---for example, different fashions in shoes---would be submitted to them, which the consumers could test and criticize and replace by others. Showrooms and publicity sheets would be the main instruments of that testing. The latter could play the role of a ‘referendum'---a consumer, having the right to receive six pairs of footwear a year, would cross six samples in a sheet containing a hundred or two hundred options. The model mix would then be determined by the outcome of such a referendum, with post-production corrective mechanisms reflecting subsequent consumer criticisms. Compared with the market mechanism, the great advantage of such a system would be the far greater consumer influence on the product mix and the suppression of over-production---the balancing out of consumer preference and actual production essentially occurring /before/ production and not /after/ sales, with a buffer stock of social reserves additionally produced---empirically (statistically) optimized after a few years. Factory workers' councils would then be free to translate these branch decisions at the level of the producing unit as they liked---organizing the production and labour process to realize all the economy of labour-times they could achieve. If they could reach the output target by working twenty instead of thirty hours a week after submitting their goods to a quality test, they would enjoy a reduction in work-load without any reduction of social consumption.

Alec Nove at one point remarks: ‘In no society can an elected assembly decide by 115 votes to 73 where to allocate ten tonnes of leather, or whether to produce another 100 tonnes of sulphuric acid.'[fn:8] In our model of articulated self-management, no assembly would have to take two such decisions at one and the same time, and no ‘central' assembly or planning board would have to take any of them. But for what reason could not the congress of workers' councils of the leather industry decide by a majority vote (more likely by consensus, after some discussion) on the allocation of leather (whether the very small quantities in the example should be left to a factory council is another question), once consumer goals for products using leather had been decided by other bodies? Why couldn't it divide the total of---say---50,000 tonnes of annual leather output among several plants (as in any multi-factory capitalist leather concern today), assigning to each unit its ‘customers' (i.e. the destinations of the required quantities of leather)? Wouldn't the delegates of such a congress in fact be more likely to handle such allocations better than any technocrat or computer, because they know their industry better and can take into account a lot of imponderables which no market or central board will include in its calculations, or at best only accidentally?

In fact, gigantic ‘mistakes' in allocation constantly occur in a market economy, which no sensible workers' assembly would ever commit. Capitalist planners budgeted the building of the Itaipu dam in Brazil at $5 billion. Its cost today stands at $18 billion, and the bill is not yet complete. In the US agricultural machinery trust Deere new products have to be repeatedly redesigned, in spite of fierce competition, because of the endemic discrepancies between the skills and interests of design and manufacturing engineers. In the current recession, the Bavarian auto company bmw suddenly discovered it could reduce inventories from eleven to five days output---i.e. by more than 50 per cent. Such examples could be multiplied at will.

National self-managing bodies could, moreover, take over the administration of the public services---housing, education, health, telecommunications, transport, or distribution. Here too there would be councils elected by the citizens concerned, which they would have to consult before decisions could be finally implemented. Regional and local bodies would then deploy the resources thus allocated, again with the maximum of free initiative to make best use of them in the interests of user satisfaction and producer effort reduction. Such a system would give a concrete content to the Marxist conception of a gradual withering away of the state. It would allow at least half of contemporary Ministries to be replaced at one stroke by self-managing bodies. It would also effect a radical reduction in the number of functionaries, including in the field of planning. At the same time, it would mean that literally millions of people would be---not merely ‘consulted'---but actually participants in decision-taking and direct administration of economy and society. The social division of labour between administered and administrators---between the bosses and the bossed---would begin to disappear.

Administration would no longer be monopolized at the ‘central level', any more than self-management would be confined to a plant level. Both would be mixed at central and decentralized levels. The great masses of citizens involved in this decision-making would not be engaged in such activity on a full-time professional basis, spending all their time either in meetings or travelling to them. Since the decisions in question would directly influence their current welfare and working conditions, it can be assumed that they would not take a formal or indifferent attitude towards their responsibilities, but involve themselves seriously in the process of administration. The reduction in the working week and the information and communication potential of the computer would furnish the principal material bases for a successful diffusion of power.[fn:9]

How would the additional money income of the producing and distributing units, beyond their guaranteed allocation of free goods and services, be calculated? It could be indexed to quality control and customer satisfaction within a given spread, with a coefficient for work stress (mines and other harsher production-sites earning higher remuneration). For intermediary goods, punctual deliveries would form part of the quality-control/consumer-satisfaction index. Such a system would have the advantage of not containing any built-in disincentives to an open and honest flow of information about the resources and potentialities of producer or distributor units, as the self-managing work-force would have no interest in hiding the facts. Nove makes out a strong case against the idea that honest flows of information can be taken for granted. But he tends to overlook the main cause of the provision of dishonest data in societies like the ussr---the material interest of factory managers, tied to the physical output of their plants. You can't suppress the consequence if you don't suppress the cause. In addition, of course, computerized flows of information automatically accompanying flows of goods can go a long way towards assuring correct data inputs for democratically centralized planning. How would such a system be articulated on a world scale? It should be stressed at the outset that democratic self-management does not mean that everybody decides about everything. If one was to assume that, the conclusion would be obvious: socialism is not possible. Four billion human beings could not find the life-span to settle even the tiniest fraction of each other's affairs, in that sense. But it is not necessary. Certain decisions can be best taken at work-shop level, others at factory level, others again at neighbourhood, local, regional, national, continental and finally at world level. Our discussion, following Nove, has so far been concerned mainly with the national level. But what decisions could---and should---be taken on a world scale? Four fields immediately present themselves. The first would be all those decisions necessitating a global redistribution of human and material resources to ensure the rapid disappearance of the social and cultural ills of underdevelopment---hunger, infant mortality, disease and illiteracy in the Third World. The second would cover priority allocation of genuinely scarce natural resources---those which could be depleted absolutely, and of which no minority of the human race has the right to dispossess the next generations; only the living population of the world in its totality has the right to decide here. The third would include everything affecting the natural environment and climate of the planet as a whole; all those processes which can pollute or disrupt oceans, poles or atmosphere, or destroy such world-wide bases of ecological balance as the Amazon Forest. Finallly, of course, there would be all universal prohibitions---weapons of mass destruction, manufacture of toxic drugs, and so on.

From these global parameters would flow constraints on continental or national resources available for planning and need-satisfaction, which would themselves be decided in each continent or country. Thus, for example, once the total tonnage of steel that could be used in America, Europe or Asia was set, the producers and consumers of these areas would be free to allocate it as they decided. If, in spite of every environmental and other argument, they wanted to maintain the dominance of the private motor car and to continue polluting their cities, that would be their right. Changes in long-standing consumer orientations are generally slow---there can be few who believe that workers in the United States would abandon their attachment to the automobile the day after a socialist revolution. The notion of forcing people to change their consumption habits is far worse than that of another few decades of smog in Los Angeles. The emancipation of the working class---today, contrary to every received notion, /for the first time in history/ the absolute majority of the earth's population---can only be achieved by the workers themselves, as they are: not people out of another world, but human beings with their weaknesses like all of us.

** Towards Socialism

Such a complex of conscious resource allocation, of democratically centralized planning and self-management, would be much more efficient than either a (monopoly-capitalist) market economy, or a (bureaucratically-centralized) command economy. For it would have a powerful built-in self-correcting mechanism, which both of the existing alternatives lack. We do not believe that the ‘majority is always right', any more than we believe that the Duce, the Pope or the Party is always right. Everybody does make mistakes. This will certainly also be true of the majority of the citizens, of the majority of the producers, and of the majority of the consumers alike. But there will be one basic difference between them and their predecessors. In any system of unequal power---be it economic inequality, political monopoly or a combination of the two---those who make the wrong decisions about the allocation of resources are rarely those who pay the price for the consequences of their mistakes, and never those who pay the heaviest price.

When the Directors of a large monopoly decide on a major investment which a couple of years later doesn't pay off, they themselves will not be reduced to unemployment compensation and their suburbs will not fall into decay. But the workers they have laid off, and their communities, will suffer exactly that fate, although they are completely innocent of the original decision. Likewise when the Praesidium of the cpsu, or the Council of Ministers, or the Gosplan authorities make a mistaken decision about agricultural policies, members of these exalted bodies will generally not forego meat consumption---but millions of people may have an inadequate diet for years, and whole areas be polluted or devastated. By contrast, when the mass of producers/consumers vote by a majority for a misguided allocation of resources, they themselves will be the first to pay the price for their error. Provided there exist real political democracy, real cultural choice and information, it is hard to believe that the majority would then prefer to see their woods die, their meat consumption fall, their housing stock dwindle, or their hospitals understaffed, rather than rapidly to correct their mistaken allocation.

The system we have outlined would not yet be a ‘pure' socialism of the kind envisaged by Marx and Engels. It would still be a transition towards socialism---though definitely /towards socialism/, not towards an unknown future or towards capitalism---for it would still contain a sector ruled by money and the market. Private and cooperative enterprises would survive in small-scale production (agriculture, handicrafts, services and so on). Individual entrepreneurship would not be forbidden; for since all citizens would have a guaranteed minimum level of consumption, there could be no /economic compulsion/ for others to sell their labour power to such entrepreneurs, and contracts between them would be genuinely voluntary. Domestic ‘self-employment' could be generalized as citizens received elementary tools to produce whatever they wanted for their own satisfaction or that of their families, friends or neighbours, in their leisure-time. Identical motor-cars make ugly cities---which might be transformed if car-users became creative painters and put their imagination to work on their auto bodies. The scope for practical do-it-yourself initiatives would be enormously enlarged.

* 8. Mixed Misery---a General Critique

Alec Nove has proposed a five-sector model of feasible socialism---a combination of state, socialized, cooperative, small-scale private and individual enterprises.[fn:10] At first glance the differences between this scheme and the model we have just sketched might appear relatively slight. Yet despite some areas of overlap, the two models diverge in three essential respects. The first concerns the nature of the predominant productive---or distributive---units. For Nove, individual cost-accounting implies individual profitability for these units---i.e. that the incomes of the groups or persons involved should be related to the differences between the computed money (or value) costs of inputs and outputs. In other words, these units are independent firms. We do not agree with this prospect. In our view, to link group or personal incomes to ‘profits' is to introduce powerful impulses towards economic irrationality, risking social havoc as multiple decisions are taken as a function of particular, fragmented interests. For the same reasons, we do not believe that agreements between producers and consumers should be based on monetary rewards and sanctions. In other words, real market relations---that is, commodity exchange transacted in currency---should essentially be limited to the inter-relations between the private and cooperative sectors on the one hand, and the individual consumer or the socialized sector on the other. The effect would be that in the advanced industrial countries such relations would have only a subordinate weight in output and consumption. The dynamic of the transition would be towards the withering away of commodity production and not towards its extension.

Secondly, Alec Nove establishes a distinction between a centralized ‘state sector', where he argues technical scale and complexity preclude self-management by the producers, and a ‘socialized' sector of less integrated enterprises where such self-management would operate. He also seems to suggest that income differentials would be indispensable to both, perhaps even to the cooperative sector as well. Thus he writes: ‘Income differentials (a species of labour market) are the only known alternative to direction of labour. Here it is essential to avoid a mental muddle: some might say that within a commune, or a good kibbutz, one can have full equality and rotation in jobs . . . But this cannot be generalized over the whole of society, partly because it is only workable with small numbers of people who know each other and can meet together daily, and partly because such communes would attract only the enthusiasts who like this sort of life.'[fn:11] The argument here seems common-sensical enough, but in fact it rests on a series of unproven dogmas and prejudices. For it is not true that the only choice is between a despotic ‘direction of labour' and a market in labour. Cooperatively distributed labour is a real alternative. Nor is it the case that large-scale organizations cannot be administered without income differentials. In the nineteenth and early twentieth centuries, trade unions and churches encompassing tens and hundreds of thousands of members were often managed by people who did not receive any serious material privileges. So indeed---as Alec Nove himself points out---were large scientific organizations, not to speak of major producer cooperatives. Nove elsewhere rightly points out that few professors would prefer to be garbage collectors, even if they were better paid. But that observation rather tells against his general assumptions here. It is an argument for paying disagreeable, dirty or burdensome work---not administrative or skilled work (provided society pays for the acquisition of the skill)---more.

But perhaps the most fundamental flaw in Nove's argument lies elsewhere. It is to be found in the antithesis he postulates between ‘a small number of people' and ‘large organizations'. For there is no such thing as an /unstructured/---that is, atomized---large organization. A modern factory, bank, hospital or high-school are certainly nothing of the kind. All institutions of this sort are in reality built upon small units of objective social cooperation: work teams, offices, departments, classes, and so on. Why should it be unthinkable that these smaller units administer themselves, and elect delegates (including by rotation) who then administer the larger units, who then administer the whole? The preconditions of democratic self-management are to be found in the way in which the actual cells of existing undemocratic institutions function---that is, in the working relations of a small number of people who know each other, meet each other and /need each other/ daily: in other words, could not do their jobs without mutual cooperation. Thus, unlike Alec Nove, we believe that the scope for self-management is in


The third basic difference between Nove's model and our own concerns the role of competition in them. Nove is aware of the destructive and corrupting effects of the competitive rat-race under existing capitalism. But he wants to preserve monetary incentives in his socialism. He therefore argues that we should distinguish between ‘benign' and ‘undesirable' forms of competition.[fn:12] But the examples he uses to illustrate the distinction in fact show how little relevance it has for economic purposes. For it is obvious that ‘competition' for a seat in the Scottish National Orchestra, for victory in the Olympic mile, or even for election to the workers' council of a ‘socialized Dupont', has very little to do with competition to sell oil, steel, heavy equipment, aircraft or missiles on the market. The first variety of ‘competition' has never, to our knowledge, caused misery for millions of people (it has caused a lot of individual misery---but then Marxian socialism has never had the illusion that it could solve all cases of that). The second variety, by contrast, has not only again and again caused mass unemployment and falling living standards---if not stark poverty---but also wars that cost millions of deaths.

** A False Dilemma

Nove resorts, however, to his involuntary casuistry because he remains so committed to a conventional view of the market. The combination of ‘market' and ‘socialism' in his thought then inevitably leads to disconcerting contradictions. Nove repeatedly taxes Marxists with a utopian vision of socialism. What he fails to notice is that his own premises---a higher level of freely accepted social responsibility by individuals, yet at the same time a social framework permeated by competition for financial remuneration and material gain---represent an acme of utopia. In a milder way they recall the ingenuous (or cynical) claims of Soviet officialdom that the ussr can proceed towards the creation of ‘socialist man' while maintaining huge inequalities of income and power, and a universal scramble for material advantages. Nove is driven to his inconsistency because he is imprisoned in a false dilemma. The logic of his error can be seen in the following passage: ‘Suppose there are sixteen or more firms (socialized and cooperative) engaged in providing some one good or service. Let it be wool cloth, tooth-paste, ball-bearings, holiday hotels, or whatever. They base their productive activities on negotiations with their customers. The latter can choose from whom to obtain the goods and services they require. All can obtain from /their/ suppliers, whom /they/ can choose, the inputs needed to make production possible. They have a built-in interest in satisfying the customer . . . We would hope that the motive of competition would not be primarily monetary . . . But we cannot assume that the mass of the population will act only for the satisfaction of succeeding, that there will not be a need for material incentives, and disincentives too.'[fn:13]

The first part of this argument commands our whole-hearted agreement. We would only enter the qualification that for most sophisticated or large equipment goods, there would not be sixteen suppliers. But the second part does not follow from the first at all. It is presented as a kind of supplement, or rider, yet in fact it lacks either connexion or foundation. What Nove has done is to presume that people can only act /either/ in purely disinterested fashion /or/ for monetary incentives. But this choice is not an exhaustive one. Why cannot there be incentives and disincentives of a non-monetary and non-market character? Everyday experience testifies to the importance of these even under capitalism. After all, if more than 99 per cent of car drivers observe traffic lights, it is not primarily because they want to escape paying fines for violating them, but because they want to live longer. That healthy instinct for self-preservation is not unrelated to another common human impulse: the desire to minimize troublesome, mechanical, boring and uncreative labour---work done just as means of securing consumer goods and services, that is lost living time. There is always a potential incentive to cut the work-load by organizing it better---a very powerful one. Above and beyond these, however, Nove seems to have forgotten the possibility of a ‘social dividend'. Why should not an additional amount of free goods and services be tied to the annual /overall/ economic performance of society, rendered transparent through public debate and telecommunications? Wouldn't it be an incentive for all producers and distributors to increase the quantity and improve the quality of their output, and to rationalize their labour organization, if a given rise in the amount of goods and services actually produced and consumed were linked to---let us say---a specific extension of free vacation and

motivations, which impels him towards monetary incentives, Nove then goes on to ignore the objectively irrational consequences of combining a large market economy with a sector of free goods and services and social property. For, of course, if profit remains a basic mechanism of resource allocation, there is no reason why the negative outcomes of it so familiar under capitalism should not reappear. It is significant that when Nove does touch on the risks of resort to monetary incentives, his examples are very marginal ones---not the /huge waste/ to which production for profit leads: over-capacity, over-production, unemployment, destruction of equipment and goods. All of these typical phenomena harm consumers and producers alike far more gravely than the supposedly excessive costs arising from absence of ‘the discipline of profits and losses'. This lesson is not just one learnt daily under capitalism. It is being painfully acquired in post-capitalist societies as well. Practical experience there too---above all in Yugoslavia and Poland, but other examples will follow---show that attempts to correct the distortions and dysfunctions of bureaucratically centralized planning through increased reliance on market mechanisms lead, after some initial successes, to a growing combination of the ills of bureaucracy with those of the market, each reinforcing rather than mitigating the other.

This pattern will hold good even in China---the most favourable case for the advocates of market socialism, since the more backward the country, the more indispensable market mechanisms remain, above all in agriculture. There can be no doubt that the undoing of the disastrous legacy of the Great Leap Forward---the completely irrational and mystified notion of an immediate introduction of communism---has led to very big progress in the Chinese countryside. Productivity and output have shot up, and a growing surplus is now being generated on the land. This was the result of freeing the tremendous productive energies of the Chinese peasantry, probably the most capable such class in the world, with a two-thousand-year-old tradition of intensive farming behind it that has no equivalent in much of Western---let alone Eastern---Europe. But the growing surplus of food-grains is going to bring with it an ever growing surplus of rural labour, as less people produce more food. What will happen to that surplus population in fifteen, twenty or thirty years time? If it is left to the market, the result is going to be a huge build-up of unemployment in China---a problem that is already becoming severe in the big cities. Only planned industrialization can absorb that surplus rural population and only /democratically/---not bureaucratically---planned industrialization can do so without preci-pitating the convulsions in the countryside that forced collectivization brought in the Soviet Union: itself a panic reaction to the consequences of market growth in the ussr.

Overlooking the weight of all the negative economic consequences of the market, Nove offers a positive political rationale for it---that it diffuses decision-making power, and so is a bulwark against tyranny. This, of course, is a traditional liberal justification of the market. But it is no less of a misconception in socialist guise. Nove's concomitant acceptance of income differentials for administrators makes that clear. For if administrators derive material advantages from management positions, they will inevitably try to transform these into permanent tenure---that is, to hold onto them with all the economically irrational and politically oppressive conduct inherent in such attempts. Power will tend to become monopolized. /The diffusion of power for which Nove speaks cannot be realized unless its exercise is divorced from privilege/. This is not an article of faith, but an empirical conclusion from all recorded human history. Once power and privilege go together, the logic is away from democracy and towards monopoly of information, knowledge and control by a small minority. Nove wants to further a democratic socialism. But once he underwrites monetary rewards for management, it is no accident that he has to end by speaking of the need for a strong state.[fn:14] For all the trenchancy of his critique of ‘actually existing socialism', he thus concludes with two propositions that are uncomfortably closer to the reality of the Soviet bureaucratic order than they are to Marxian socialism. It is significant that Nove uses much the same terms as the Polish bureaucracy in criticizing Solidarnosc's refusal to accept a cut in the living standards of Polish workers.[fn:15] In doing so, he forgets that the responsibility for economic disruption lies not with the workers' demands and strikes but with the whole pattern of bureaucratic mismanagement before and after 1980.[fn:16] Similarly, he does not take into account the insoluble contradiction between workers' self-management and ‘market socialism' which is today exploding in Yugoslavia. If ‘objective economic laws' operating behind the backs of the producers---and that is what the law of value really means---decide in the final analysis upon output and employment, then workers /cannot/ determine them at either factory, commune or national level.

Is there no alternative? The burden of this article is that, happily, there /does/ exists a way out---democratically articulated and centralized selfmanagement, the planned self-rule of the associated producers. Popular sovereignty does not depend on the assumption of any pre-established or perfect harmony between general and particular interests in the community. On the contrary, it takes for granted that there will be /unavoidable/ conflicts of interest between producers and consumers, technically more and less advanced producing units, socially more and less active people, economically and culturally more and less developed regions. What democratic self-management represents is precisely a system of built-in safeguards to prevent these contradictions from undermining any rational planning or social cooperation by setting off renewed class strife and internecine violence. ‘Market socialism', by contrast, is no solution for the evils of either the capitalist legend of a free market or the bureaucratic travesty of a free socialism. The mixed economy it proposes is merely mixed misery. The real economics of a feasible and desirable socialism would supersede either alternative. Contrary to Alec Nove's declared belief---/tertium datur/.

What our debate is finally about is the central problem of human history: whether and under what conditions humanity has the potential to shape its own destiny; whether self-emancipation and self-determination for all will forever remain an unfulfilled dream. For if the social sciences and social praxis fail to achieve a control over social evolution comparable to that which the natural sciences have so far attained over nature, then even the advances of natural science threaten to explode in our faces. In the age-old debate about the potential of reason and the dead weight of fate---ultimately a contest between knowledge and superstition---‘market laws' represent nothing but blind fate under an increasingly thin disguise of partial ‘rationality'. Is humanity's insight into the laws of its own evolution really a fruit from which it should be forbidden to partake?

* Footnotes
[fn:1] Friedrich Engels, /Anti-Dühring/, Moscow 1954, pp.
374--75, 378.

[fn:2] /The Economics of Feasible Socialism/, London 1983,
p. 33. I shall concentrate in this article on the principal criticisms Nove makes of the Marxist conception of socialism, rather than his disagreements with Marxist economic theory in general. I will touch on the latter in my forthcoming book /Marx's Theoretical Legacy---Restating the Case for Socialism at the End of the Twentieth Century/, London: Verso, 1987.

[fn:3] /The Economics of Feasible Socialism/, pp. 15--16.

[fn:4] See, among others, Wlodzimierz Brus, /The Market in a Socialist Economy/, London 1972; Branko Horvath, /The Political Economy of Socialism/, London 1976; Ota Sik, /The Third Way/, London 1976; R. Selucky, /Marxism, Socialism and Freedom/, London 1979; Ferenc Feher and Agnes Heller, /Dictatorship over Needs/, London 1984.

[fn:5] For the use of the computer to introduce completely automatized enterprise management systems in the ussr, called in English asup by the author, see Martin Cave, /Computers and Economic Planning/, Cambridge 1980, pp. 153--67.

[fn:6] Cesar Milstein, Nobel prize-winner for medicine in 1984, refused to take out a patent on a discovery that could be generating a £1 billion market by 1990: ‘A patent would have meant keeping everything secret while we thought about applications---an outrageous insult to science. Patents are an intellectual swindle.' /Sunday Times/, 21 October 1984.

[fn:7] See, among others, Bruno Bettelheim, /The Children of the Dream/, New York 1969; Rabin-Beit Hallahmi, /Twenty Years Later/, New York 1982; Gunar Heinsohn (ed.), /Das Kibbutz-Modell/, Frankfurt 1982; Dieter Zimmer, ‘Die Form des neuen Menschen', in /Zeitfragen/, 12 October 1984.

[fn:8] /The Economics of Feasible Socialism/, p. 77.

[fn:9] An intensive research project under Professor Dörner, a German conservative, has shown experimentally that with the aid of computers ordinary people can resolve many of the complex problems of socio-economic planning at the level of a medium-sized town. What they needed was not above-average intelligence or a great deal of advanced knowledge. The key to their ability was /the feeling that they really were in control/, the conviction that they possessed a genuine power to decide. See Dörner (ed.), /Lohausen. Vom Umgang mit Unbestimmtheit und Komplexität/, Berne-Stuttgart-Vienna, 1983.

[fn:10]  /The Economics of Feasible Socialism/, pp. 200--01.

[fn:11] Ibid., p. 215.

[fn:12] Ibid., pp. 204--05.

[fn:13] Ibid., p. 204.

[fn:14] Ibid., p. 229.

[fn:15] Ibid., p. 178.

[fn:16]  Andreas Hoessli has written a remarkable analysis and critique of the Polish bureaucracy's mismanagement: /Die planlose Planwirtschaft?/ It must be hoped that this book, soon to appear in German, will be rapidly translated into English.
