#+TITLE: June 15th, 2023
#+INCLUDE: ~/org/blog/noumena/header.org

* Reflecting on the past


The same way it's true that I'm arbitrarily starting this journal about Noumena right now, some time ago, I wanted to start uploading all of our videos of her to youtube and categorizing them. And, just like then, I wish I had been doing journaling every since she was born. Thankfully, I think this may be a bit easier than uploading the videos. I'm actually uploading another batch of 15 as we speak. The maximum YouTube allows you to upload at one time. At this rate, including all the videos I've uploaded since, It will take me maybe a month. Yipee! 🙄 and I think to myself, "If only I had just been doing this once a day, it would have been so easy." So This is my attempt to fix that. Unfortunately, I can't retroactively blog the way I can upload old videos, so I'll just have to settle for the ephemeral nature of those days.


* Today

It rained all evening after I picked Noumena up from daycare, so we didn't get to really go outside and play, which is unfortunate because it really is the most fun to get her outside. She really does love the outdoors and it's so easy for me when she's preoccupied. All the kids at the park absolutely adore her. There are a few kids I let hold her and she absolutely loves them. Mia, 13, and Caleb, 10, are two of them I let hold her.

But, unfortunately, as I said, it rained all evening, so we were stuck inside. A double issue has been that I've been sick for what feels like forever now, though I'd estimate about 4 weeks almost. See, when Noumena went to daycare, she got what's affectionately called "daycare syndrome," a persistent bout of sicknesses caused by the sudden exposure to many different new kids who are obviously not the cleanest. So we first got strep throat. That was a really hard time, then we got antibiotics, got better... then got sick with the common cold. Oh boy, what a ride it's been. At any rate, due to the sickness, it's difficult to take care of her.

I made her mashed potatoes and she seemed totally uninterested. It was so bizarre because I remember previously that she couldn't stop eating them! She was very whiny about it and I couldn't figure out what was wrong, but I ended up realizing that she wanted to drink. The only way I could tell is that she would put the food in her mouth, but then spit it out and get upset. So, I thought to myself, "what can you put in your mouth that's not food... obviously drink." So I got her soymilk and she seemed parched she drank it so fast. And a lot too.

I did get to have a little break because her behavior in general has been pretty great. She sort of easily preoccupies herself with her toys and is not too demanding. I like to believe she's making it easy on me because she loves me and knows I'm having a hard time since I'm sick.

The light that hangs above our kitchen table has piqued her interest as of late and I have no clue why. We have low ceilings, maybe 9 foot, and the kitchen light "chandelier" hangs down far enough to where, before the table was directly under it, I smashed my head on it a few times. She's constantly pointing at it and grunting. And, of course, every time she does, I say "light" to indicate to her that's what it is. I also will suspend her above the table letting her grab and touch it.

This makes me think about spoiling her. I wonder to myself, "if I give in when she wants to touch the light, am I instilling bad habits?" Thankfully, I'm tempered by a few thoughts that also occur shortly thereafter: I think, "it's not a big deal. When is she ever going to be interested in this light again? I should definitely cherish this. If it were serious, I wouldn't give in so easily." So... I always give in. haha. If she wants to touch that light, then dammit she will if there's anything I can do about it.

We read her currently favorite popup book and played a little while on the bed. I have some videos of us doing so as well and I'll update this blog when they get uploaded. Her smile and laughter are so important to me and so so so cherished, so these playful opportunities mean the world to me. She loves when I'm a goofball around her and if it makes her laugh then I guess it's a huge win for both of us. I also have a cubical box with interchangeable lids and various things to place through them and into the box. There's one with holes for five fake carrots to stick out of, one for small, cylindrical wooden rods much longer than they are wide that fit into a bunch of little holes, and big wooden coins (relative to the coins we're most familiar with) and  a slitted top to fit them in. Today, she really seemed like she was trying to fit the rods into those holes and I gave her ample time to try. It really does seem like she's progressing and it's so fascinating to watch.

* Bed time

When she turned 1 year old, there was a massive sleep regression. At least it felt massive to me. She would have such a hard time going to sleep or staying asleep and it would be like that every night for perhaps 2 weeks. It was really hard, but now... now I couldn't ask for a better sleeper! Every night before bed, after I give her her nightly bath at 8:30 and brush her teeth and feed them pets we listen to /Isn't She Lovely/ By Stevie Wonder. I get so overwhelmed emotionally I cry often while listening to it with her and holding her as I sway to the music and she lays her head on my chest knowing I'm there for her and she feels comfortable falling asleep on me. The tears are welling up as I write this post.

I had no motivation to clean the house after she went to bed which is when I do a lot of my cleaning. I finally managed to start at 10pm, picked up all the toys from the living room and piled the dishes into the sink where they remain unwashed. Likewise, the drying machine remains full of clean clothes. "I'll do it tomorrow," I think to myself. Which is definitely, true, but I wish I had the resolve to do it today.

Anyway, after that was done, I went to take a shower. Before I got in the shower and after I shaved, I walk out of the bathroom to hear my legendary sleeper crying! I thought, "Well, if I hadn't walked out of the bathroom, I would have showered and she'd be back to sleep and I'd have never known she woke up." So I just took a shower. When I got out, maybe 20 minutes later, she was still crying. I can't help myself when it comes to her crying. I have to do something about it! I'm her dad, after all. So I went into console her and I'm not kidding when I say this, the moment I lifted her into my arms she was tranquil as can be. It melted me. I was so happy it was so easy for me to console her.

Speaking of, it's bed time for me now.
