#+TITLE: June 16, 2025
#+INCLUDE: ~/org/blog/noumena/header.org
#+INCLUDE: ~/org/blog/image-preview-header.org

#+HTML_HEAD_EXTRA:<meta property="og:image" content="https://joshua-wood.dev/noumena/2025/june/16/">
#+HTML_HEAD_EXTRA:<meta property="og:image:alt" content="June 16, 2025 alt"/>
#+HTML_HEAD_EXTRA:<meta property="og:description" content="">
#+HTML_HEAD_EXTRA:<meta name="twitter:image" content="https://joshua-wood.dev/noumena/2025/june/16/" />


* Good morning, Kiddo!

Noumena has been crawling in bed with Mommy and Daddy as of late. I was asleep when she awoke. Mommy usually feeds her breakfast and gets her ready for daycare and Noumena watches TV on the bed with me usually sleeping.

Noumena had gotten and was ready to head out the door by the time I had gotten up. She stood next to the bed holding her pink blanket—mouth down turned and lower lip furled. She says "I don't want to go to daycare" and I feel horrible I can't just keep her home with me. I love that girl more than the day is long and if I had the option, I would never take her to daycare. I think on the weekends we have so much fun that it makes Mondays all the more difficult.

Mommy tells Noumena about the tooth-fairy distracting her which works to calm her before leaving for the day.

* Noumena's Home!

Mommy picks Noumena up a little early, and when Noumena gets home I immediately go to greet her. She's made her way into the garage and she's looking for a matching cards memory game. Mommy coaxes her out of the garage and she finally sees me. For some reason, she doesn't rush excited to greet me. She hangs her head and it's not clear to me exactly what's motivating her behavior. I think I began to slowly back away and when I notice that she's interested, I lean away and start speeding up my walking down the hallway motivating her to give chase. When I finally allow Noumena to catch up to me, I scoop her up into my arms and shower her with affection before setting her down and chasing her. I then head back into my office to finish out my work day.

While working, I heard Noumena telling her mother to feed her and she's given a piece of bread to tide her over before dinner. When I finally finish up, I leave to go spend time with Noumena and notice she's on the couch helping Mommy package items up that Mommy is selling.

Mommy and I end up in a little argument and Noumena is scared so she hides behind me grabbing my leg. After we resolve it, Noumena enters the room and starts seemingly taking both of our sides in the argument. I'm not sure how to interpret her behavior. I don't even remember what she was yelling, but she would approach Mommy hands outstretched yelling god knows what and coming back to the foot of the bed where I'm standing to hug me.

After some discussion, Mommy and I decide that Noumena will come with me to Cava to eat and Mommy is going to figure out what to do on her own. I get Noumena to jump off my bed frame a few times before we get her shoes on and head out the door. The entire car ride to Cava she's playing with change we'd accrued and given to her to put in her purse.

* Cava

When we arrive at Cava, Noumena notices in her periphery some man walking and asks if he's Chris. She asks because she sort of expects Chris to be around given that like 70% of the time we go to Cava we go to meet up with him and eat. A woman named Jay asks us as we approach the building if we can help her out with food so I invite her to get food from Cava with us.

While Noumena and I wait in line, Jay is complementing how beautiful and smart she is thinking she's advanced for being three years old. We, of course, order our usual and part ways with Jay, fill our water cups and make our way outside to eat.

Noumena loves to eat outside. She loves to look at the birds as much as I do if not more. She gets so excited when she sees them she screams "DADDY LOOK!" We see quite a few house sparrows and a sparrow couple in a flowered tree I end up getting photos of.


* Walking To The YMCA Park

When we finish eating, I ask Noumena to walk down to the YMCA park and she agrees so we cross the street and once we're in a safe location, I hand her the water to walk along side me. I see what I thought was an animal, but turned out to be a piece of trash to my right so I go to investigate, Noumena running behind. Once I realize it's trash I pick it up to dispose of it and she begins running after me down the hill at one point dropping the cup she's holding. It doesn't spill, so I wait for her to get back up and continue along.

#+begin_export html
<div class="video-container">
<iframe width="358" height="637" src="https://www.youtube.com/embed/KPRM3XALomw" title="Walking And Drinking Water" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
#+end_export


* YMCA Playground

When Noumena and I get to the playground, we're the only ones there. Shortly after, a 1 year old Elias arrives with his grandparents. They try to give me a chick tract and I tell them I don't need that. The grandpa responds "what does anyone need?" and I told him the most appropriate answer for the activities: "Time with loved ones." Noumena plays while he and I talk for a bit.

Noumena's found her way to the spinning hollow spheres and one of them is full of water. Noumena splashes around despite my resistance to it. I'm just glad she's having fun.

At some point, Noumena decides it's time to start climbing the slide and despite failing several times never gives up and eventually gets all the way to the top of the steepest slide there. I'm she consistently makes me so proud with all the effort she puts in and continuing to get back up from failing over and over again.

While Noumena climbs, two young girls (2-year-old Ilyana and 3-year-old Azaria, affectionately called Ily and Zary respectively) arrive with their mother. We teeter-totter with them and their mother and play until they leave. We continue playing and finally Noumena wants to head down to the river bank. I put her over the fence, climb over it myself, jump over the hedge and have Noumena jump over the hedge into my outstretched arms and we make our way.

* Riverside

At the river bank, Noumena and I begin as usual throwing big rocks into the river when something catches her eye. Some of the concrete lining the river bank has rusty metal rods sticking out of them. She asks about them, so we go to investigate. I'm paranoid about tetanus, so I discourage her from touching the rusted metal. I can see that the metal is so corroded it flakes to the touch, so I take a stick and start hitting it off. Noumena of course wants to try after me, so I hand her the stick and she hits the rods also flaking off the rust. This is when we spot a Great Blue Heron. She wants to take a closer look so we bounce along the concrete blocks and get close.

Eventually, I decide it's time to go. I had lost track of time with all the fun we were having and I don't check the time until it's already 8pm. Noumena's bed time is in thirty minutes and since she got so dirty at the park, there's no way she can go to bed without bathing. I inform her of this before telling her we have to get to the car and ask her if she wants to take a shower with me. She elects for a bath and we take ten minutes to walk back to the car. Noumena is so affectionate as I walk back to the car kissing me several times over and over and telling me she loves me.

Noumea is playing with coins on the way back—the same change she played with on the way to Cava—but she ends up losing some of it and is really upset by it. I wasn't sure exactly how to react so, I just reaffirmed what she said and talked about how I might feel sad if I lost something I really wanted to play with. I asked her how she felt and she said "sad" and then I asked her to tell me where she felt the sadness in her body at which point she pointed to her tummy. I asked where she though I felt sadness and again she pointed to her tummy. At some point, telling her we'd find the coins when we got back to the house and that I'd help her find them when I stopped driving along with reaffirming her feelings calms her down and she just says "I feel better." Once again, this girl makes me so proud that she's able to articulate and contrast her feelings temporally.

* Bath Time

We arrive at home and I make sure Noumena understands that there's no time for playing around and that we need to get in the bath right away. She complies after needing a little assistance removing her shirt and undresses the rest of the way on her own putting her clothes in her dirty-laundry hamper.

I try to insist that we need to get out of the bath immediately once Noumena's scrubbed and clean. She bargains for 3 minutes to which I oblige and get her pajamas ready while I set a timer for 3 minutes for her to continue playing.

* Bed Time

Finally, after Noumena brushes her teeth, Mommy had invented a game to play a trick on the tooth-fairy by putting a hair clip in a small, tin, tooth-container so that when the tooth-fairy will be deceived and then upset that she's not getting a tooth. Mommy, gives the container to Noumena, Noumena places it under her pillow and we lay down to get to sleep.

Noumena sits quietly falling asleep arms wrapped around my neck. Because I find it so odd that she's being so quiet, not asking for stories or to watch videos or anything, I ask her what she's thinking about. Her knee-jerk reaction is to say "nothing", but the question sits with her a few seconds longer before she meekly remarks "I'm thinking about you." I pause to sit with this information for a few seconds before asking her what she thinks about me. She considers for less than a second before expressing "I love you." In this moment I can tell you that I have never felt so fulfilled. There is nothing more magical to me than this little girl's love. To think she /thinks/ this of me. Nothing could have prepared me for the idea that she was sitting there bound in silence embracing me pondering how she loves me. Even now, writing these words it feels surreal.

Goodnight, beautiful. You've made my life better than I could have ever imagined.
