#+TITLE: Problem of Evil
#+DESCRIPTION: Notes on the Logical Problem Of Evil Dialectic
#+AUTHOR: Josh

The quote falsely but nevertheless frequently attributed to Dostoevsky, "If there is no God, everything is permitted."

* Problem of Evil

#+begin_quote
  Good is /opposed/ to evil in such a way that a being who is wholly good eliminates evil as far as he can.
  - J.L. Mackie
#+end_quote

* Definitions
*** Omipotence
+ A property of an agent whereby the agent can do any logically possible action.

*** Omnibenevolence
+ A property of an agent whereby the agent exemplifies no evil properties.

*** Omniscience
+ A property of an agent whereby the agent knows all knowable propositions and believes no false propositions.

*** Evil
**** Normative Notion
+ The normative conception of evil is just understood as something which one ought not bring about.
+ Evil properties are properties of states of affairs that ought not be brought about.
**** Non-normative Notion
+ The non-normative conception of evil is understood as inconsistent with good.
  + e.g. A perfectly effective chair destroying machine, /i.e./ a machine that destroys chairs the moment they come into existence, is not consistent inconsistent with chairs existing.

* The Argument

1. If evil is understood as a state of affairs that ought not be brought about and God is understood as an omnipotent, omniscient, and omnibenevolent being, then He would prevent or eliminate evil.

2. Evil is understood as a state of affairs that ought not be brought about and God is understood as an omnipotent, omnicient, and omnibenevolent being.

3. Therefore he would prevent or eliminate evil.

4. If God exists and he prevents or eliminates evil, there is no evil.

5. God exists. (assumed from traditional theism)

6. There is no evil.

7. There is evil. (assumed from traditional theism)

   + Reductio ad absurdum.

* Responses
** Free Will Defense
